Repository wix/yoshi, pull requests merged in 2018-12, with the labels that each got.

#871 Add a test that verifies directory listing in assets directory
  test/kitchensink/integration/dev-server.test.js
Labels: PR: Internal :house:

#874 make test consistent
  test/kitchensink/integration/dev-server.test.js
Labels: PR: Internal :house:

#807 Add documentation for stylesheet linting
  docs/api/cli.md
  docs/guides/stylelint-setup.md
  packages/stylelint-config-yoshi/README.md
  website/sidebars.json
Labels: PR: Docs :memo:

#896 Change Typescript transpliation target for ES modules
  packages/yoshi-config/index.js
  packages/yoshi-config/schema/yoshi-config-schema.json
  packages/yoshi/src/commands/build.js
Labels: PR: New Feature :rocket:

#897 Server bundle experiment should respect `hmr` config
  packages/yoshi/src/commands/start-app.js
Labels: PR: Bug Fix :bug:
