Repository wix/yoshi, pull requests merged in 2018-11, with the labels that each got.

#695 Format TypeScript errors with react-dev-utils
  packages/yoshi/config/webpack.config.js
Labels: PR: Polish :nail_care:

#692 Write client files to the file system and show them nicely via serve-handler
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
  packages/yoshi/src/webpack-utils.js
Labels: PR: New Feature :rocket:

#693 Run fork-ts-checker-webpack-plugin only once
  packages/yoshi/config/webpack.config.js
Labels: PR: Polish :nail_care:

#691 Transpile server bundle to Node version 8
  packages/yoshi/config/webpack.config.js
Labels: PR: Polish :nail_care:

#688 validate @wix email on project generation
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/src/getQuestions.js
  packages/create-yoshi-app/src/runPrompt.js
Labels: PR: New Feature :rocket:

#734 Open browser on start (#539)
  packages/yoshi/src/commands/start.js
  packages/yoshi/src/tasks/app-server/index.js
Labels: PR: Internal :house:

#745 Change prettier errors to warnings instead of errors
  packages/eslint-config-yoshi-base/index.js
Labels: PR: New Feature :rocket:

#747 Fix flaky tests related to `yoshi start`
  packages/yoshi/test/start.spec.js
Labels: PR: Internal :house:

#715 Small webpack improvements
  packages/yoshi/config/webpack.config.js
  packages/yoshi/test/build.spec.js
Labels: PR: Polish :nail_care:

#716 Show a loading indication when starting a local development setup
  packages/yoshi/src/commands/start-app.js
Labels: PR: Polish :nail_care:

#714 Move from uglifyjs to terserjs
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
Labels: PR: Polish :nail_care:

#711 Use cssnano as a CSS minifier
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
  packages/yoshi/test/build.spec.js
Labels: PR: New Feature :rocket:

#712 Migrate to ESlint version 5
  package.json
  packages/eslint-config-yoshi-base/index.js
  packages/eslint-config-yoshi-base/package.json
  packages/eslint-config-yoshi/index.js
  packages/yoshi/package.json
Labels: PR: New Feature :rocket:

#754 Run two different typescript typechecks
  packages/yoshi/config/webpack.config.js
Labels: PR: Bug Fix :bug:

#750 Lint Stylesheets by default
  packages/create-yoshi-app/templates/business-manager-module-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/{%packagejson%}
  packages/create-yoshi-app/templates/client-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/{%packagejson%}
  packages/create-yoshi-app/templates/component-library-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/component-library/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/{%packagejson%}
  packages/create-yoshi-app/templates/universal-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/universal/{%packagejson%}
  packages/stylelint-config-yoshi/index.js
  packages/stylelint-config-yoshi/package.json
  packages/yoshi/package.json
  packages/yoshi/src/commands/lint.js
  packages/yoshi/src/tasks/stylelint.js
  packages/yoshi/test/lint.spec.js
Labels: PR: New Feature :rocket:, 📝 WIP

#770 Fix yoshi not outputing verbose errors on CI
  packages/yoshi/bin/yoshi-cli.js
Labels: PR: Bug Fix :bug:

#769 Improve e2e errors by using `it` instead of `before`
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/scripts/runE2E.js
Labels: PR: Internal :house:

#772 Setup webpack-dev-server on https if it has been configured from cli or from config
  packages/yoshi/src/commands/start-app.js
  packages/yoshi/src/webpack-utils.js
Labels: 🐛 Bug

#771 Watch public dir during start and sync the static dir with changes
  packages/yoshi/src/commands/start-app.js
  packages/yoshi/src/webpack-utils.js
Labels: 🐛 Bug

#780 Change the public dir from public to src/assets
  packages/yoshi-config/paths.js
  packages/yoshi/src/commands/build-app.js
  packages/yoshi/src/commands/start-app.js
Labels: PR: Polish :nail_care:, 📝 WIP

#786 prettier all the markdown files
  docs/api/cli.md
  docs/api/configuration.md
  docs/getting-started/create-app.md
  docs/getting-started/project-types.md
  docs/getting-started/usage.md
  docs/guides/ab-translate.md
  docs/guides/assets.md
  docs/guides/babel-setup.md
  docs/guides/bundle-analyze.md
  docs/guides/debugging.md
  docs/guides/disable-css-modules.md
  docs/guides/enzyme-support.md
  docs/guides/export-es-modules.md
  docs/guides/hmr.md
  docs/guides/jest-setup.md
  docs/guides/split-chunks.md
  docs/guides/svg.md
Labels: PR: Polish :nail_care:

#789 prettify markdowns pre-commit hook
  package.json
Labels: PR: Internal :house:

#778 wrong file name format in the md template of business-manager-module
  packages/create-yoshi-app/templates/business-manager-module-typescript/README.md
  packages/create-yoshi-app/templates/business-manager-module/README.md
Labels: ❔ Need more information

#735 Start a forward proxy to intercept public cdn requests to the local cdn
  packages/jest-environment-yoshi-puppeteer/cdnProxy.js
  packages/jest-environment-yoshi-puppeteer/globalSetup.js
  packages/jest-environment-yoshi-puppeteer/globalTeardown.js
  packages/yoshi-helpers/constants.js
  packages/yoshi-helpers/index.js
  packages/yoshi-helpers/package.json
  packages/yoshi-helpers/queries.js
  packages/yoshi-helpers/rewrite-forward-proxy.js
  packages/yoshi-helpers/server.cert
  packages/yoshi-helpers/server.key
  packages/yoshi-helpers/utils.js
  packages/yoshi/config/protractor.conf.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
  packages/yoshi/src/constants.js
  packages/yoshi/test/test.spec.js
Labels: PR: Bug Fix :bug:

#799 Run lint on a separate command (for PR CI)
  package.json
Labels: PR: Internal :house:

#804 Run eslint on website/templates instead of ignoring them
  .eslintignore
  .eslintrc
  packages/create-yoshi-app/templates/business-manager-module-typescript/protractor.conf.js
  packages/create-yoshi-app/templates/client-typescript/vm.js
  packages/create-yoshi-app/templates/client-typescript/wallaby.js
  packages/create-yoshi-app/templates/client/test/setup.e2e.js
  packages/create-yoshi-app/templates/client/vm.js
  packages/create-yoshi-app/templates/platform-app/src/client.js
  packages/create-yoshi-app/templates/platform-app/src/components/App/App.js
  packages/create-yoshi-app/templates/platform-app/src/platform/viewerScript.js
  packages/create-yoshi-app/templates/platform-app/test/setup.e2e.js
  packages/create-yoshi-app/templates/platform-app/vm.js
  packages/create-yoshi-app/templates/server-typescript/index.js
  packages/create-yoshi-app/templates/universal-typescript/index.js
  packages/eslint-config-yoshi-base/__tests__/eslint-config-yoshi-base.spec.js
Labels: PR: Internal :house:

#810 add uglifyjs-webpack-plugin as a dep to yoshu
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#811 Update travis settings
  .travis.yml
Labels: PR: Internal :house:

#814 mock `verifyRegistry` for unit tests
  packages/create-yoshi-app/__tests__/createApp.spec.js
Labels: PR: Internal :house:

#817 fix travis to work with puppeteer
  .travis.yml
Labels: PR: Internal :house:

#812 Mention tags used for changelog in contributing guide
  CONTRIBUTING.md
Labels: PR: Docs :memo:

#831 Remove forward proxy from protractor
  packages/yoshi/config/protractor.conf.js
Labels: PR: Bug Fix :bug:

#801 Log test execution output if the test failed
  packages/yoshi/test/build.spec.js
  packages/yoshi/test/config.spec.js
  packages/yoshi/test/e2e.spec.js
  packages/yoshi/test/jasmine.spec.js
  packages/yoshi/test/lint.spec.js
  packages/yoshi/test/loaders.spec.js
  packages/yoshi/test/start.spec.js
  packages/yoshi/test/test.spec.js
  packages/yoshi/test/webpack-config.spec.js
  test-helpers/test-phases.js
Labels: PR: Internal :house:

#834 Merge user defined puppeteer args with default args
  packages/jest-environment-yoshi-puppeteer/globalSetup.js
  packages/yoshi/test/test.spec.js
Labels: PR: Bug Fix :bug:

#835 Ignore ssl errors when proxying requests to the local cdn
  packages/yoshi-helpers/rewrite-forward-proxy.js
  packages/yoshi/config/protractor.conf.js
  packages/yoshi/test/test.spec.js
  test-helpers/fixtures.js
Labels: PR: Bug Fix :bug:

#826 Improve test:app-flow infra
  scripts/runKitchensink.js
  test/kitchensink/config/buildEnvironment.js
  test/kitchensink/config/buildGlobalSetup.js
  test/kitchensink/config/buildGlobalTeardown.js
  test/kitchensink/config/plainEnvironment.js
  test/kitchensink/config/plainGlobalSetup.js
  test/kitchensink/config/plainGlobalTeardown.js
  test/kitchensink/config/startEnvironment.js
  test/kitchensink/config/startGlobalSetup.js
  test/kitchensink/config/startGlobalTeardown.js
  test/kitchensink/jest-puppeteer.config.js
  test/kitchensink/jest.build.config.js
  test/kitchensink/jest.plain.config.js
  test/kitchensink/jest.start.config.js
  test/scripts.js
Labels: PR: Internal :house:

#815 Fix app flow tests on version 4.x
  packages/babel-preset-yoshi/package.json
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
  test/kitchensink/babel.config.js
  test/kitchensink/integration/webpack.test.js
  test/kitchensink/package.json
Labels: PR: Internal :house:

#816 Add no-extraneous-dependencies to eslintrc
  .eslintrc
  package.json
  packages/create-yoshi-app/package.json
  packages/eslint-config-yoshi-base/package.json
  packages/tslint-config-yoshi-base/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi/package.json
Labels: PR: Internal :house:

#837 Migrate templates to scoped packages
  packages/create-yoshi-app/templates/business-manager-module-typescript/src/client.tsx
  packages/create-yoshi-app/templates/business-manager-module-typescript/test/mocha-setup.ts
  packages/create-yoshi-app/templates/business-manager-module-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/src/client.js
  packages/create-yoshi-app/templates/business-manager-module/test/mocha-setup.js
  packages/create-yoshi-app/templates/business-manager-module/{%packagejson%}
  packages/create-yoshi-app/templates/client-typescript/src/client.tsx
  packages/create-yoshi-app/templates/client-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/src/client.js
  packages/create-yoshi-app/templates/client/{%packagejson%}
  packages/create-yoshi-app/templates/component-library-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/component-library/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack-typescript/index.js
  packages/create-yoshi-app/templates/fullstack-typescript/src/client.tsx
  packages/create-yoshi-app/templates/fullstack-typescript/src/server.ts
  packages/create-yoshi-app/templates/fullstack-typescript/src/test-types.d.ts
  packages/create-yoshi-app/templates/fullstack-typescript/test/environment.js
  packages/create-yoshi-app/templates/fullstack-typescript/tsconfig.json
  packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/index.js
  packages/create-yoshi-app/templates/fullstack/src/client.js
  packages/create-yoshi-app/templates/fullstack/src/server.js
  packages/create-yoshi-app/templates/fullstack/test/environment.js
  packages/create-yoshi-app/templates/fullstack/{%packagejson%}
  packages/create-yoshi-app/templates/node-library-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/node-library/{%packagejson%}
  packages/create-yoshi-app/templates/platform-app/src/client.js
  packages/create-yoshi-app/templates/platform-app/{%packagejson%}
  packages/create-yoshi-app/templates/server-typescript/index.js
  packages/create-yoshi-app/templates/server-typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/server-typescript/src/server.ts
  packages/create-yoshi-app/templates/server-typescript/test/environment.ts
  packages/create-yoshi-app/templates/server-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/server/index.js
  packages/create-yoshi-app/templates/server/src/server.js
  packages/create-yoshi-app/templates/server/test/environment.js
  packages/create-yoshi-app/templates/server/{%packagejson%}
  packages/create-yoshi-app/templates/universal-typescript/index.js
  packages/create-yoshi-app/templates/universal-typescript/src/client.tsx
  packages/create-yoshi-app/templates/universal-typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/universal-typescript/src/server.tsx
  packages/create-yoshi-app/templates/universal-typescript/test/environment.ts
  packages/create-yoshi-app/templates/universal-typescript/test/it/server.spec.ts
  packages/create-yoshi-app/templates/universal-typescript/test/mocha-setup.ts
  packages/create-yoshi-app/templates/universal-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/universal/index.js
  packages/create-yoshi-app/templates/universal/src/client.js
  packages/create-yoshi-app/templates/universal/src/server.js
  packages/create-yoshi-app/templates/universal/test/environment.js
  packages/create-yoshi-app/templates/universal/test/it/server.spec.js
  packages/create-yoshi-app/templates/universal/test/mocha-setup.js
  packages/create-yoshi-app/templates/universal/{%packagejson%}
Labels: 📝 WIP

#840 fix killing of server process and its children, for travis-ci
  package.json
  packages/jest-environment-yoshi-puppeteer/globalTeardown.js
  packages/yoshi-helpers/package.json
  packages/yoshi-helpers/utils.js
  packages/yoshi/package.json
  packages/yoshi/test/jasmine.spec.js
  packages/yoshi/test/migrate-to-scoped-packages.spec.js
  packages/yoshi/test/start.spec.js
  packages/yoshi/test/webpack-config.spec.js
  test-helpers/process.js
Labels: PR: Internal :house:

#752 Increase max retries for tests, so they'll pass locally
  packages/yoshi/test/jasmine.spec.js
  packages/yoshi/test/start.spec.js
  test-helpers/test-phases.js
Labels: PR: Internal :house:

#851 Improve app-flow tests and add missing tests
  packages/yoshi/config/webpack.config.js
  scripts/runKitchensink.js
  test/kitchensink/integration/analyze.test.js
  test/kitchensink/integration/dev-server.test.js
  test/kitchensink/integration/entries.test.js
  test/kitchensink/integration/env-vars.test.js
  test/kitchensink/integration/externals.test.js
  test/kitchensink/integration/hmr.test.js
  test/kitchensink/integration/loaders.test.js
  test/kitchensink/integration/moment.test.js
  test/kitchensink/integration/optimize.test.js
  test/kitchensink/integration/statics.test.js
  test/kitchensink/integration/transpile-externals.test.js
  test/kitchensink/jest.build.config.js
  test/kitchensink/jest.plain.config.js
  test/kitchensink/jest.start.config.js
  test/kitchensink/package.json
  test/kitchensink/src/components/App.js
  test/kitchensink/src/components/features/assets/auto-prefixer.css
  test/kitchensink/src/components/features/assets/auto-prefixer.less
  test/kitchensink/src/components/features/assets/auto-prefixer.sass
  test/kitchensink/src/components/features/assets/auto-prefixer.scss
  test/kitchensink/src/components/features/assets/module-with-multiple-exports.js
  test/kitchensink/src/components/features/assets/module-with-unused-exports.js
  test/kitchensink/src/components/features/css-auto-prefixer.js
  test/kitchensink/src/components/features/env-vars.js
  test/kitchensink/src/components/features/externals.js
  test/kitchensink/src/components/features/global-css-inclusion.js
  test/kitchensink/src/components/features/global-less-inclusion.js
  test/kitchensink/src/components/features/global-sass-inclusion.js
  test/kitchensink/src/components/features/global-scss-inclusion.js
  test/kitchensink/src/components/features/less-auto-prefixer.js
  test/kitchensink/src/components/features/sass-auto-prefixer.js
  test/kitchensink/src/components/features/scss-auto-prefixer.js
  test/kitchensink/src/components/features/tree-shaking-unused-export.js
  test/kitchensink/src/index.html
  test/scripts.js
  test/utils.js
Labels: PR: Internal :house:

#844 Move hmr to webpack config
  packages/yoshi/config/webpack.config.js
  packages/yoshi/src/commands/start-app.js
  packages/yoshi/src/webpack-utils.js
  packages/yoshi/test/webpack-config.spec.js
  test/utils.js
Labels: PR: Internal :house:

#856 Add missing app-flow tests for build output
  .eslintignore
  packages/yoshi/config/webpack.config.js
  test/kitchensink/integration/output.test.js
  test/kitchensink/package.json
  test/kitchensink/src/errors/clientBabel.js
  test/kitchensink/src/errors/clientCaseSensitive.js
  test/kitchensink/src/errors/clientCss.css
  test/kitchensink/src/errors/clientCss.js
  test/utils.js
Labels: PR: Internal :house:

#857 add support for css
  packages/jest-yoshi-preset/jest-preset.js
Labels: PR: New Feature :rocket:

#843 Puppeteer: tearing down Parent Environment and no throw on `pageerror`
  packages/jest-environment-yoshi-puppeteer/index.js
Labels: PR: Bug Fix :bug:
