Repository wix/yoshi, pull requests merged in 2018-09, with the labels that each got.

#549 Simplify server code and add basic annotations to it
  packages/create-yoshi-app/templates/fullstack-typescript/index.js
  packages/create-yoshi-app/templates/fullstack-typescript/src/index.ejs
  packages/create-yoshi-app/templates/fullstack-typescript/src/server.ts
  packages/create-yoshi-app/templates/fullstack/index.js
  packages/create-yoshi-app/templates/fullstack/src/index.ejs
  packages/create-yoshi-app/templates/fullstack/src/server.js
Labels: PR: New Feature :rocket:

#560 Update univeral project config
  docs/faq/YOSHI-API.md
  packages/create-yoshi-app/scripts/e2e.js
  packages/yoshi/config/yoshi-config-schema.json
Labels: PR: Bug Fix :bug:

#561 Simplify local (fake) server for client projects
  packages/create-yoshi-app/templates/client-typescript/index.js
  packages/create-yoshi-app/templates/client-typescript/test/dev/server.ts
  packages/create-yoshi-app/templates/client-typescript/test/dev/vm.ts
  packages/create-yoshi-app/templates/client-typescript/vm.js
  packages/create-yoshi-app/templates/client/index.js
  packages/create-yoshi-app/templates/client/test/dev/server.js
  packages/create-yoshi-app/templates/client/test/dev/vm.js
  packages/create-yoshi-app/templates/client/vm.js
Labels: PR: New Feature :rocket:

#564 Add direct dependency on lodash to yoshi-helpers
  packages/yoshi-helpers/package.json
Labels: 🐛 Bug

#566 don't show webpack performance hints by default
  packages/yoshi/config/webpack.config.client.js
Labels: PR: Bug Fix :bug:

#537 create-yoshi-app node version verification
  packages/create-yoshi-app/__tests__/verifyMinimumNodeVersion.spec.js
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/src/createApp.js
  packages/create-yoshi-app/src/verifyMinimumNodeVersion.js
Labels: PR: New Feature :rocket:

#540 Generate git repo when requested
  packages/create-yoshi-app/__tests__/__fixtures__/minimal-template/package.json
  packages/create-yoshi-app/__tests__/createApp.spec.js
  packages/create-yoshi-app/src/createApp.js
  packages/create-yoshi-app/src/utils.js
Labels: PR: New Feature :rocket:

#538 wait for app-server port before finishing app-server task
  packages/yoshi/package.json
  packages/yoshi/src/tasks/app-server/index.js
  packages/yoshi/test/helpers/fixtures.js
  packages/yoshi/test/start.spec.js
Labels: PR: New Feature :rocket:

#579 Upgrade "typescript" package version
  packages/yoshi-helpers/package.json
Labels: PR: Polish :nail_care:

#592 change xml2js with xmldoc and compute artifact id from pom.xml
  packages/yoshi-config/paths.js
  packages/yoshi-helpers/package.json
  packages/yoshi-helpers/utils.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
  packages/yoshi/src/tasks/maven-statics/index.js
  packages/yoshi/src/tasks/maven-statics/utils.js
  packages/yoshi/test/webpack-config.spec.js
  test-helpers/fixtures.js
Labels: PR: Bug Fix :bug:

#596 add @types/node version 8 as version 10 clashes with typescript
  packages/create-yoshi-app/templates/server-typescript/{%packagejson%}
Labels: PR: Bug Fix :bug:

#594 integrate algolia search and add command to run the site from the root
  package.json
  website/siteConfig.js
Labels: PR: New Feature :rocket:

#593 Fix webpack's public path for local development
  packages/yoshi-config/index.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/src/commands/start.js
  packages/yoshi/test/webpack-config.spec.js
Labels: PR: Bug Fix :bug:
