Repository wix/yoshi, pull requests merged in 2018-10, with the labels that each got.

#588 prefer local yoshi installation when using cli
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/bin/yoshi.js
  packages/yoshi/package.json
Labels: PR: Polish :nail_care:

#591 yoshi: Add `--stats` flag to generate `dist/webpack-stats.json`
  docs/api/cli.md
  docs/guides/bundle-analyze.md
  packages/yoshi-config/paths.js
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/src/commands/build.js
  packages/yoshi/test/build.spec.js
Labels: PR: New Feature :rocket:

#582 process unprocessedModules with graphql loader
  packages/yoshi/config/webpack.config.js
  packages/yoshi/test/loaders.spec.js
Labels: PR: New Feature :rocket:

#573 enable opt-in to build with devtool: source-map
  docs/api/cli.md
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/src/commands/build.js
  packages/yoshi/test/build.spec.js
  packages/yoshi/test/loaders.spec.js
Labels: PR: Bug Fix :bug:

#615 Improve lint on typescript templates
  packages/create-yoshi-app/templates/business-manager-module-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client-typescript/tsconfig.json
  packages/create-yoshi-app/templates/client-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/component-library-typescript/tsconfig.json
  packages/create-yoshi-app/templates/component-library-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack-typescript/tsconfig.json
  packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/node-library-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/server-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/universal-typescript/tsconfig.json
  packages/create-yoshi-app/templates/universal-typescript/{%packagejson%}
Labels: PR: Polish :nail_care:

#539 Open browser on start
  packages/yoshi/package.json
  packages/yoshi/src/commands/start.js
  packages/yoshi/src/tasks/app-server/index.js
Labels: PR: New Feature :rocket:

#621 Remove the duplicate package checker plugin
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
  packages/yoshi/test/webpack-config.spec.js
Labels: PR: Polish :nail_care:

#618 Forward jest options
  docs/api/cli.md
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/src/commands/test.js
  packages/yoshi/test/test.spec.js
Labels: PR: New Feature :rocket:

#586 Server-side bundle MVP
  packages/bootstrap-hot-loader/README.md
  packages/bootstrap-hot-loader/hot.dev.js
  packages/bootstrap-hot-loader/hot.prod.js
  packages/bootstrap-hot-loader/index.js
  packages/bootstrap-hot-loader/package.json
  packages/create-yoshi-app/templates/fullstack/public/hello.world
  packages/yoshi-config/index.js
  packages/yoshi-config/paths.js
  packages/yoshi-config/utils/yoshi-config-schema.json
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/config/hot.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
  packages/yoshi/src/commands/build-app.js
  packages/yoshi/src/commands/start-app.js
  packages/yoshi/src/constants.js
  packages/yoshi/src/tasks/app-server/index.js
  packages/yoshi/src/webpack-utils.js
Labels: PR: New Feature :rocket:

#619 fix wallaby configuration when working with jest
  packages/create-yoshi-app/templates/client-typescript/wallaby.js
  packages/create-yoshi-app/templates/client/wallaby.js
  packages/create-yoshi-app/templates/fullstack-typescript/wallaby.js
  packages/create-yoshi-app/templates/fullstack/wallaby.js
  packages/yoshi/config/wallaby-common.js
  packages/yoshi/config/wallaby-jest.js
  packages/yoshi/config/wallaby-mocha.js
Labels: PR: Bug Fix :bug:

#633 fix generated launch.json for vscode across templates
  packages/create-yoshi-app/templates/client-typescript/.vscode/launch.json
  packages/create-yoshi-app/templates/client/.vscode/launch.json
  packages/create-yoshi-app/templates/component-library-typescript/.vscode/launch.json
  packages/create-yoshi-app/templates/component-library/.vscode/launch.json
  packages/create-yoshi-app/templates/fullstack-typescript/.vscode/launch.json
  packages/create-yoshi-app/templates/fullstack/.vscode/launch.json
  packages/create-yoshi-app/templates/node-library-typescript/.vscode/launch.json
  packages/create-yoshi-app/templates/node-library/.vscode/launch.json
  packages/create-yoshi-app/templates/server-typescript/.vscode/launch.json
  packages/create-yoshi-app/templates/server/.vscode/launch.json
  packages/create-yoshi-app/templates/universal-typescript/.vscode/launch.json
  packages/create-yoshi-app/templates/universal/.vscode/launch.json
Labels: PR: Bug Fix :bug:

#640 Do nothing during npm test command
  package.json
Labels: PR: Internal :house:

#647 update rtlcss-webpack-plugin version
  packages/yoshi/package.json
Labels: PR: Polish :nail_care:

#648 Copy .ejs/.vm files to dist/statics in experimental server bundle
  packages/yoshi/src/commands/build-app.js
Labels: PR: Bug Fix :bug:

#612 Sentry error reporting
  packages/create-yoshi-app/package.json
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/package.json
  packages/yoshi/src/cli.js
  packages/yoshi/src/commands/build-app.js
  packages/yoshi/src/commands/build.js
  packages/yoshi/src/commands/info.js
  packages/yoshi/src/commands/lint.js
  packages/yoshi/src/commands/test.js
  packages/yoshi/src/constants.js
  packages/yoshi/src/env-info.js
  packages/yoshi/src/error-handler.js
  packages/yoshi/src/sentry.js
  packages/yoshi/src/tasks/protractor/index.js
  website/static/error-feedback.html
Labels: PR: Internal :house:, 🛠 Infrastructure

#679 handle dep check errors on build
  packages/yoshi/src/commands/build.js
Labels: PR: Bug Fix :bug:

#680 Move the docs for babel-preset-yoshi and jest-yoshi-preset to the docs website
  docs/guides/babel-setup.md
  docs/guides/jest-setup.md
  website/sidebars.json
Labels: PR: Docs :memo:

#677 Look for a fake-server entry if the standard server entry isn't found
  packages/yoshi/config/webpack.config.js
Labels: PR: New Feature :rocket:

#678 Remove headless: true default from puppeteer.launch call
  packages/jest-environment-yoshi-puppeteer/globalSetup.js
Labels: PR: Bug Fix :bug:

#683 print error messages and add verbose flag for full stacktrace
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/src/sentry.js
Labels: PR: New Feature :rocket:

#610 create-yoshi-app: sort projects by priority
  CONTRIBUTING.md
  packages/create-yoshi-app/README.md
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/src/getProjectTypes.js
  packages/create-yoshi-app/src/getQuestions.js
  packages/create-yoshi-app/src/index.js
  packages/create-yoshi-app/src/projects.js
Labels: PR: New Feature :rocket:

#706 Add globby as dependency
  packages/jest-environment-yoshi-puppeteer/package.json
Labels: PR: Bug Fix :bug:
