Repository wix/yoshi, pull requests merged in 2019-10, with the labels that each got.

#1570 CYA - Fullstack stricter tsconfig
  packages/create-yoshi-app/templates/fullstack/typescript/src/client.tsx
  packages/create-yoshi-app/templates/fullstack/typescript/src/components/App/App.spec.tsx
  packages/create-yoshi-app/templates/fullstack/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/fullstack/typescript/src/components/__mocks__/i18n.ts
  packages/create-yoshi-app/templates/fullstack/typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/fullstack/typescript/src/i18n.ts
  packages/create-yoshi-app/templates/fullstack/typescript/src/server.ts
  packages/create-yoshi-app/templates/fullstack/typescript/tsconfig.json
Labels: PR: Polish :nail_care:

#1558 CYA - BM stricter tsconfig
  packages/create-yoshi-app/templates/business-manager-module/javascript/__tests__/e2e/drivers/app.driver.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/src/client.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/src/i18n.js
  packages/create-yoshi-app/templates/business-manager-module/typescript/__tests__/dev/environment.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/__tests__/dev/server.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/__tests__/e2e/app.e2e.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/__tests__/e2e/drivers/app.driver.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/client.tsx
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/components/App/App.spec.tsx
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/components/__mocks__/i18n.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/i18n.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/module.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/tsconfig.json
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
Labels: PR: Polish :nail_care:

#1583 Fix BM template by emitting TS src files again
  packages/create-yoshi-app/templates/business-manager-module/typescript/tsconfig.json
Labels: PR: Bug Fix :bug:

#1585 Add EditorConfig extension as recommended for VSCode
  packages/create-yoshi-app/templates/client/javascript/.vscode/extensions.json
  packages/create-yoshi-app/templates/client/typescript/.vscode/extensions.json
  packages/create-yoshi-app/templates/fullstack/javascript/.vscode/extensions.json
  packages/create-yoshi-app/templates/fullstack/typescript/.vscode/extensions.json
  packages/create-yoshi-app/templates/library/javascript/.vscode/extensions.json
  packages/create-yoshi-app/templates/library/typescript/.vscode/extensions.json
  packages/create-yoshi-app/templates/server/javascript/.vscode/extensions.json
  packages/create-yoshi-app/templates/server/typescript/.vscode/extensions.json
Labels: PR: Polish :nail_care:

#1590 Add Carmi support via Webpack loader
  packages/yoshi/config/webpack.config.js
Labels: PR: New Feature :rocket:

#1601 Bump template e2e test timeout from 10m to 20m
  packages/create-yoshi-app/scripts/runE2E.js
Labels: PR: Internal :house:

#1492 fix migration guide v4 for yarn workspaces
  docs/migration/version-4.md
Labels: PR: Docs :memo:

#1594 BM Template migration to @testing-library/react
  packages/create-yoshi-app/templates/business-manager-module/javascript/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/src/components/App/App.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/src/components/App/App.spec.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/typescript/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/components/App/App.spec.tsx
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
Labels: PR: Polish :nail_care:

#1604 Always run template e2e tests with verbose output
  packages/create-yoshi-app/scripts/e2e.js
Labels: PR: Internal :house:

#1603 Support starting multiple apps with different dev-server/hmr settings
  packages/yoshi/config/webpack.config.js
  packages/yoshi/src/commands/utils/start-single-app.js
  packages/yoshi/src/webpack-utils.js
Labels: PR: Polish :nail_care:, 🏘️ Monorepo

#1596 Update templates to 9.3 @testing-library/react
  packages/create-yoshi-app/templates/client/javascript/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/client/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/javascript/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
Labels: PR: Polish :nail_care:

#1591 Add support for Svelte as a Webpack loader
  packages/yoshi/config/webpack.config.js
Labels: PR: New Feature :rocket:

#1597 Show warning if no server entry point was found
  packages/yoshi/package.json
  packages/yoshi/src/commands/start.js
  packages/yoshi/src/tasks/app-server/index.js
  packages/yoshi/test/start.spec.js
Labels: PR: New Feature :rocket:

#1595 Migrate OOI templates to @testing-library/react
  packages/create-yoshi-app/templates/out-of-iframe/javascript/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/Settings/Settings.spec.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/Widget/Widget.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/Widget/Widget.spec.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Settings/Settings.spec.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/Widget.spec.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/Widget.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
Labels: PR: Polish :nail_care:

#1606 Don't handle local dependencies on the same monorepo as external for server bundle
  packages/yoshi-config/load-packages.d.ts
  packages/yoshi-config/load-packages.js
  packages/yoshi-config/packages.d.ts
  packages/yoshi-config/packages.js
  packages/yoshi-config/src/packages.ts
  packages/yoshi/config/webpack.config.js
  packages/yoshi/src/commands/build-monorepo.js
  packages/yoshi/src/commands/release-monorepo.js
  packages/yoshi/src/commands/start-monorepo.js
Labels: PR: Polish :nail_care:, 🏘️ Monorepo

#1607 Increase e2e test timeout and puppeteer navigation timeout
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/index.js
  packages/jest-yoshi-preset/setup/e2e.js
Labels: PR: Polish :nail_care:

#1609 Set Svelte's hydratable to true by default
  packages/yoshi/config/webpack.config.js
Labels: PR: Polish :nail_care:

#1610 Copy public folder to correct location for monorepos
  packages/yoshi/src/commands/utils/start-single-app.js
Labels: PR: Bug Fix :bug:, 🏘️ Monorepo

#1598 Migrate create-yoshi-app to TypeScript
  packages/create-yoshi-app/__tests__/TemplateModel.test.ts
  packages/create-yoshi-app/__tests__/__snapshots__/create-yoshi-app.test.ts.snap
  packages/create-yoshi-app/__tests__/__snapshots__/generateProject.test.ts.snap
  packages/create-yoshi-app/__tests__/create-yoshi-app.test.ts
  packages/create-yoshi-app/__tests__/createApp.test.ts
  packages/create-yoshi-app/__tests__/generateProject.test.js
  packages/create-yoshi-app/__tests__/generateProject.test.ts
  packages/create-yoshi-app/__tests__/getQuestions.spec.ts
  packages/create-yoshi-app/__tests__/verifyRegistry.test.ts
  packages/create-yoshi-app/__tests__/verifyWorkingDirectory.test.ts
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/scripts/cache.js
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/src/TemplateModel.js
  packages/create-yoshi-app/src/TemplateModel.ts
  packages/create-yoshi-app/src/bin/create-yoshi-app.ts
  packages/create-yoshi-app/src/constants.js
  packages/create-yoshi-app/src/constants.ts
  packages/create-yoshi-app/src/createApp.ts
  packages/create-yoshi-app/src/generateProject.js
  packages/create-yoshi-app/src/generateProject.ts
  packages/create-yoshi-app/src/getFilesInDir.ts
  packages/create-yoshi-app/src/getQuestions.ts
  packages/create-yoshi-app/src/getValuesMap.ts
  packages/create-yoshi-app/src/index.js
  packages/create-yoshi-app/src/index.ts
  packages/create-yoshi-app/src/replaceTemplates.ts
  packages/create-yoshi-app/src/runPrompt.ts
  packages/create-yoshi-app/src/templates.ts
  packages/create-yoshi-app/src/utils.ts
  packages/create-yoshi-app/src/verifyDirectoryName.ts
  packages/create-yoshi-app/src/verifyMinimumNodeVersion.ts
  packages/create-yoshi-app/src/verifyRegistry.ts
  packages/create-yoshi-app/src/verifyWorkingDirectory.ts
  packages/create-yoshi-app/tsconfig.json
Labels: PR: Internal :house:

#1504 server templates: use wix-test-env for environment setup
  packages/create-yoshi-app/templates/server/javascript/test/environment.js
  packages/create-yoshi-app/templates/server/javascript/test/it/server.it.js
  packages/create-yoshi-app/templates/server/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/server/typescript/test/environment.ts
  packages/create-yoshi-app/templates/server/typescript/test/it/server.it.ts
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
Labels: PR: Polish :nail_care:

#1616 create-yoshi-app typescript tweaks
  jest.unit.config.js
  packages/create-yoshi-app/__tests__/TemplateModel.test.ts
  packages/create-yoshi-app/__tests__/createApp.test.ts
  packages/create-yoshi-app/__tests__/generateProject.test.ts
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/scripts/dev.js
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/src/TemplateModel.ts
  packages/create-yoshi-app/src/getQuestions.ts
  packages/create-yoshi-app/src/runPrompt.ts
  packages/create-yoshi-app/src/templates.ts
Labels: PR: Polish :nail_care:

#1617 Fix TS importing project's own package.json and causing it to be copied
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/src/bin/create-yoshi-app.ts
  packages/create-yoshi-app/tsconfig.json
Labels: PR: Polish :nail_care:

#1618 Describe why we required the package.json instead of imported
  packages/create-yoshi-app/src/bin/create-yoshi-app.ts
Labels: PR: Chore :construction_worker:

#1614 Fail template generation if node version does not match ours
  __tests__/verifyNvmrc.test.ts
  packages/create-yoshi-app/.nvmrc
  packages/create-yoshi-app/__tests__/__fixtures__/minimal-template/javascript/.nvmrc
  packages/create-yoshi-app/__tests__/verifyNodeVersion.test.ts
  packages/create-yoshi-app/src/bin/create-yoshi-app.ts
  packages/create-yoshi-app/src/constants.ts
  packages/create-yoshi-app/src/index.ts
  packages/create-yoshi-app/src/verifyMinimumNodeVersion.ts
  packages/create-yoshi-app/src/verifyNodeVersion.ts
Labels: PR: Polish :nail_care:

#1620 Fix removal of CYA's shebang
  packages/create-yoshi-app/src/bin/create-yoshi-app.ts
Labels: PR: Bug Fix :bug:

#1625 Remove TS workaround for @types/prompts
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/src/getQuestions.ts
Labels: PR: Internal :house:

#1626 Fix HtmlWebpackPlugin to work inside monorepo
  packages/yoshi/config/webpack.config.js
Labels: PR: New Feature :rocket:, 🏘️ Monorepo

#1631 improving symlinking strategy
  package.json
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/scripts/dev.js
  packages/create-yoshi-app/src/installExternalDependnecies.ts
  scripts/utils/setupProject.js
  scripts/utils/symlinkModules.js
Labels: PR: Internal :house:
