Repository wix/yoshi, pull requests merged in 2019-02, with the labels that each got.

#950 Release website to surge on PR
  .travis.yml
Labels: PR: Internal :house:

#957 Add documentation for the why & how of using a lockfile
  .editorconfig
  docs/guides/managing-dependencies.md
  website/sidebars.json
Labels: PR: Docs :memo:

#960 Update package.json
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#962 Fix terser version as a temporary fix
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#963 change Yoshi's config schema to support setting `separateCss: true`
  packages/yoshi-config/schema/yoshi-config-schema.js
Labels: PR: Polish :nail_care:

#961 Don't minimize server bundle
  packages/yoshi/config/webpack.config.js
Labels: PR: Polish :nail_care:

#958 Update stylable runtime config
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
Labels: PR: New Feature :rocket:

#966 Unfix terser version
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#965 fail early if Yoshi is being run with an old Node version
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/src/constants.js
  packages/create-yoshi-app/src/createApp.js
  packages/yoshi-helpers/__tests__/verifyMinimumNodeVersion.spec.js
  packages/yoshi-helpers/package.json
  packages/yoshi-helpers/verifyMinimumNodeVersion.js
  packages/yoshi/bin/yoshi.js
  packages/yoshi/src/constants.js
Labels: PR: Polish :nail_care:

#970 fix clash between test infra's .npmrc and .npmrc generated by the templates
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/src/utils.js
Labels: PR: Internal :house:

#975 Lock AJV version due to a bug
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#976 Lock yoshi-config ajv
  packages/yoshi-config/package.json
Labels: PR: Bug Fix :bug:

#969 Fix checking if file is exist.
  packages/yoshi-helpers/utils.js
Labels: PR: Bug Fix :bug:

#983 remove component library generators from list
  packages/create-yoshi-app/src/projects.js
Labels: PR: Internal :house:

#984 Update biz mgr template to address configuration changes
  packages/create-yoshi-app/templates/business-manager-module-typescript/templates/module_{%PROJECT_NAME%}.json.erb
  packages/create-yoshi-app/templates/business-manager-module-typescript/test/environment.ts
  packages/create-yoshi-app/templates/business-manager-module/templates/module_{%PROJECT_NAME%}.json.erb
  packages/create-yoshi-app/templates/business-manager-module/test/environment.js
Labels: PR: Bug Fix :bug:

#973 Fix watch jest mode - do not watch 'dist' and 'target' folders
  packages/jest-yoshi-preset/jest-preset.js
Labels: PR: Bug Fix :bug:

#990 Remove mocha-teamcity-reporter
  packages/yoshi-helpers/utils.js
  packages/yoshi/test/e2e.spec.js
  packages/yoshi/test/mocha.opts
  packages/yoshi/test/test.spec.js
Labels: PR: Bug Fix :bug:

#978 Do not pack dist and test in yoshi main package
  packages/create-yoshi-app/.npmignore
  packages/eslint-config-yoshi-base/.npmignore
  packages/tslint-config-yoshi-base/.npmignore
  packages/yoshi-helpers/.npmignore
  packages/yoshi/package.json
Labels: PR: Internal :house:

#977 Remove ajv from yoshi and upgrade the version
  packages/yoshi-config/package.json
  packages/yoshi/package.json
Labels: PR: Polish :nail_care:

#994 Remove mocha-teamcity-reporter
  packages/yoshi/src/utils.js
  packages/yoshi/test/e2e.spec.js
  packages/yoshi/test/test.spec.js
Labels: PR: Bug Fix :bug:

#995 Upgrade wnpm-ci
  package.json
Labels: PR: Internal :house:

#993 tslint-config-yoshi > Update README.md
  packages/tslint-config-yoshi/README.md
Labels: PR: Docs :memo:

#996 upgrade wnpm-ci
  packages/yoshi/package.json
Labels: PR: Internal :house:

#998 mocha-teamcity-reporter to ^2
  package.json
Labels: PR: Bug Fix :bug:

#999 upgrade mocha-teamcity-reporter to v2
  packages/yoshi/package.json
  packages/yoshi/src/utils.js
  packages/yoshi/test/e2e.spec.js
  packages/yoshi/test/test.spec.js
Labels: PR: Bug Fix :bug:

#1001 fix protractor with teamcity reporter test
  test/e2e.spec.js
Labels: PR: Bug Fix :bug:

#1000 Upgrade mocha-teamcity-reporter to v2
  packages/yoshi-helpers/utils.js
  packages/yoshi/package.json
  packages/yoshi/test/e2e.spec.js
  packages/yoshi/test/mocha.opts
  packages/yoshi/test/test.spec.js
Labels: PR: Bug Fix :bug:

#1004 Fix mocha teamcity reporter
  packages/yoshi/test/e2e.spec.js
Labels: PR: Internal :house:

#1008 upgrade generators to node 10
  .nvmrc
  packages/create-yoshi-app/templates/business-manager-module-typescript/.nvmrc
  packages/create-yoshi-app/templates/business-manager-module-typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/business-manager-module-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/.nvmrc
  packages/create-yoshi-app/templates/client-typescript/.nvmrc
  packages/create-yoshi-app/templates/client/.nvmrc
  packages/create-yoshi-app/templates/fullstack-typescript/.nvmrc
  packages/create-yoshi-app/templates/fullstack/.nvmrc
  packages/create-yoshi-app/templates/server-typescript/.nvmrc
  packages/create-yoshi-app/templates/server/.nvmrc
  packages/yoshi/test/e2e.spec.js
  packages/yoshi/test/jasmine.spec.js
  packages/yoshi/test/test.spec.js
Labels: PR: Internal :house:

#1011 Fix server/business-manager generators for version 4
  packages/create-yoshi-app/templates/business-manager-module-typescript/src/components/__mocks__/i18n.ts
  packages/create-yoshi-app/templates/business-manager-module-typescript/tsconfig.json
  packages/create-yoshi-app/templates/business-manager-module/src/components/__mocks__/i18n.js
  packages/create-yoshi-app/templates/client-typescript/tsconfig.json
  packages/create-yoshi-app/templates/fullstack-typescript/tsconfig.json
  packages/create-yoshi-app/templates/server-typescript/tsconfig.json
  packages/create-yoshi-app/templates/server-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/server/{%packagejson%}
  packages/jest-yoshi-preset/package.json
  packages/yoshi/config/webpack.config.js
Labels: PR: Internal :house:

#1015 Use ^4.1.0-alpha.1 instead of ^4.0.0 as it does not exist yet
  packages/create-yoshi-app/templates/business-manager-module-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/{%packagejson%}
  packages/create-yoshi-app/templates/client-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/{%packagejson%}
Labels: PR: Polish :nail_care:

#1010 Change 'appflow' FT
  packages/yoshi-config/index.js
  packages/yoshi-config/schema/yoshi-config-schema.js
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/config/webpack.config.js
  test/projects/kitchensink-javascript/package.json
  test/projects/kitchensink-typescript/package.json
Labels: PR: Polish :nail_care:

#992 Improve app flow: Show server errors in the browser and refresh the browser on server changes
  package.json
  packages/yoshi/config/hot.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
  packages/yoshi/src/commands/start-app.js
  packages/yoshi/src/server-process.js
  packages/yoshi/src/webpack-utils.js
  test/projects/kitchensink-javascript/integration/hmr.test.js
  test/projects/kitchensink-javascript/package.json
  test/projects/kitchensink-javascript/src/index.ejs
  test/projects/kitchensink-javascript/src/other.ejs
  test/projects/kitchensink-javascript/src/server.js
  test/projects/kitchensink-typescript/integration/hmr.test.js
  test/projects/kitchensink-typescript/package.json
  test/projects/kitchensink-typescript/src/index.ejs
  test/projects/kitchensink-typescript/src/other.ejs
  test/projects/kitchensink-typescript/src/server.tsx
  test/scripts.js
  test/utils.js
Labels: PR: New Feature :rocket:

#1017 Generate correct public path on local build
  packages/yoshi/config/webpack.config.js
  packages/yoshi/test/webpack-config.spec.js
Labels: PR: Bug Fix :bug:

#1016 properly log port when waiting for server to start
  packages/yoshi/src/tasks/app-server/index.js
Labels: PR: Bug Fix :bug:

#1035 configure npm to not automatically add `^` to installed dependency
  packages/yoshi/.npmrc
Labels: PR: Internal :house:

#1037 freeze direct deps in `yoshi-*` packages
  packages/yoshi-angular-dependencies/.npmrc
  packages/yoshi-angular-dependencies/package.json
  packages/yoshi-config/.npmrc
  packages/yoshi-config/package.json
  packages/yoshi-helpers/.npmrc
  packages/yoshi-helpers/package.json
  packages/yoshi-style-dependencies/.npmrc
  packages/yoshi-style-dependencies/package.json
Labels: PR: Internal :house:

#1046 do not show name of files without stylelint errors
  packages/yoshi/src/tasks/stylelint.js
  packages/yoshi/test/lint.spec.js
Labels: PR: Bug Fix :bug:
