Repository wix/yoshi, pull requests merged in 2019-07, with the labels that each got.

#1423 Install published version on templates tests rather than latest
  packages/create-yoshi-app/src/utils.js
Labels: PR: Internal :house:

#1422 make lint-staged to fail on warnings
  package.json
Labels: PR: Internal :house:

#1421 Add Wallaby support with "__tests__" folder (#1339)
  packages/yoshi/config/wallaby-common.js
Labels: PR: Bug Fix :bug:

#1395 Rtl css
  packages/yoshi-config/src/config.d.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-config/src/validConfig.ts
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
Labels: PR: New Feature :rocket:

#1430 Update docs about project types (add OOI app)
  docs/getting-started/project-types.md
Labels: PR: Docs :memo:

#1428 Remove "yoshi-helpers" dependency to improve performance
  packages/create-yoshi-app/bin/create-yoshi-app.js
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/src/verifyMinimumNodeVersion.js
Labels: PR: Polish :nail_care:

#1435 Update cli.md
  website/versioned_docs/version-4.x/api/cli.md
Labels: PR: Docs :memo:

#1434 Fix yoshi-config validation/schema
  packages/yoshi-config/loadConfig.d.ts
  packages/yoshi-config/package.json
  packages/yoshi-config/src/config.d.ts
  packages/yoshi-config/src/jest/index.ts
  packages/yoshi-config/src/jest/types.d.ts
  packages/yoshi-config/src/jest/validConfig.ts
  packages/yoshi-config/src/loadConfig.ts
  packages/yoshi-config/src/validConfig.ts
Labels: PR: Bug Fix :bug:

#1431 support '--https' cli option in 'start' command
  docs/api/cli.md
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/src/commands/start.js
  packages/yoshi/test/start.spec.js
Labels: PR: Bug Fix :bug:

#1425 Create version-3.md
  docs/migration/version-3.md
  website/sidebars.json
Labels: PR: Docs :memo:

#1436 Fix server not getting process.env.NODE_ENV and others
  packages/yoshi/config/webpack.config.js
Labels: PR: Bug Fix :bug:

#1437 Adjust wallaby to version 4 changes
  packages/yoshi/config/wallaby-mocha.js
Labels: PR: Bug Fix :bug:

#1438 Build packages in travis before running scripts
  .travis.yml
Labels: PR: Internal :house:

#1439 fix wallaby mocha config
  packages/yoshi/config/wallaby-mocha.js
Labels: PR: Bug Fix :bug:

#1433 print full path of dependencies with different major version
  packages/yoshi/package.json
  packages/yoshi/src/verify-dependencies.js
Labels: PR: Bug Fix :bug:

#1441 Adjust travis config to recent split in test commands
  .travis.yml
Labels: PR: Internal :house:

#1449 Fix wallaby.ts file to not include types
  packages/yoshi/config/wallaby-mocha-ts.ts
  tsconfig.json
Labels: PR: Bug Fix :bug:

#1446 Typos: fix typos throughout the project
  CHANGELOG.md
  CONTRIBUTING.md
  MONOREPO_SUPPORT.md
  docs/api/cli.md
  docs/api/configuration.md
  docs/guides/debugging.md
  docs/guides/enzyme-support.md
  docs/guides/export-es-modules.md
  docs/guides/hmr.md
  docs/guides/jest-setup.md
  docs/guides/split-chunks.md
  docs/migration/version-4.md
  packages/babel-preset-yoshi/index.js
  packages/bootstrap-hot-loader/hot.dev.js
  packages/bootstrap-hot-loader/package.json
  packages/create-yoshi-app/__tests__/TemplateModel.spec.js
  packages/create-yoshi-app/src/getFilesInDir.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/__tests__/e2e-ssr/verify-ssr.ssr.js
  packages/jest-environment-yoshi-bootstrap/index.js
  packages/jest-environment-yoshi-puppeteer/globalSetup.js
  packages/yoshi-template-intro/README.md
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/config/wallaby-common.js
  packages/yoshi/config/wallaby-jest.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/src/commands/start-app.js
  packages/yoshi/src/commands/test.js
  packages/yoshi/src/tasks/cdn/utils.js
  packages/yoshi/src/tasks/dep-check/index.js
  packages/yoshi/src/tasks/petri-specs/README.md
  packages/yoshi/src/webpack-plugins/environment-mark-plugin.js
  packages/yoshi/test/build.spec.js
  packages/yoshi/test/e2e.spec.js
  packages/yoshi/test/lint.spec.js
  packages/yoshi/test/start.spec.js
  packages/yoshi/test/test.spec.js
  packages/yoshi/test/webpack-config.spec.js
  scripts/customPublish.js
  test/projects/kitchensink-javascript/integration/output.test.js
  test/projects/kitchensink-typescript/integration/output.test.js
  website/blog/2018-03-14-semantic-versioning.md
  website/versioned_docs/version-3.x/api/cli.md
  website/versioned_docs/version-3.x/api/configuration.md
  website/versioned_docs/version-3.x/guides/debugging.md
  website/versioned_docs/version-3.x/guides/enzyme-support.md
  website/versioned_docs/version-3.x/guides/export-es-modules.md
  website/versioned_docs/version-3.x/guides/hmr.md
  website/versioned_docs/version-3.x/guides/jest-setup.md
  website/versioned_docs/version-3.x/guides/split-chunks.md
  website/versioned_docs/version-4.x/api/cli.md
  website/versioned_docs/version-4.x/api/configuration.md
  website/versioned_docs/version-4.x/guides/export-es-modules.md
  website/versioned_docs/version-4.x/guides/jest-setup.md
  website/versioned_docs/version-4.x/guides/split-chunks.md
  website/versioned_docs/version-4.x/migration/version-4.md
Labels: PR: Docs :memo:

#1452 Update react version in the templates to 16.8.6
  packages/create-yoshi-app/templates/client/javascript/src/index.vm
  packages/create-yoshi-app/templates/client/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/src/index.vm
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/javascript/src/index.ejs
  packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/typescript/src/index.ejs
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
Labels: PR: New Feature :rocket:

#1459 update out-of-iframe typescript template: match widget css with javascript template
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/Widget.st.css
Labels: PR: Bug Fix :bug:

#1457 When using jest, do not ignore the transformation of svg assets from node_modules
  packages/jest-yoshi-preset/jest-preset.js
  packages/yoshi/config/jest.config.js
Labels: PR: Bug Fix :bug:

#1460 Fix links to out-of-iframe docs on their templates readme
  packages/create-yoshi-app/templates/out-of-iframe/javascript/README.md
  packages/create-yoshi-app/templates/out-of-iframe/typescript/README.md
Labels: PR: Docs :memo:

#1235 Add an option to add a custom protractor config
  packages/yoshi/config/protractor.conf.js
  packages/yoshi/test/e2e.spec.js
Labels: PR: New Feature :rocket:

#1458 remove webpack lock from yoshi
  packages/yoshi/package.json
  packages/yoshi/test/build.spec.js
  packages/yoshi/test/loaders.spec.js
  renovate.json
Labels: PR: New Feature :rocket:

#1463 Migrate `yoshi-helpers` to TypeScript
  packages/yoshi-config/index.d.ts
  packages/yoshi-config/src/config.ts
  packages/yoshi-config/src/jest/config.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-helpers/bootstrap-utils.d.ts
  packages/yoshi-helpers/bootstrap-utils.js
  packages/yoshi-helpers/certificates/server.cert
  packages/yoshi-helpers/certificates/server.key
  packages/yoshi-helpers/constants.d.ts
  packages/yoshi-helpers/constants.js
  packages/yoshi-helpers/package.json
  packages/yoshi-helpers/queries.d.ts
  packages/yoshi-helpers/queries.js
  packages/yoshi-helpers/require-hooks.d.ts
  packages/yoshi-helpers/require-hooks.js
  packages/yoshi-helpers/require-hooks/index.js
  packages/yoshi-helpers/rewrite-forward-proxy.d.ts
  packages/yoshi-helpers/rewrite-forward-proxy.js
  packages/yoshi-helpers/src/bootstrap-utils.ts
  packages/yoshi-helpers/src/constants.ts
  packages/yoshi-helpers/src/queries.ts
  packages/yoshi-helpers/src/require-hooks/babel-register.ts
  packages/yoshi-helpers/src/require-hooks/index.ts
  packages/yoshi-helpers/src/require-hooks/ts-node-register.ts
  packages/yoshi-helpers/src/rewrite-forward-proxy.ts
  packages/yoshi-helpers/src/utils.ts
  packages/yoshi-helpers/src/verifyMinimumNodeVersion.ts
  packages/yoshi-helpers/tsconfig.json
  packages/yoshi-helpers/utils.d.ts
  packages/yoshi-helpers/utils.js
  packages/yoshi-helpers/verifyMinimumNodeVersion.d.ts
  packages/yoshi-helpers/verifyMinimumNodeVersion.js
Labels: PR: Internal :house:

#1474 Bump 'wnpm-ci' to v8
  packages/yoshi/package.json
Labels: PR: Internal :house:

#1475 Add user defined `process.env.APP_CONF_DIR`
  packages/yoshi-helpers/src/bootstrap-utils.ts
  packages/yoshi/test/start.spec.js
Labels: PR: Bug Fix :bug:

#1471 Combine Jest preset and related packages into 1 package
  packages/jest-environment-yoshi-bootstrap/package.json
  packages/jest-environment-yoshi-puppeteer/package.json
  packages/jest-yoshi-preset/jest-environment-yoshi-bootstrap/constants.js
  packages/jest-yoshi-preset/jest-environment-yoshi-bootstrap/environment-setup.js
  packages/jest-yoshi-preset/jest-environment-yoshi-bootstrap/index.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/cdnProxy.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/constants.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/globalSetup.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/globalTeardown.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/index.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/utils.js
  packages/jest-yoshi-preset/jest-preset.js
  packages/jest-yoshi-preset/package.json
  packages/yoshi/src/env-info.js
Labels: PR: Internal :house:

#1470 added jest preset types pointer
  packages/jest-yoshi-preset/package.json
Labels: PR: Polish :nail_care:

#1472 Remove redundant `wait-for-selector` from generated code
  packages/create-yoshi-app/templates/client/javascript/__tests__/simple.e2e.js
  packages/create-yoshi-app/templates/client/typescript/__tests__/simple.e2e.ts
  packages/create-yoshi-app/templates/fullstack/javascript/__tests__/browser.e2e.js
  packages/create-yoshi-app/templates/fullstack/typescript/__tests__/browser.e2e.ts
Labels: PR: Chore :construction_worker:

#1447 Migrate `bootstrap-hot-loader` to TypeScript
  packages/bootstrap-hot-loader/bootstrap-hot-loader.d.ts
  packages/bootstrap-hot-loader/hot.prod.js
  packages/bootstrap-hot-loader/index.js
  packages/bootstrap-hot-loader/package.json
  packages/bootstrap-hot-loader/src/hot.dev.ts
  packages/bootstrap-hot-loader/src/hot.prod.ts
  packages/bootstrap-hot-loader/src/types.ts
  packages/bootstrap-hot-loader/tsconfig.json
Labels: PR: Internal :house:
