Repository wix/yoshi, pull requests merged in 2019-04, with the labels that each got.

#1191 Add sensible defaults for webpack-dev-server's allowedHosts
  packages/yoshi/src/webpack-utils.js
Labels: PR: Polish :nail_care:

#1190 Add ability to use an answers json file instead of prompt
  packages/create-yoshi-app/__tests__/createApp.spec.js
  packages/create-yoshi-app/bin/create-yoshi-app.js
  packages/create-yoshi-app/src/Answers.js
  packages/create-yoshi-app/src/createApp.js
Labels: PR: New Feature :rocket:

#967 create-yoshi-app: add sentry and fedops to client and fullstack apps
  packages/create-yoshi-app/templates/client-typescript/fedops.json
  packages/create-yoshi-app/templates/client-typescript/src/client.tsx
  packages/create-yoshi-app/templates/client-typescript/src/index.vm
  packages/create-yoshi-app/templates/client-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/fedops.json
  packages/create-yoshi-app/templates/client/src/client.js
  packages/create-yoshi-app/templates/client/src/index.vm
  packages/create-yoshi-app/templates/client/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack-typescript/fedops.json
  packages/create-yoshi-app/templates/fullstack-typescript/src/client.tsx
  packages/create-yoshi-app/templates/fullstack-typescript/src/index.ejs
  packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/fedops.json
  packages/create-yoshi-app/templates/fullstack/src/client.js
  packages/create-yoshi-app/templates/fullstack/src/index.ejs
  packages/create-yoshi-app/templates/fullstack/{%packagejson%}
Labels: PR: New Feature :rocket:

#1160 Add to our jest preset a graphql transform
  packages/jest-yoshi-preset/jest-preset.js
  packages/jest-yoshi-preset/package.json
  test/projects/kitchensink-javascript/src/components/features/graphql-inclusion.spec.js
  test/projects/kitchensink-typescript/src/components/features/graphql-inclusion.spec.tsx
Labels: PR: New Feature :rocket:

#1198 Remove an unused and undocumented way to disable thread optimization in Typescript
  packages/yoshi/config/webpack.config.js
  packages/yoshi/test/build.spec.js
Labels: PR: Internal :house:

#1205 Fix failing integration tests (Babel)
  packages/yoshi/test/build.spec.js
Labels: PR: Internal :house:

#1193 Upgrade JSDOM to v14
  packages/jest-yoshi-preset/constants.js
  packages/jest-yoshi-preset/jest-preset.js
  packages/jest-yoshi-preset/package.json
Labels: PR: New Feature :rocket:

#1203 Wrong displayName in jest wallaby
  packages/yoshi/config/wallaby-jest.js
Labels: PR: Bug Fix :bug:

#1090 Html Webpack Plugin MVP
  packages/yoshi-config/loadConfig.js
  packages/yoshi-helpers/utils.js
  packages/yoshi/config/html-polyfill-plugin.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
  packages/yoshi/test/build.spec.js
Labels: PR: New Feature :rocket:

#1194 Add versioned documentation 🎉🐉
  CONTRIBUTING.md
  package.json
  website/pages/en/index.js
  website/pages/en/versions.js
  website/versioned_docs/version-3.x/api/cli.md
  website/versioned_docs/version-3.x/api/configuration.md
  website/versioned_docs/version-3.x/getting-started/create-app.md
  website/versioned_docs/version-3.x/getting-started/project-types.md
  website/versioned_docs/version-3.x/getting-started/usage.md
  website/versioned_docs/version-3.x/guides/ab-translate.md
  website/versioned_docs/version-3.x/guides/assets.md
  website/versioned_docs/version-3.x/guides/babel-setup.md
  website/versioned_docs/version-3.x/guides/bundle-analyze.md
  website/versioned_docs/version-3.x/guides/debugging.md
  website/versioned_docs/version-3.x/guides/disable-css-modules.md
  website/versioned_docs/version-3.x/guides/enzyme-support.md
  website/versioned_docs/version-3.x/guides/export-es-modules.md
  website/versioned_docs/version-3.x/guides/hmr.md
  website/versioned_docs/version-3.x/guides/jest-setup.md
  website/versioned_docs/version-3.x/guides/managing-dependencies.md
  website/versioned_docs/version-3.x/guides/momentjs-optimization.md
  website/versioned_docs/version-3.x/guides/split-chunks.md
  website/versioned_docs/version-3.x/guides/svg.md
  website/versioned_docs/version-4.x/api/cli.md
  website/versioned_docs/version-4.x/api/configuration.md
  website/versioned_docs/version-4.x/getting-started/create-app.md
  website/versioned_docs/version-4.x/getting-started/project-types.md
  website/versioned_docs/version-4.x/getting-started/usage.md
  website/versioned_docs/version-4.x/guides/ab-translate.md
  website/versioned_docs/version-4.x/guides/app-flow.md
  website/versioned_docs/version-4.x/guides/assets.md
  website/versioned_docs/version-4.x/guides/babel-setup.md
  website/versioned_docs/version-4.x/guides/bundle-analyze.md
  website/versioned_docs/version-4.x/guides/debugging.md
  website/versioned_docs/version-4.x/guides/disable-css-modules.md
  website/versioned_docs/version-4.x/guides/enzyme-support.md
  website/versioned_docs/version-4.x/guides/export-es-modules.md
  website/versioned_docs/version-4.x/guides/hmr.md
  website/versioned_docs/version-4.x/guides/jest-setup.md
  website/versioned_docs/version-4.x/guides/managing-dependencies.md
  website/versioned_docs/version-4.x/guides/momentjs-optimization.md
  website/versioned_docs/version-4.x/guides/split-chunks.md
  website/versioned_docs/version-4.x/guides/stylelint-setup.md
  website/versioned_docs/version-4.x/guides/svg.md
  website/versioned_docs/version-4.x/migration/version-4.md
  website/versioned_sidebars/version-3.x-sidebars.json
  website/versioned_sidebars/version-4.x-sidebars.json
  website/versions.json
Labels: PR: Docs :memo:

#1213 Wrong MATCH_ENV in VS Code settings
  packages/create-yoshi-app/templates/client/javascript/.vscode/launch.json
  packages/create-yoshi-app/templates/client/typescript/.vscode/launch.json
  packages/create-yoshi-app/templates/fullstack/javascript/.vscode/launch.json
  packages/create-yoshi-app/templates/fullstack/typescript/.vscode/launch.json
Labels: PR: Bug Fix :bug:

#1216 Webpack HTML plugin fixes
  packages/yoshi-config/schema/yoshi-config-schema.js
  packages/yoshi/config/webpack.config.js
Labels: PR: Bug Fix :bug:

#1212 Adjust internal `createVersion` script to generate versioned docs
  scripts/createVersion.js
Labels: PR: Internal :house:

#1222 separate template tests
  package.json
  packages/create-yoshi-app/package.json
Labels: PR: Internal :house:, 🛠 Infrastructure

#1225 Remove universal template from project types doc
  docs/getting-started/project-types.md
Labels: PR: Docs :memo:

#1223 Node library template
  package.json
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/src/getQuestions.js
  packages/create-yoshi-app/src/index.js
  packages/create-yoshi-app/src/templates.js
  packages/create-yoshi-app/templates.js
  packages/create-yoshi-app/templates/library/javascript/.editorconfig
  packages/create-yoshi-app/templates/library/javascript/.nvmrc
  packages/create-yoshi-app/templates/library/javascript/.vscode/extensions.json
  packages/create-yoshi-app/templates/library/javascript/.vscode/launch.json
  packages/create-yoshi-app/templates/library/javascript/.vscode/settings.json
  packages/create-yoshi-app/templates/library/javascript/pom.xml
  packages/create-yoshi-app/templates/library/javascript/src/counter.js
  packages/create-yoshi-app/templates/library/javascript/src/index.js
  packages/create-yoshi-app/templates/library/javascript/test/counter.spec.js
  packages/create-yoshi-app/templates/library/javascript/wallaby.js
  packages/create-yoshi-app/templates/library/javascript/{%gitignore%}
  packages/create-yoshi-app/templates/library/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/library/typescript/.editorconfig
  packages/create-yoshi-app/templates/library/typescript/.nvmrc
  packages/create-yoshi-app/templates/library/typescript/.vscode/extensions.json
  packages/create-yoshi-app/templates/library/typescript/.vscode/launch.json
  packages/create-yoshi-app/templates/library/typescript/.vscode/settings.json
  packages/create-yoshi-app/templates/library/typescript/pom.xml
  packages/create-yoshi-app/templates/library/typescript/src/counter.ts
  packages/create-yoshi-app/templates/library/typescript/src/index.ts
  packages/create-yoshi-app/templates/library/typescript/test/counter.spec.ts
  packages/create-yoshi-app/templates/library/typescript/tsconfig.json
  packages/create-yoshi-app/templates/library/typescript/tslint.json
  packages/create-yoshi-app/templates/library/typescript/wallaby.js
  packages/create-yoshi-app/templates/library/typescript/{%gitignore%}
  packages/create-yoshi-app/templates/library/typescript/{%packagejson%}
Labels: PR: New Feature :rocket:

#1226 Provide `yoshi-runtime` by default
  packages/yoshi-angular-dependencies/package.json
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#1230 simplify ooi javascript src directory file structure
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/ExampleWidget/ExampleWidget.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/ExampleWidgetRoot/ExampleWidgetRoot.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/App.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/App.spec.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/App.st.css
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/appController.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/appController.spec.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/settingsPanel/SettingsPanel.global.scss
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/settingsPanel/SettingsPanel.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/settingsPanel/SettingsPanel.scss
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/settingsPanel/SettingsPanel.spec.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/config/constants.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/editorApp.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/editorExampleWidget.entry.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/platform/viewerScript.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/settingsExampleWidget.entry.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/settingsPanel.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/templates/editorApp.vm
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/templates/settingsPanel.vm
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerApp/viewerScript.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerApp/viewerScript.spec.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerApp/viewerWidget.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerExampleWidget.entry.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerScript.entry.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/test/e2e/editorApp.spec.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/test/fake-server.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/test/wix-private.mock.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
Labels: PR: Polish :nail_care:

#1245 Make puppeteer ignore ssl errors if user run with flag ssl:true
  packages/jest-environment-yoshi-puppeteer/globalSetup.js
Labels: PR: Bug Fix :bug:

#1249 use major version in nvmrc, and not a specific one
  packages/create-yoshi-app/templates/out-of-iframe/javascript/.nvmrc
  packages/create-yoshi-app/templates/out-of-iframe/typescript/.nvmrc
Labels: PR: Polish :nail_care:

#1200 Make deploy "website" to surge.sh conditional
  .travis.yml
  website/pages/en/index.js
Labels: PR: New Feature :rocket:

#1244 add server bundle on build logs
  packages/yoshi/src/commands/build-app.js
Labels: PR: Bug Fix :bug:

#1252 Remove server `ts-loader` config
  packages/yoshi/config/webpack.config.js
Labels: PR: Bug Fix :bug:

#1236 Update library generator to Yoshi 4
  jest.unit.config.js
  packages/create-yoshi-app/templates/library/javascript/__tests__/counter.spec.js
  packages/create-yoshi-app/templates/library/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/library/typescript/__tests__/counter.spec.ts
  packages/create-yoshi-app/templates/library/typescript/tsconfig.json
  packages/create-yoshi-app/templates/library/typescript/{%packagejson%}
Labels: PR: Chore :construction_worker:

#1254 Revert "Add missing dev dependency to biz-mgr templates"
  packages/create-yoshi-app/templates/business-manager-module/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
Labels: PR: Chore :construction_worker:

#1253 Remove HMR from production bundle
  packages/yoshi/config/webpack.config.js
  packages/yoshi/config/webpack.config.specs.js
  packages/yoshi/config/webpack.config.storybook.js
  packages/yoshi/src/commands/build-app.js
Labels: PR: Bug Fix :bug:

#1260 yoshi: Enable `--source-map` option in app flow build
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/src/commands/build-app.js
Labels: PR: New Feature :rocket:
