Repository wix/yoshi, pull requests merged in 2019-08, with the labels that each got.

#1467 Jest yoshi preset overrides
  docs/guides/jest-setup.md
  packages/jest-yoshi-preset/jest-preset.js
  packages/jest-yoshi-preset/package.json
  packages/yoshi-config/src/jest/config.ts
  packages/yoshi-config/src/jest/index.ts
  packages/yoshi-config/src/jest/validConfig.ts
  test/projects/kitchensink-javascript/__tests__/simple.e2e.js
  test/projects/kitchensink-javascript/jest-yoshi.config.js
  test/projects/kitchensink-javascript/src/components/features/jest-preset-overrides.spec.js
Labels: PR: New Feature :rocket:

#1478 Add types to jest config
  packages/yoshi-config/package.json
  packages/yoshi-config/src/jest/config.ts
  packages/yoshi-config/src/jest/validConfig.ts
Labels: PR: Internal :house:

#1480 Increase template tests timeout from 30s to 60s
  packages/create-yoshi-app/scripts/runE2E.js
Labels: PR: Internal :house:

#1481 Move `@jest/types` to be devDependency
  packages/yoshi-config/package.json
Labels: PR: Internal :house:

#1479 Optimize eslint and babel configs for server and library
  packages/create-yoshi-app/templates/library/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/server/javascript/{%packagejson%}
Labels: PR: Polish :nail_care:

#1484 Update unit test files pattern to `*.test.js`
  jest.unit.config.js
  packages/create-yoshi-app/__tests__/TemplateModel.test.js
  packages/create-yoshi-app/__tests__/__snapshots__/create-yoshi-app.test.js.snap
  packages/create-yoshi-app/__tests__/__snapshots__/generateProject.test.js.snap
  packages/create-yoshi-app/__tests__/create-yoshi-app.test.js
  packages/create-yoshi-app/__tests__/createApp.test.js
  packages/create-yoshi-app/__tests__/generateProject.test.js
  packages/create-yoshi-app/__tests__/verifyRegistry.test.js
  packages/create-yoshi-app/__tests__/verifyWorkingDirectory.test.js
  packages/eslint-config-yoshi/__tests__/eslint-config-yoshi.test.js
  packages/tslint-config-yoshi/__tests__/tslint-config-yoshi.test.js
  packages/yoshi-helpers/__tests__/utils.test.js
  packages/yoshi-helpers/__tests__/verifyMinimumNodeVersion.test.js
Labels: PR: Internal :house:

#1482 Create-yoshi-app: Better email input experience
  packages/create-yoshi-app/__tests__/getQuestions.spec.js
  packages/create-yoshi-app/src/getQuestions.js
Labels: PR: New Feature :rocket:

#1488 Add @yavorsky to CODEOWNERS
  CODEOWNERS
Labels: PR: Chore :construction_worker:

#1500 support eslint for typescript
  packages/yoshi-helpers/src/queries.ts
  packages/yoshi/src/commands/lint.js
  packages/yoshi/test/lint.spec.js
Labels: PR: New Feature :rocket:

#1505 fix typo in ooi readme
  packages/create-yoshi-app/templates/out-of-iframe/javascript/README.md
  packages/create-yoshi-app/templates/out-of-iframe/typescript/README.md
Labels: PR: Docs :memo:

#1515 Adds deviantart.lan to allowedhosts for hmr on that project
  packages/yoshi/src/webpack-utils.js
Labels: PR: New Feature :rocket:

#1516 Fix TypeScript version to ~3.5
  package.json
Labels: PR: Internal :house:

#1513 transpile development bundle to last chrome version
  packages/babel-preset-yoshi/index.js
Labels: PR: Polish :nail_care:
