Repository wix/yoshi, pull requests merged in 2019-11, with the labels that each got.

#1635 Use yarn
  .gitignore
  CONTRIBUTING.md
  lerna.json
  package.json
  packages/create-yoshi-app/README.md
  yarn.lock
Labels: PR: Internal :house:

#1644 Revert "Use yarn (#1635)"
  .gitignore
  CONTRIBUTING.md
  lerna.json
  package.json
  packages/create-yoshi-app/README.md
  yarn.lock
Labels: PR: Internal :house:

#1646 Improve wix private mock
  .eslintignore
  packages/create-yoshi-app/templates/out-of-iframe/javascript/dev/wix-private.mock.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/dev/wix-private.mock.js
Labels: PR: Bug Fix :bug:

#1641 Page close error level
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/index.js
Labels: PR: Bug Fix :bug:

#1654 prettier version update
  package.json
  packages/yoshi-server-react/src/hooks.ts
  packages/yoshi/test/start.spec.js
  packages/yoshi/test/webpack-config.spec.js
Labels: PR: Internal :house:

#1650 support importing web workers
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
  packages/yoshi/types.d.ts
  test/projects/kitchensink-javascript/integration/loaders.test.js
  test/projects/kitchensink-javascript/src/components/features/web-worker-chunk-container.js
  test/projects/kitchensink-javascript/src/components/features/web-worker-chunk-entry.inline.worker.js
  test/projects/kitchensink-typescript/integration/loaders.test.js
  test/projects/kitchensink-typescript/src/components/features/web-worker-chunk-container.tsx
  test/projects/kitchensink-typescript/src/components/features/web-worker-chunk-entry.inline.worker.ts
Labels: PR: New Feature :rocket:

#1657 support browser env var
  package.json
  packages/yoshi/config/webpack.config.js
  test/projects/kitchensink-javascript/integration/env-vars.test.js
  test/projects/kitchensink-javascript/src/components/features/env-vars.js
  test/projects/kitchensink-javascript/src/server.js
  test/projects/kitchensink-typescript/integration/env-vars.test.js
  test/projects/kitchensink-typescript/src/components/features/env-vars.tsx
  test/projects/kitchensink-typescript/src/server.tsx
  test/utils.js
Labels: PR: New Feature :rocket:

#1544 Update i18n for OOI templates
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/Widget/Widget.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/Widget/appController.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/Widget/appController.spec.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/config/i18n.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerApp/viewerScript.spec.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/Widget.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/appController.spec.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/appController.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/config/i18n.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/viewerApp/viewerScript.spec.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
Labels: PR: Bug Fix :bug:

#1664 Use latest stylable@1
  packages/yoshi-common/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#1665 Take Dev Server/HMR configuration values per app over rootConfig
  packages/yoshi-flow-monorepo/src/scripts/start.ts
Labels: PR: Bug Fix :bug:

#1667 Fix `cssModules` config not having any effect
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1666 Whitelist external monorepo packages in node bundle
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/scripts/start.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:, 🏘️ Monorepo

#1668 move types to dev dependencies
  packages/yoshi-common/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-server-tools/package.json
Labels: PR: Bug Fix :bug:

#1669 Write manifest file to correct app directory in monorepos
  packages/yoshi-common/src/write-manifest.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
Labels: PR: Bug Fix :bug:, 🏘️ Monorepo

#1670 Don't crash if `--verbose` is passed to app/monorepo
  packages/yoshi-flow-app/src/bin/yoshi-app.ts
  packages/yoshi-flow-monorepo/src/bin/yoshi-monorepo.ts
Labels: PR: Bug Fix :bug:

#1674 server templates: fix index-dev.js
  packages/create-yoshi-app/templates/server/javascript/index-dev.js
  packages/create-yoshi-app/templates/server/typescript/index-dev.js
Labels: PR: Bug Fix :bug:

#1677 Transpile typescript to latest browsers only on local development
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1679 Transpile TypeScript according to `--production`
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1676 pass tpaStyle and enhancedTpaStyle config options to the webpack config
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1680 Pass missing configurations to webpack config
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-legacy/config/webpack.config.js
Labels: PR: Bug Fix :bug:

#1681 `manifest.json` for local dev
  packages/yoshi-common/package.json
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-common/src/write-manifest.ts
  packages/yoshi-common/write-manifest.d.ts
  packages/yoshi-common/write-manifest.js
  packages/yoshi-flow-app/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  scripts/utils/constants.js
  test/projects/kitchensink-javascript/integration/__snapshots__/manifest.test.js.snap
  test/projects/kitchensink-javascript/integration/manifest.test.js
  test/projects/kitchensink-javascript/src/cases/manifest.js
  test/projects/kitchensink-typescript/integration/__snapshots__/manifest.test.js.snap
  test/projects/kitchensink-typescript/integration/manifest.test.js
  test/projects/kitchensink-typescript/src/cases/manifest.tsx
  test/scripts.js
  test/utils.js
Labels: PR: New Feature :rocket:

#1683 pass through experimentalBuildHtml flag
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1684 Update Renovate Configuration
  renovate.json
Labels: PR: Chore :construction_worker:

#1512 don't publish from monorepo release command
  packages/yoshi-flow-monorepo/src/scripts/release.ts
Labels: PR: Bug Fix :bug:

#1691 Support transpiling TypeScript files with Carmi loader
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1693 Temporary webpack.config.ts work around for thunderbolt-elements
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Chore :construction_worker:

#1688 create-yoshi-app: update Server template with Node Platform types
  packages/create-yoshi-app/templates/server/typescript/index.js
  packages/create-yoshi-app/templates/server/typescript/index.ts
  packages/create-yoshi-app/templates/server/typescript/src/config.ts
  packages/create-yoshi-app/templates/server/typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/server/typescript/src/server.ts
  packages/create-yoshi-app/templates/server/typescript/src/types.ts
  packages/create-yoshi-app/templates/server/typescript/test/environment.ts
  packages/create-yoshi-app/templates/server/typescript/tsconfig.json
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
Labels: PR: New Feature :rocket:

#1685 Correctly link Yoshi's CLIs
  packages/create-yoshi-app/__tests__/create-yoshi-app.test.ts
  packages/create-yoshi-app/package.json
  scripts/utils/symlinkModules.js
Labels: PR: Internal :house:

#1671 Improve publish script
  package.json
  packages/yoshi-flow-monorepo/src/load-package-graph.ts
  scripts/customPublish.js
  scripts/customPublish.ts
Labels: PR: Internal :house:

#1697 Add test scripts for the new templates to come
  package.json
Labels: PR: Internal :house:

#1698 Remove `externalUnprocessedModules` option from docs
  docs/api/configuration.md
Labels: PR: Docs :memo:

#1700 to unversioned manifest
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-server/src/render.ts
  test/projects/kitchensink-javascript/integration/manifest.test.js
  test/projects/kitchensink-typescript/integration/manifest.test.js
Labels: PR: Polish :nail_care:

#1613 Yoshi BM Flow
  package.json
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/scripts/runE2E.js
  packages/create-yoshi-app/src/templates.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/.editorconfig
  packages/create-yoshi-app/templates/flow-bm/typescript/.npmrc
  packages/create-yoshi-app/templates/flow-bm/typescript/.nvmrc
  packages/create-yoshi-app/templates/flow-bm/typescript/__tests__/e2e/app.e2e.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/__tests__/e2e/drivers/app.driver.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/__tests__/test-common.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/dev/environment.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/dev/server.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/jest-yoshi.config.js
  packages/create-yoshi-app/templates/flow-bm/typescript/pom.xml
  packages/create-yoshi-app/templates/flow-bm/typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/BMModule.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/generateERB.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/generateFedeops.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/hooks/ExperimentsProvider.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/hooks/FedopsProvider.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/hooks/ModuleProvider.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/hooks/SentryProvider.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/hooks/TranslationProvider.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/hooks/useExperiments.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/hooks/useFedops.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/hooks/useModuleParams.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/hooks/useSentry.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/hooks/useTranslate.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/utils.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/withBM.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/poc/components/LegacyTodoList.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/poc/config.json
  packages/create-yoshi-app/templates/flow-bm/typescript/src/poc/methods/getTodo.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/poc/methods/getTodos.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/poc/moduleInit.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/poc/pages/index.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/poc/src/AddTodo.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/poc/src/TodoItem.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/poc/src/TodoList.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/poc/src/hooks/useTodos.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/poc/translations/de.json
  packages/create-yoshi-app/templates/flow-bm/typescript/src/poc/translations/en.json
  packages/create-yoshi-app/templates/flow-bm/typescript/templates/module_{%PROJECT_NAME%}.json.erb
  packages/create-yoshi-app/templates/flow-bm/typescript/tsconfig.json
  packages/create-yoshi-app/templates/flow-bm/typescript/tslint.json
  packages/create-yoshi-app/templates/flow-bm/typescript/wallaby.js
  packages/create-yoshi-app/templates/flow-bm/typescript/{%gitignore%}
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}
Labels: PR: Internal :house:

#1699 Wait for server process to listen to a port before opening the browser
  packages/yoshi-common/src/dev-environment.ts
Labels: PR: Bug Fix :bug:

#1703 file structure refactor
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/editorApp.e2e.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/settingsPanel.e2e.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/viewerApp.e2e.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/viewerScript.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/initApp.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/todo/Component.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/todo/Settings.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/todo/controller.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/todo/service.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/todo/styles.scss
  packages/create-yoshi-app/templates/flow-editor/javascript/yoshi.config.js
  packages/yoshi-flow-editor/src/buildEditorEntires.ts
  packages/yoshi-flow-editor/src/commands/start.ts
Labels: PR: Chore :construction_worker:

#1702 show package name on false publish
  scripts/customPublish.ts
Labels: PR: Internal :house:

#1706 Move dependencies to their rightful place in kitchensink tests
  test/projects/kitchensink-javascript/package.json
  test/projects/kitchensink-typescript/package.json
  test/projects/yoshi-server-javascript/package.json
  test/projects/yoshi-server-typescript/package.json
Labels: PR: Internal :house:

#1695 Skip package-lock.json on all packages
  .npmrc
  packages/yoshi-angular-dependencies/.npmrc
  packages/yoshi-config/.npmrc
  packages/yoshi-flow-app/.npmrc
  packages/yoshi-flow-legacy/.npmrc
  packages/yoshi-flow-monorepo/.npmrc
  packages/yoshi-helpers/.npmrc
  packages/yoshi-server-tools/.npmrc
  packages/yoshi-server/.npmrc
  packages/yoshi-style-dependencies/.npmrc
  packages/yoshi/.npmrc
Labels: PR: Chore :construction_worker:

#1694 Remove jest configuration from create-yoshi-app
  packages/create-yoshi-app/package.json
Labels: PR: Chore :construction_worker:

#1705 Bump some-what major dev dependencies and refactor yoshi-config
  .eslintrc
  package.json
  packages/yoshi-config/src/config.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-config/src/utils.ts
  packages/yoshi-flow-app/src/scripts/build.ts
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-editor/src/commands/build.ts
  packages/yoshi-flow-editor/src/webpack.config.ts
  packages/yoshi-flow-legacy/test/e2e.spec.js
  packages/yoshi-flow-monorepo/src/webpack.config.ts
  packages/yoshi-helpers/src/utils.ts
  packages/yoshi-server-tools/src/loader.ts
  packages/yoshi-server-tools/src/utils.ts
Labels: PR: Internal :house:

#1715 [Temporary hack] Always transpile `editor-elements` through ts-loader
  packages/yoshi-helpers/src/utils.ts
Labels: PR: Internal :house:

#1714 Build changes to support building editor-elements
  packages/yoshi-common/src/manifest-webpack-plugin.ts
  packages/yoshi-common/src/print-build-results.ts
  packages/yoshi-common/src/webpack-manager.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: New Feature :rocket:

#1718 Use transpiled JavaScript in the yoshi-flow-editor's templates (instead of jsx)
  packages/yoshi-flow-editor/src/editorAppWrapping.ts
  packages/yoshi-flow-editor/src/settingsWrapping.ts
Labels: PR: Internal :house:

#1721 fix eslint not running on .tsx files
  packages/yoshi-flow-legacy/src/commands/lint.js
  packages/yoshi-flow-legacy/test/lint.spec.js
Labels: PR: Polish :nail_care:

#1720 resolve bootstrap env vars according to cwd for monorepo support
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/server-process.ts
  packages/yoshi-flow-legacy/test/start.spec.js
  packages/yoshi-flow-monorepo/src/scripts/start.ts
  packages/yoshi-helpers/src/bootstrap-utils.ts
Labels: PR: Bug Fix :bug:

#1722 Telemetry
  packages/yoshi-common/package.json
  packages/yoshi-common/src/telemetry.ts
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/package.json
Labels: PR: Internal :house:

#1726 Use correct versions for packages inside the Yoshi monorepo
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#1728 Don't collect telemetry on Yoshi's E2E tests
  packages/yoshi-common/src/telemetry.ts
Labels: PR: Internal :house:

#1725 Assume only one pom.xml exists on monorepo root
  packages/yoshi-common/src/webpack-utils.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-helpers/src/queries.ts
Labels: PR: Bug Fix :bug:

#1729 remove netanelg from CODEOWNERS
  CODEOWNERS
Labels: PR: Chore :construction_worker:

#1727 resolving telemetry dependency
  packages/yoshi-common/telemetry.d.js
  packages/yoshi-common/telemetry.js
  packages/yoshi/bin/yoshi-cli.js
Labels: PR: Internal :house:

#1723 Build site assets modules with specific webpack config
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Internal :house:

#1724 Support working on webworker bundle locally in monorepo flow
  packages/yoshi-flow-monorepo/src/scripts/start.ts
Labels: PR: Polish :nail_care:

#1701 Add yoshi-flow-bm and make the template pass while using it
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}
  packages/yoshi-flow-bm-runtime/.npmrc
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm-runtime/src/index.ts
  packages/yoshi-flow-bm-runtime/tsconfig.json
  packages/yoshi-flow-bm/.npmrc
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-bm/src/bin/yoshi-bm.ts
  packages/yoshi-flow-bm/src/external-types.d.ts
  packages/yoshi-flow-bm/src/scripts/build.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  packages/yoshi-flow-bm/src/webpack.config.ts
  packages/yoshi-flow-bm/tsconfig.json
Labels: PR: Internal :house:

#1730 Stop telemetry until we have our own custom server
  packages/yoshi/bin/yoshi-cli.js
Labels: PR: Internal :house:
