Repository wix/yoshi, pull requests merged in 2019-05, with the labels that each got.

#1255 OOI generator best practices
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/App.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/App.st.css
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/appController.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/settingsPanel/SettingsPanel.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
Labels: PR: Polish :nail_care:

#1224 Create manifest JSON file with mapping to initial assets
  packages/yoshi-helpers/utils.js
  packages/yoshi/src/commands/build-app.js
  scripts/utils/constants.js
  scripts/utils/testProject.js
  test/projects/kitchensink-javascript/integration/__snapshots__/manifest.test.js.snap
  test/projects/kitchensink-javascript/integration/manifest.test.js
  test/projects/kitchensink-javascript/jest.plain.config.js
  test/projects/kitchensink-javascript/src/cases/manifest.js
  test/projects/kitchensink-typescript/integration/__snapshots__/manifest.test.js.snap
  test/projects/kitchensink-typescript/integration/manifest.test.js
  test/projects/kitchensink-typescript/jest.plain.config.js
  test/projects/kitchensink-typescript/src/cases/manifest.tsx
  test/projects/kitchensink-typescript/tsconfig.json
Labels: PR: New Feature :rocket:

#964 add basic unit tests for `yoshi-config`'s `validateConfig`
  packages/yoshi-config/__tests__/validate-config.spec.js
Labels: PR: Internal :house:

#1206 Pipe output to server.log in app-flow
  packages/yoshi-config/paths.js
  packages/yoshi/src/server-process.js
  packages/yoshi/src/tasks/app-server/index.js
Labels: PR: New Feature :rocket:

#1208 handle bad MATCH_ENV
  docs/migration/version-4.md
  packages/jest-yoshi-preset/constants.js
  packages/jest-yoshi-preset/jest-preset.js
Labels: PR: Polish :nail_care:

#1267 Add spec-setup with react-testing-library/clean-after-each
  packages/create-yoshi-app/templates/client/javascript/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/client/javascript/src/components/App/App.spec.js
  packages/create-yoshi-app/templates/client/typescript/__tests__/simple.e2e.ts
  packages/create-yoshi-app/templates/client/typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/client/typescript/src/components/App/App.spec.tsx
  packages/create-yoshi-app/templates/fullstack/javascript/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/fullstack/javascript/src/components/App/App.spec.js
  packages/create-yoshi-app/templates/fullstack/typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/fullstack/typescript/src/components/App/App.spec.tsx
Labels: PR: Polish :nail_care:

#1269 add another 100,000ms timeout to verify there is no timeout problem
  packages/create-yoshi-app/scripts/runE2E.js
Labels: PR: Internal :house:, 🛠 Infrastructure

#1271 configure algolia to search according to the version specified
  website/siteConfig.js
Labels: PR: Bug Fix :bug:

#1270 Remove task migrate to scoped packages
  packages/yoshi-helpers/queries.js
  packages/yoshi/src/commands/build.js
  packages/yoshi/src/commands/start.js
  packages/yoshi/src/tasks/migrate-to-scoped-packages/README.md
  packages/yoshi/src/tasks/migrate-to-scoped-packages/index.js
  packages/yoshi/test/migrate-to-scoped-packages.spec.js
  test-helpers/env-variables.js
Labels: PR: Chore :construction_worker:, PR: Polish :nail_care:

#1251 Improve error logging in jest setup error handling
  packages/yoshi-config/jest.js
Labels: PR: Polish :nail_care:

#1273 bump tpa-style-webpack-plugin to 1.3.7
  packages/yoshi/package.json
Labels: PR: Chore :construction_worker:

#1243 Fix issues with lint .js files in typescript environments
  packages/create-yoshi-app/templates/business-manager-module/typescript/tsconfig.json
  packages/create-yoshi-app/templates/client/typescript/.vscode/settings.json
  packages/create-yoshi-app/templates/client/typescript/tsconfig.json
  packages/create-yoshi-app/templates/fullstack/typescript/.vscode/settings.json
  packages/create-yoshi-app/templates/fullstack/typescript/tsconfig.json
Labels: PR: Bug Fix :bug:

#1262 Add jest-cli as a direct yoshi dependency.
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#1275 Rename ejs production file for html webpack plugin
  packages/yoshi/config/webpack.config.js
Labels: PR: Polish :nail_care:

#1277 bump tpa-style-webpack-plugin to 1.3.8
  packages/yoshi/package.json
Labels: PR: Chore :construction_worker:

#1274 Add React Hooks eslint rules
  .eslintignore
  package.json
  packages/eslint-config-yoshi-base/package.json
  packages/eslint-config-yoshi/README.md
  packages/eslint-config-yoshi/__tests__/env/jasmine.js
  packages/eslint-config-yoshi/__tests__/env/jest.js
  packages/eslint-config-yoshi/__tests__/env/mocha.js
  packages/eslint-config-yoshi/__tests__/env/protractor.js
  packages/eslint-config-yoshi/__tests__/eslint-config-yoshi.spec.js
  packages/eslint-config-yoshi/__tests__/rules/array-callback-return/valid.js
  packages/eslint-config-yoshi/__tests__/rules/array-callback-return/warn.js
  packages/eslint-config-yoshi/__tests__/rules/default-case/valid.js
  packages/eslint-config-yoshi/__tests__/rules/default-case/warn.js
  packages/eslint-config-yoshi/__tests__/rules/eqeqeq/valid.js
  packages/eslint-config-yoshi/__tests__/rules/eqeqeq/warn.js
  packages/eslint-config-yoshi/__tests__/rules/exhaustive-deps/valid.js
  packages/eslint-config-yoshi/__tests__/rules/exhaustive-deps/warn.js
  packages/eslint-config-yoshi/__tests__/rules/getter-return/valid.js
  packages/eslint-config-yoshi/__tests__/rules/getter-return/warn.js
  packages/eslint-config-yoshi/__tests__/rules/newline-after-import/foo.js
  packages/eslint-config-yoshi/__tests__/rules/newline-after-import/invalid.js
  packages/eslint-config-yoshi/__tests__/rules/newline-after-import/valid.js
  packages/eslint-config-yoshi/__tests__/rules/no-absolute-path/invalid.js
  packages/eslint-config-yoshi/__tests__/rules/no-amd/invalid.js
  packages/eslint-config-yoshi/__tests__/rules/no-array-constructor/valid.js
  packages/eslint-config-yoshi/__tests__/rules/no-array-constructor/warn.js
  packages/eslint-config-yoshi/__tests__/rules/no-caller/warn.js
  packages/eslint-config-yoshi/__tests__/rules/no-shadow/warn.js
  packages/eslint-config-yoshi/__tests__/rules/no-unused-vars/valid.js
  packages/eslint-config-yoshi/__tests__/rules/no-unused-vars/warn.js
  packages/eslint-config-yoshi/__tests__/rules/no-var/warn.js
  packages/eslint-config-yoshi/__tests__/rules/prefer-const/warn.js
  packages/eslint-config-yoshi/__tests__/rules/rules-of-hooks/invalid.js
  packages/eslint-config-yoshi/__tests__/rules/rules-of-hooks/valid.js
  packages/eslint-config-yoshi/index.js
  packages/eslint-config-yoshi/package.json
  packages/yoshi/package.json
Labels: PR: New Feature :rocket:

#1280 Fix hash for assets
  packages/yoshi/config/webpack.config.js
Labels: PR: Bug Fix :bug:

#1237 [create-yoshi-app]: remove `@types/axios` from devDeps
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
Labels: PR: Bug Fix :bug:

#1282 Log full URL to CDN, including scheme and port
  packages/yoshi/src/tasks/cdn/index.js
Labels: PR: Polish :nail_care:

#1279 Resolve symlinks to their symlinked locations in Webpack
  packages/yoshi/config/webpack.config.js
Labels: PR: Bug Fix :bug:

#1285 Basic monorepo support
  MONOREPO_SUPPORT.md
  packages/yoshi-config/loadConfig.js
  packages/yoshi-config/package.json
  packages/yoshi-config/paths.js
  packages/yoshi-config/schema/yoshi-config-schema.js
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/package.json
  packages/yoshi/src/commands/build-monorepo.js
  packages/yoshi/src/commands/release-monorepo.js
  packages/yoshi/src/commands/start-monorepo.js
  packages/yoshi/src/commands/utils/index.js
Labels: PR: New Feature :rocket:

#1290 Fix migration guide to Yoshi V4
  docs/migration/version-4.md
  website/blog/2019-03-12-yoshi-4.md
Labels: PR: Docs :memo:

#1291 Resolve symlinks only for monorepos
  packages/yoshi-config/loadConfig.js
  packages/yoshi/config/webpack.config.js
Labels: PR: Polish :nail_care:

#1292 Add InterpolateHtmlPlugin for html webpack plugin
  packages/yoshi/config/webpack.config.js
Labels: PR: New Feature :rocket:

#1293 Verify typescript references before build/start
  packages/yoshi/src/commands/build-monorepo.js
  packages/yoshi/src/commands/start-monorepo.js
  packages/yoshi/src/commands/utils/index.js
Labels: PR: New Feature :rocket:

#1288 fix(yoshi): don't remove viewBox from svg (fixes #1229)
  packages/yoshi/config/webpack.config.js
Labels: PR: Bug Fix :bug:

#1263 Fix babel-preset-yoshi resolve path.
  packages/yoshi-helpers/utils.js
Labels: PR: Bug Fix :bug:

#1258 Add `yoshi-template-intro` package to import it for all templates.
  packages/yoshi-template-intro/.npmignore
  packages/yoshi-template-intro/README.md
  packages/yoshi-template-intro/package.json
  packages/yoshi-template-intro/src/Logo/Logo.js
  packages/yoshi-template-intro/src/Logo/Logo.scss
  packages/yoshi-template-intro/src/Logo/index.js
  packages/yoshi-template-intro/src/TemplateIntro/TemplateIntro.js
  packages/yoshi-template-intro/src/TemplateIntro/TemplateIntro.scss
  packages/yoshi-template-intro/src/TemplateIntro/TemplateIntro.spec.js
  packages/yoshi-template-intro/src/TemplateIntro/index.js
Labels: PR: New Feature :rocket:

#1284 Update fullstack/client templates to use lazy-loaded Intro.
  packages/create-yoshi-app/templates/client/javascript/__tests__/simple.e2e.js
  packages/create-yoshi-app/templates/client/javascript/src/components/App/App.js
  packages/create-yoshi-app/templates/client/javascript/src/locales/messages_de.json
  packages/create-yoshi-app/templates/client/javascript/src/locales/messages_en.json
  packages/create-yoshi-app/templates/client/javascript/src/locales/messages_uk.json
  packages/create-yoshi-app/templates/client/typescript/__tests__/simple.e2e.ts
  packages/create-yoshi-app/templates/client/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/client/typescript/src/locales/messages_de.json
  packages/create-yoshi-app/templates/client/typescript/src/locales/messages_en.json
  packages/create-yoshi-app/templates/client/typescript/src/locales/messages_uk.json
  packages/create-yoshi-app/templates/fullstack/javascript/__tests__/browser.e2e.js
  packages/create-yoshi-app/templates/fullstack/javascript/src/components/App/App.js
  packages/create-yoshi-app/templates/fullstack/javascript/src/locales/messages_de.json
  packages/create-yoshi-app/templates/fullstack/javascript/src/locales/messages_en.json
  packages/create-yoshi-app/templates/fullstack/javascript/src/locales/messages_uk.json
  packages/create-yoshi-app/templates/fullstack/typescript/__tests__/browser.e2e.ts
  packages/create-yoshi-app/templates/fullstack/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/fullstack/typescript/src/locales/messages_de.json
  packages/create-yoshi-app/templates/fullstack/typescript/src/locales/messages_en.json
  packages/create-yoshi-app/templates/fullstack/typescript/src/locales/messages_uk.json
Labels: PR: New Feature :rocket:

#1301 Ignore monorepo hoisted dependencies in server bundle
  packages/yoshi/config/webpack.config.js
Labels: PR: Bug Fix :bug:

#1303 issue-1180: removed https for opening browser
  packages/yoshi/src/commands/start-app.js
Labels: PR: Bug Fix :bug:

#1302 Upgrade react to 16.8
  packages/create-yoshi-app/templates/client/javascript/src/index.vm
  packages/create-yoshi-app/templates/client/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/src/index.vm
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/javascript/src/index.ejs
  packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/typescript/src/index.ejs
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
Labels: PR: New Feature :rocket:

#1053 Use sockjs instead of ipc for server HMR communication
  packages/jest-environment-yoshi-puppeteer/globalTeardown.js
  packages/yoshi/config/hot.js
  packages/yoshi/package.json
  packages/yoshi/src/commands/start-app.js
  packages/yoshi/src/server-process.js
  packages/yoshi/src/socket-server.js
Labels: PR: Bug Fix :bug:

#1305 Update generators to use Webpack's dynamic import
  packages/create-yoshi-app/templates/client/javascript/src/components/App/App.js
  packages/create-yoshi-app/templates/client/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/javascript/src/components/App/App.js
  packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
  packages/yoshi-template-intro/package.json
Labels: PR: Bug Fix :bug:

#1306 Change Bootstrap's testkit to use server, instead of app
  packages/create-yoshi-app/templates/fullstack/javascript/environment.js
  packages/create-yoshi-app/templates/fullstack/typescript/environment.js
  packages/create-yoshi-app/templates/server/javascript/index.js
  packages/create-yoshi-app/templates/server/javascript/test/environment.js
  packages/create-yoshi-app/templates/server/typescript/index.js
  packages/create-yoshi-app/templates/server/typescript/test/environment.ts
Labels: PR: New Feature :rocket:

#1304 Core principles for adding code to CYA templates
  CORE_PRINCIPALS.md
Labels: PR: Docs :memo:

#1286 add wix-ui-tpa provider - for mobile mode
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/App.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/appController.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/appController.spec.js
Labels: PR: Polish :nail_care:

#1307 issue-1177: refresh jest's watch mode when updating jest-yoshi-config
  packages/jest-environment-yoshi-bootstrap/environment-setup.js
  packages/jest-environment-yoshi-puppeteer/globalSetup.js
  packages/jest-environment-yoshi-puppeteer/index.js
  packages/yoshi-config/jest.js
  packages/yoshi-config/package.json
Labels: PR: Bug Fix :bug:

#1311 create-yoshi-app: minor cleanups towards the perfection - 2d attempt
  docs/guides/app-flow.md
  packages/create-yoshi-app/templates/fullstack/javascript/index.js
  packages/create-yoshi-app/templates/fullstack/typescript/index.js
  packages/create-yoshi-app/templates/server/javascript/index.js
  packages/create-yoshi-app/templates/server/typescript/index.js
  website/versioned_docs/version-4.x/guides/app-flow.md
Labels: PR: Polish :nail_care:

#1312 Revert testkit server
  packages/create-yoshi-app/templates/fullstack/javascript/environment.js
  packages/create-yoshi-app/templates/fullstack/typescript/environment.js
  packages/create-yoshi-app/templates/server/javascript/test/environment.js
  packages/create-yoshi-app/templates/server/typescript/test/environment.ts
Labels: PR: Bug Fix :bug:

#1320 Fix migration guide to version 4
  docs/migration/version-4.md
Labels: PR: Bug Fix :bug:

#1322 Yoshi 4 migration ooi template
  .eslintignore
  packages/create-yoshi-app/templates/out-of-iframe/javascript/__tests__/e2e-setup.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/__tests__/e2e-ssr/verify-ssr.ssr.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/__tests__/e2e/editorApp.e2e.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/__tests__/helpers/i18n.mock.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/__tests__/jest-setup-ssr.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/dev/certificates/cert.pem
  packages/create-yoshi-app/templates/out-of-iframe/javascript/dev/certificates/key.pem
  packages/create-yoshi-app/templates/out-of-iframe/javascript/dev/fake-tpa-response.json
  packages/create-yoshi-app/templates/out-of-iframe/javascript/dev/server.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/dev/vm.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/dev/wix-private.mock.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/jest-ssr.config.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/jest-yoshi.config.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/App.spec.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/__tests__/e2e-setup.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/__tests__/e2e/editorApp.e2e.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/__tests__/helpers/i18n.mock.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/dev/certificates/cert.pem
  packages/create-yoshi-app/templates/out-of-iframe/typescript/dev/certificates/key.pem
  packages/create-yoshi-app/templates/out-of-iframe/typescript/dev/fake-tpa-response.json
  packages/create-yoshi-app/templates/out-of-iframe/typescript/dev/server.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/dev/vm.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/dev/wix-private.mock.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/jest-yoshi.config.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/app/App.spec.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
Labels: PR: Polish :nail_care:

#1326 reuse createApp from dev and move relevant parts to bin
  packages/create-yoshi-app/__tests__/createApp.spec.js
  packages/create-yoshi-app/bin/create-yoshi-app.js
  packages/create-yoshi-app/scripts/dev.js
  packages/create-yoshi-app/src/TemplateModel.js
  packages/create-yoshi-app/src/createApp.js
  packages/create-yoshi-app/src/utils.js
Labels: PR: Internal :house:

#1330 Add types-jest dep for jest autocomplete
  packages/jest-yoshi-preset/package.json
Labels: PR: New Feature :rocket:

#1331 Limit useless server HMR logs
  packages/yoshi/src/socket-server.js
Labels: PR: Polish :nail_care:

#1336 Use wallaby jest setup instead of mocha
  packages/create-yoshi-app/templates/library/javascript/wallaby.js
  packages/create-yoshi-app/templates/library/typescript/wallaby.js
Labels: PR: Bug Fix :bug:

#1338 Fix MANAGEMENT_PORT default and introduce GRPC_PORT
  packages/yoshi-helpers/bootstrap-utils.js
  packages/yoshi/test/start.spec.js
Labels: PR: Bug Fix :bug:

#1337 work against production when running npm start
  packages/create-yoshi-app/templates/out-of-iframe/javascript/__tests__/e2e/viewerApp.e2e.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerApp/viewerApp.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/__tests__/e2e/viewerApp.e2e.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/viewerApp/viewerApp.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
Labels: PR: New Feature :rocket:

#1340 Remove the unused configuration option - universalProject
  docs/api/configuration.md
  packages/yoshi-config/schema/yoshi-config-schema.js
  website/versioned_docs/version-4.x/api/configuration.md
Labels: PR: Polish :nail_care:
