Repository wix/yoshi, pull requests merged in 2019-12, with the labels that each got.

#1708 Correctly forward template e2e tests' output
  package.json
  packages/create-yoshi-app/scripts/e2e.js
Labels: PR: Chore :construction_worker:

#1739 Make `yoshi start` on legacy flow emit build to disk
  packages/yoshi-flow-legacy/src/tasks/cdn/index.js
Labels: PR: Bug Fix :bug:

#1740 Open url according to pkg config instead of root config
  packages/yoshi-flow-monorepo/src/scripts/start.ts
Labels: PR: Bug Fix :bug:, 🏘️ Monorepo

#1741 Adjust custom site assets config to use correct naming conventions
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#1743 Override output settings for site assets modules correctly
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1711 Use Node 12
  .nvmrc
  .travis.yml
  packages/create-yoshi-app/.nvmrc
  packages/create-yoshi-app/__tests__/__fixtures__/minimal-template/javascript/.nvmrc
  packages/create-yoshi-app/templates/business-manager-module/javascript/.nvmrc
  packages/create-yoshi-app/templates/business-manager-module/typescript/.nvmrc
  packages/create-yoshi-app/templates/client/javascript/.nvmrc
  packages/create-yoshi-app/templates/client/typescript/.nvmrc
  packages/create-yoshi-app/templates/flow-bm/typescript/.nvmrc
  packages/create-yoshi-app/templates/flow-editor/javascript/.nvmrc
  packages/create-yoshi-app/templates/fullstack/javascript/.nvmrc
  packages/create-yoshi-app/templates/fullstack/javascript/Dockerfile
  packages/create-yoshi-app/templates/fullstack/typescript/.nvmrc
  packages/create-yoshi-app/templates/fullstack/typescript/Dockerfile
  packages/create-yoshi-app/templates/library/javascript/.nvmrc
  packages/create-yoshi-app/templates/library/typescript/.nvmrc
  packages/create-yoshi-app/templates/out-of-iframe/javascript/.nvmrc
  packages/create-yoshi-app/templates/out-of-iframe/typescript/.nvmrc
  packages/create-yoshi-app/templates/server/javascript/.nvmrc
  packages/create-yoshi-app/templates/server/javascript/Dockerfile
  packages/create-yoshi-app/templates/server/typescript/.nvmrc
  packages/create-yoshi-app/templates/server/typescript/Dockerfile
  packages/yoshi-flow-legacy/test/jasmine.spec.js
  packages/yoshi-flow-legacy/test/start.spec.js
  packages/yoshi-flow-legacy/test/test.spec.js
  test/projects/kitchensink-javascript/.nvmrc
  test/projects/kitchensink-typescript/.nvmrc
  test/projects/yoshi-server-javascript/.nvmrc
  test/projects/yoshi-server-typescript/.nvmrc
Labels: PR: New Feature :rocket:

#1744 Switch node-platform deps from latest to ^1.0.0
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-server/package.json
  test/projects/yoshi-server-javascript/package.json
  test/projects/yoshi-server-typescript/package.json
Labels: PR: Chore :construction_worker:

#1745 Revert dockerfile version to stable
  packages/create-yoshi-app/templates/fullstack/javascript/Dockerfile
  packages/create-yoshi-app/templates/fullstack/typescript/Dockerfile
  packages/create-yoshi-app/templates/server/javascript/Dockerfile
  packages/create-yoshi-app/templates/server/typescript/Dockerfile
Labels: PR: Chore :construction_worker:

#1747 Add asset-relocate-loader for node bundles
  packages/yoshi-common/package.json
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-config/src/config.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-config/src/validConfig.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#1707 entry points with dynamic naming
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/editorApp.e2e.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/settingsPanel.e2e.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/viewerApp.e2e.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/viewerScript.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/dev/server.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Settings/index.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Widget/Component.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Widget/Component.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Widget/Component.st.css
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Widget/Settings.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Widget/Settings/Settings.global.scss
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Widget/Settings/Settings.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Widget/Settings/Settings.scss
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Widget/Settings/Settings.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Widget/controller.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Widget/controller.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Widget/index.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/templates/editorApp.vm
  packages/create-yoshi-app/templates/flow-editor/javascript/src/templates/settingsPanel.vm
  packages/create-yoshi-app/templates/flow-editor/javascript/wallaby.js
  packages/create-yoshi-app/templates/flow-editor/javascript/{%packagejson%}
  packages/yoshi-flow-editor-runtime/src/WidgetWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/createInstances.ts
  packages/yoshi-flow-editor-runtime/src/react/PublicDataContext.ts
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/src/buildEditorEntires.ts
  packages/yoshi-flow-editor/src/componentWrapping.ts
  packages/yoshi-flow-editor/src/editorAppWrapping.ts
  packages/yoshi-flow-editor/src/settingsWrapping.ts
  packages/yoshi-flow-editor/src/viewerScriptWrapping.ts
Labels: PR: Flow Editor 🖼

#1733 Change npm to yarn
  .gitignore
  .yarnrc
  CONTRIBUTING.md
  lerna.json
  package.json
  packages/create-yoshi-app/README.md
  packages/jest-yoshi-preset/package.json
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-legacy/test/build.spec.js
  packages/yoshi-flow-legacy/test/e2e.spec.js
  packages/yoshi-flow-legacy/test/loaders.spec.js
  packages/yoshi-flow-legacy/test/test.spec.js
  packages/yoshi-helpers/package.json
  packages/yoshi/config/wallaby-jest.js
  scripts/utils/symlinkModules.js
  test-helpers/test-phases.js
  test/projects/kitchensink-typescript/package.json
  test/projects/yoshi-server-typescript/package.json
  yarn.lock
Labels: PR: Internal :house:

#1751 Construct CDN URL according to the package's `experimentalBuildHtml`
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/cdnProxy.js
  packages/yoshi-common/src/webpack-utils.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-legacy/config/protractor.conf.js
  packages/yoshi-helpers/src/utils.ts
Labels: PR: Bug Fix :bug:, 🏘️ Monorepo

#1757 fixing yarn install issue
  .travis.yml
Labels: PR: Internal :house:

#1750 updating css-loader
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-style-dependencies/package.json
  yarn.lock
Labels: PR: Internal :house:

#1759 disable chunks on server bundle on thunderbolt-elements only
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#1758 Editor Elements fix - Transpile node-modules only for TB App
  packages/yoshi-helpers/src/utils.ts
Labels: PR: Polish :nail_care:

#1761 Build site-assets modules with content hashes in production
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1762 Fix thunderbolt/elements hacky transpilation
  packages/yoshi-helpers/src/utils.ts
Labels: PR: Bug Fix :bug:

#1756 Decrease amount of audit warnings during installation
  package.json
  yarn.lock
Labels: PR: Internal :house:

#1763 Throw when the publish fails
  scripts/customPublish.ts
Labels: PR: Internal :house:

#1731 Move all flow-bm framework logic into flow-bm CLI & runtime
  .yarnversion
  packages/create-yoshi-app/templates/flow-bm/typescript/components/LegacyTodoList.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/config.json
  packages/create-yoshi-app/templates/flow-bm/typescript/methods/getTodo.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/methods/getTodos.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/moduleInit.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/pages/index.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/AddTodo.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/TodoItem.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/TodoList.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/BMModule.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/hooks/useExperiments.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/framework/utils.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/hooks/useTodos.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/poc/methods/getTodo.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/poc/methods/getTodos.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/templates/module_{%PROJECT_NAME%}.json.erb
  packages/create-yoshi-app/templates/flow-bm/typescript/translations/de.json
  packages/create-yoshi-app/templates/flow-bm/typescript/translations/en.json
  packages/create-yoshi-app/templates/flow-bm/typescript/tsconfig.json
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm-runtime/src/createModule.ts
  packages/yoshi-flow-bm-runtime/src/external-types.d.ts
  packages/yoshi-flow-bm-runtime/src/hooks/ExperimentsProvider.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/FedopsProvider.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/ModuleProvider.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/SentryProvider.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/TranslationProvider.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/useExperiments.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/useFedops.ts
  packages/yoshi-flow-bm-runtime/src/hooks/useModuleParams.ts
  packages/yoshi-flow-bm-runtime/src/hooks/useSentry.ts
  packages/yoshi-flow-bm-runtime/src/hooks/useTranslate.tsx
  packages/yoshi-flow-bm-runtime/src/index.ts
  packages/yoshi-flow-bm-runtime/src/withBM.tsx
  packages/yoshi-flow-bm-runtime/tsconfig.json
  packages/yoshi-flow-bm/.gitignore
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-bm/src/bmExternalModules.ts
  packages/yoshi-flow-bm/src/generateERB.ts
  packages/yoshi-flow-bm/src/generateFedeops.ts
  packages/yoshi-flow-bm/src/renderModule.ts
  packages/yoshi-flow-bm/src/scripts/build.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  packages/yoshi-flow-bm/src/webpack.config.ts
  packages/yoshi-flow-bm/types.d.ts
  yarn.lock
Labels: PR: Flow BM 💼

#1769 Revert css-loader upgrade
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-style-dependencies/package.json
  yarn.lock
Labels: PR: Bug Fix :bug:

#1774 fix| ignore browser mainField when target:node
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1775 move global setup/teardown to e2e test environment
  packages/jest-yoshi-preset/jest-preset.js
Labels: PR: New Feature :rocket:

#1766 Extract BM flow's model
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-bm/src/bin/yoshi-bm.ts
  packages/yoshi-flow-bm/src/createFlowBMModel.ts
  packages/yoshi-flow-bm/src/renderModule.ts
  packages/yoshi-flow-bm/src/scripts/build.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  packages/yoshi-flow-bm/src/webpack.config.ts
Labels: PR: Flow BM 💼

#1765 HtmlWebpackPlugin: Inline CSS chunks / don't inject chunks
  packages/yoshi-common/html-polyfill-plugin.d.ts
  packages/yoshi-common/html-polyfill-plugin.js
  packages/yoshi-common/package.json
  packages/yoshi-common/src/html-inline-plugin.ts
  packages/yoshi-common/src/html-polyfill-plugin.ts
  packages/yoshi-common/src/lodash-template-loader.ts
  packages/yoshi-common/src/webpack.config.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#1782 Support split chunks config in monorepos
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:, 🏘️ Monorepo

#1755 [create-yoshi-app] upgrade `lint-staged` for templates to `9.5.0`
  packages/create-yoshi-app/templates/business-manager-module/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-editor/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/library/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/library/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/server/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
Labels: PR: New Feature :rocket:

#1784 Change when a chunk is inlined to be based on its name (.inline)
  packages/yoshi-common/src/html-inline-plugin.ts
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1786 Use more verbose names, don't add a redundant comma between script tags
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1787 Publish website on PRs using teamcity-surge-autorelease
  .travis.yml
  website/package.json
  website/siteConfig.js
  website/yarn.lock
Labels: PR: Internal :house:

#1789 Fix travis GH publishing
  website/package.json
Labels: PR: Bug Fix :bug:

#1792 Remove check for verbose on UncaughtError
  packages/yoshi-flow-legacy/bin/yoshi-cli.js
Labels: PR: Bug Fix :bug:

#1793 Add mdsvex svelte preprocessor
  packages/yoshi-common/package.json
  packages/yoshi-common/src/external-types.d.ts
  packages/yoshi-common/src/webpack.config.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#1777 Generate CI config in editor flow
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Widget/Widget.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Widget/Widget.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/Widget/Widget.st.css
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/app.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/todo/Widget.js
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-editor/src/bin/yoshi-flow-editor.ts
  packages/yoshi-flow-editor/src/buildEditorEntires.ts
  packages/yoshi-flow-editor/src/commands/build.ts
  packages/yoshi-flow-editor/src/commands/ciConfigGenerator.ts
  packages/yoshi-flow-editor/src/commands/start.ts
  packages/yoshi-flow-editor/src/componentWrapping.ts
  packages/yoshi-flow-editor/src/constants.ts
  packages/yoshi-flow-editor/src/editorAppWrapping.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/settingsWrapping.ts
  packages/yoshi-flow-editor/src/types.ts
  packages/yoshi-flow-editor/src/viewerScriptWrapping.ts
Labels: PR: Flow Editor 🖼

#1794 Update svelte-loader test regex to match `svx` files
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1796 Use one hot entry for the entire app instead of one per entry
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-app/src/scripts/start.ts
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  packages/yoshi-flow-editor/src/commands/start.ts
  packages/yoshi-flow-monorepo/src/scripts/start.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#1764 Integrate Suricate (tunneling)
  packages/yoshi-common/package.json
  packages/yoshi-common/src/dev-environment-logger.ts
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/external-types.d.ts
  packages/yoshi-common/src/server-process.ts
  packages/yoshi-common/src/utils/suricate.ts
  packages/yoshi-common/src/webpack-dev-server.ts
  packages/yoshi-common/src/webpack-utils.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-config/src/config.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-config/src/validConfig.ts
  packages/yoshi-flow-app/src/scripts/start.ts
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  packages/yoshi-flow-editor/src/commands/start.ts
  packages/yoshi-flow-monorepo/src/scripts/start.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#1791 Fix website publishing on master
  website/package.json
Labels: PR: Internal :house:

#1798 Fix PR website publishing
  website/siteConfig.js
Labels: PR: Bug Fix :bug:

#1802 do not emit runtime chunk on tb elements build
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:
