Repository wix/yoshi, pull requests merged in 2019-01, with the labels that each got.

#865 Use webpack node lib mock config in storybook config
  packages/yoshi/config/webpack.config.storybook.js
  packages/yoshi/test/webpack-config-storybook.spec.js
Labels: PR: Bug Fix :bug:

#850 Migrate business manager template to puppeteer
  packages/create-yoshi-app/scripts/runE2E.js
  packages/create-yoshi-app/templates/business-manager-module-typescript/jest-yoshi.config.js
  packages/create-yoshi-app/templates/business-manager-module-typescript/protractor.conf.js
  packages/create-yoshi-app/templates/business-manager-module-typescript/src/components/App/App.spec.tsx
  packages/create-yoshi-app/templates/business-manager-module-typescript/test/dev/server.ts
  packages/create-yoshi-app/templates/business-manager-module-typescript/test/e2e/app.e2e.ts
  packages/create-yoshi-app/templates/business-manager-module-typescript/test/e2e/app.spec.ts
  packages/create-yoshi-app/templates/business-manager-module-typescript/test/e2e/drivers/app.driver.ts
  packages/create-yoshi-app/templates/business-manager-module-typescript/test/environment.ts
  packages/create-yoshi-app/templates/business-manager-module-typescript/test/helpers/i18n.mock.ts
  packages/create-yoshi-app/templates/business-manager-module-typescript/test/mocha-setup.ts
  packages/create-yoshi-app/templates/business-manager-module-typescript/test/setup.component.js
  packages/create-yoshi-app/templates/business-manager-module-typescript/test/setup.e2e.ts
  packages/create-yoshi-app/templates/business-manager-module-typescript/tsconfig.json
  packages/create-yoshi-app/templates/business-manager-module-typescript/wallaby.js
  packages/create-yoshi-app/templates/business-manager-module-typescript/{%packagejson%}
Labels: PR: New Feature :rocket:

#906 Bump globby's version, 8.0.1 contained a bug
  package.json
  packages/create-yoshi-app/package.json
  packages/jest-environment-yoshi-puppeteer/package.json
  packages/jest-yoshi-preset/package.json
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#904 Update biz mgr babel template
  .eslintignore
  packages/create-yoshi-app/templates/business-manager-module-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/jest-yoshi.config.js
  packages/create-yoshi-app/templates/business-manager-module/protractor.conf.js
  packages/create-yoshi-app/templates/business-manager-module/src/components/App/App.spec.js
  packages/create-yoshi-app/templates/business-manager-module/test/dev/server.js
  packages/create-yoshi-app/templates/business-manager-module/test/e2e/app.e2e.js
  packages/create-yoshi-app/templates/business-manager-module/test/e2e/app.spec.js
  packages/create-yoshi-app/templates/business-manager-module/test/e2e/drivers/app.driver.js
  packages/create-yoshi-app/templates/business-manager-module/test/environment.js
  packages/create-yoshi-app/templates/business-manager-module/test/helpers/i18n.mock.js
  packages/create-yoshi-app/templates/business-manager-module/test/mocha-setup.js
  packages/create-yoshi-app/templates/business-manager-module/test/setup.component.js
  packages/create-yoshi-app/templates/business-manager-module/test/setup.e2e.js
  packages/create-yoshi-app/templates/business-manager-module/wallaby.js
  packages/create-yoshi-app/templates/business-manager-module/{%packagejson%}
Labels: PR: New Feature :rocket:

#891 Increase stalebot's counter params
  .github/stale.yml
Labels: PR: Internal :house:

#907 Remove `update-node-version` task from yoshi 2
  packages/yoshi/src/commands/build.js
  packages/yoshi/src/commands/start.js
  packages/yoshi/src/tasks/update-node-version/README.md
  packages/yoshi/src/tasks/update-node-version/index.js
  packages/yoshi/src/tasks/update-node-version/templates/.nvmrc
  packages/yoshi/test/build.spec.js
  packages/yoshi/test/start.spec.js
  packages/yoshi/test/tasks/update-node-version.spec.js
Labels: PR: Bug Fix :bug:

#910 Remove `jest/prefer-to-have-length` eslint rule
  packages/eslint-config-yoshi-base/test.js
Labels: PR: Bug Fix :bug:

#911 Replace deprecated ${workspaceRoot} variable with ${workspaceFolder}
  packages/create-yoshi-app/templates/client-typescript/.vscode/launch.json
  packages/create-yoshi-app/templates/client/.vscode/launch.json
  packages/create-yoshi-app/templates/component-library-typescript/.vscode/launch.json
  packages/create-yoshi-app/templates/component-library/.vscode/launch.json
  packages/create-yoshi-app/templates/fullstack-typescript/.vscode/launch.json
  packages/create-yoshi-app/templates/fullstack/.vscode/launch.json
  packages/create-yoshi-app/templates/node-library-typescript/.vscode/launch.json
  packages/create-yoshi-app/templates/node-library/.vscode/launch.json
  packages/create-yoshi-app/templates/platform-app/.vscode/launch.json
  packages/create-yoshi-app/templates/server-typescript/.vscode/launch.json
  packages/create-yoshi-app/templates/server/.vscode/launch.json
  packages/create-yoshi-app/templates/universal-typescript/.vscode/launch.json
  packages/create-yoshi-app/templates/universal/.vscode/launch.json
Labels: PR: Polish :nail_care:

#920 Bump dev dependency to typescript 3
  packages/jest-yoshi-preset/package.json
  packages/tslint-config-yoshi-base/package.json
  packages/tslint-config-yoshi/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi/package.json
Labels: PR: Internal :house:

#915 adds artifact id env var to bundle
  packages/yoshi-helpers/utils.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/test/webpack-config.spec.js
Labels: PR: New Feature :rocket:

#919 templates > add "read more" link to `*.json.erb` template files
  packages/create-yoshi-app/templates/business-manager-module-typescript/templates/module_{%PROJECT_NAME%}.json.erb
  packages/create-yoshi-app/templates/business-manager-module/templates/module_{%PROJECT_NAME%}.json.erb
  packages/create-yoshi-app/templates/fullstack-typescript/templates/{%projectName%}.json.erb
  packages/create-yoshi-app/templates/fullstack/templates/{%projectName%}.json.erb
  packages/create-yoshi-app/templates/server-typescript/templates/{%projectName%}.json.erb
  packages/create-yoshi-app/templates/server/templates/{%projectName%}.json.erb
  packages/create-yoshi-app/templates/universal-typescript/templates/{%projectName%}.json.erb
  packages/create-yoshi-app/templates/universal/templates/{%projectName%}.json.erb
Labels: PR: Polish :nail_care:

#932 Pass jest's globalConfig to jest-puppeteer global setup/teardown functions
  test/kitchensink/config/buildGlobalSetup.js
  test/kitchensink/config/buildGlobalTeardown.js
  test/kitchensink/config/plainGlobalSetup.js
  test/kitchensink/config/plainGlobalTeardown.js
  test/kitchensink/config/startGlobalSetup.js
  test/kitchensink/config/startGlobalTeardown.js
Labels: PR: Internal :house:

#930 Add process.env.IS_MINIFIED.
  packages/yoshi/config/webpack.config.js
  packages/yoshi/test/webpack-config.spec.js
Labels: PR: New Feature :rocket:

#909 Upgrade stylable packages to 1.0.0+
  packages/jest-yoshi-preset/package.json
  packages/yoshi/package.json
Labels: PR: New Feature :rocket:

#941 Update yoshi-config-schema to use webpack schema defaults
  packages/yoshi-config/index.js
  packages/yoshi-config/package.json
  packages/yoshi-config/schema/yoshi-config-schema.js
  packages/yoshi-config/schema/yoshi-config-schema.json
  packages/yoshi-config/utils/YoshiOptionsValidationError.js
Labels: PR: Bug Fix :bug:, PR: Internal :house:

#947 Remove redundant include for graphql files
  packages/yoshi/config/webpack.config.js
Labels: PR: Polish :nail_care:

#953 templates- set .npmrc to package-lock=false (#625)
  packages/create-yoshi-app/templates/business-manager-module-typescript/.npmrc
  packages/create-yoshi-app/templates/business-manager-module-typescript/{%gitignore%}
  packages/create-yoshi-app/templates/business-manager-module/.npmrc
  packages/create-yoshi-app/templates/business-manager-module/{%gitignore%}
  packages/create-yoshi-app/templates/client-typescript/.npmrc
  packages/create-yoshi-app/templates/client-typescript/{%gitignore%}
  packages/create-yoshi-app/templates/client/.npmrc
  packages/create-yoshi-app/templates/client/{%gitignore%}
  packages/create-yoshi-app/templates/component-library-typescript/.npmrc
  packages/create-yoshi-app/templates/component-library-typescript/{%gitignore%}
  packages/create-yoshi-app/templates/component-library/.npmrc
  packages/create-yoshi-app/templates/component-library/{%gitignore%}
  packages/create-yoshi-app/templates/fullstack-typescript/.npmrc
  packages/create-yoshi-app/templates/fullstack-typescript/{%gitignore%}
  packages/create-yoshi-app/templates/fullstack/.npmrc
  packages/create-yoshi-app/templates/fullstack/{%gitignore%}
  packages/create-yoshi-app/templates/node-library-typescript/.npmrc
  packages/create-yoshi-app/templates/node-library-typescript/{%gitignore%}
  packages/create-yoshi-app/templates/node-library/.npmrc
  packages/create-yoshi-app/templates/node-library/{%gitignore%}
  packages/create-yoshi-app/templates/platform-app/.npmrc
  packages/create-yoshi-app/templates/platform-app/{%gitignore%}
  packages/create-yoshi-app/templates/server-typescript/.npmrc
  packages/create-yoshi-app/templates/server-typescript/{%gitignore%}
  packages/create-yoshi-app/templates/server/.npmrc
  packages/create-yoshi-app/templates/server/{%gitignore%}
  packages/create-yoshi-app/templates/universal-typescript/.npmrc
  packages/create-yoshi-app/templates/universal-typescript/{%gitignore%}
  packages/create-yoshi-app/templates/universal/.npmrc
  packages/create-yoshi-app/templates/universal/{%gitignore%}
Labels: PR: Polish :nail_care:

#952 Run website job on master only
  .travis.yml
Labels: PR: Internal :house:
