Repository wix/yoshi, pull requests merged in 2019-09, with the labels that each got.

#1514 update tpa-style-webpack-plugin version
  packages/yoshi/package.json
Labels: PR: New Feature :rocket:

#1497 fix tests with `chalk`ed snapshots in color terms
  packages/create-yoshi-app/__tests__/create-yoshi-app.test.js
Labels: PR: Internal :house:

#1519 keep dynamic `import()` if `modules: false` (e.g. ECMAScript build)
  packages/babel-preset-yoshi/index.js
Labels: PR: New Feature :rocket:

#1527 Add comment regarding `babel-plugin-dynamic-import` to babel preset yoshi
  packages/babel-preset-yoshi/index.js
Labels: PR: Internal :house:

#1529 jest.config.js - allow overriding transformers from local config
  packages/yoshi/config/jest.config.js
Labels: PR: New Feature :rocket:

#1530 Remove travis configuration for Yoshi tests
  .travis.yml
Labels: PR: Internal :house:

#1531 separate kitchensink app-flow and yoshi-server tests
  package.json
Labels: PR: Internal :house:

#1532 Temporarily skip flaky HMR tests
  test/projects/kitchensink-javascript/integration/hmr.test.js
Labels: PR: Internal :house:

#1539 Inject HMR entries to the correct webpack configuration
  packages/yoshi/config/webpack.config.js
  test/projects/kitchensink-javascript/integration/hmr.test.js
Labels: PR: Bug Fix :bug:

#1541 Transform .api files only for those who opt-in
  packages/jest-yoshi-preset/utils.js
  packages/yoshi/config/webpack.config.js
Labels: PR: Bug Fix :bug:

#1550 ignoring leran backup files
  .gitignore
Labels: PR: Internal :house:

#1549 fixes #1524 adding hash to assets name
  packages/yoshi/config/webpack.config.js
  packages/yoshi/test/build.spec.js
  packages/yoshi/test/loaders.spec.js
  test/projects/kitchensink-javascript/integration/loaders.test.js
  test/projects/kitchensink-typescript/integration/loaders.test.js
Labels: PR: Bug Fix :bug:

#1552 Update typescript templates to TS ~3.6
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/library/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
Labels: PR: Polish :nail_care:

#1557 Exit on setup when setup is failing during kitchensink tests
  scripts/runKitchensink.js
Labels: PR: Internal :house:, 🛠 Infrastructure

#1554 CYA - Client stricter config
  .eslintignore
  packages/create-yoshi-app/templates/business-manager-module/javascript/__tests__/e2e/drivers/app.driver.js
  packages/create-yoshi-app/templates/business-manager-module/typescript/__tests__/e2e/drivers/app.driver.ts
  packages/create-yoshi-app/templates/client/javascript/__tests__/simple.e2e.js
  packages/create-yoshi-app/templates/client/typescript/__tests__/simple.e2e.ts
  packages/create-yoshi-app/templates/client/typescript/src/client.tsx
  packages/create-yoshi-app/templates/client/typescript/src/components/App/App.spec.tsx
  packages/create-yoshi-app/templates/client/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/client/typescript/src/components/__mocks__/i18n.ts
  packages/create-yoshi-app/templates/client/typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/client/typescript/src/i18n.ts
  packages/create-yoshi-app/templates/client/typescript/tsconfig.json
  packages/create-yoshi-app/templates/fullstack/javascript/__tests__/browser.e2e.js
  packages/create-yoshi-app/templates/fullstack/typescript/__tests__/browser.e2e.ts
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/editorApp/editorApp.e2e.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerApp/viewerApp.e2e.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/editorApp/editorApp.e2e.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/viewerApp/viewerApp.e2e.ts
  packages/jest-yoshi-preset/package.json
Labels: PR: New Feature :rocket:

#1555 Top commandד
  docs/getting-started/project-types.md
  docs/guides/stylelint-setup.md
  docs/migration/version-3.md
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/globalSetup.js
  packages/yoshi-config/load-packages.d.ts
  packages/yoshi-config/load-packages.js
  packages/yoshi-config/package.json
  packages/yoshi-config/root-app.d.ts
  packages/yoshi-config/root-app.js
  packages/yoshi-config/src/config.ts
  packages/yoshi-config/src/load-packages.ts
  packages/yoshi-config/src/loadConfig.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-config/src/paths.ts
  packages/yoshi-config/src/root-app.ts
  packages/yoshi-helpers/src/bootstrap-utils.ts
  packages/yoshi-helpers/src/queries.ts
  packages/yoshi-helpers/src/utils.ts
  packages/yoshi-server-tools/src/utils.ts
  packages/yoshi-server/src/render.ts
  packages/yoshi-server/src/routes/api.ts
  packages/yoshi-server/src/server.ts
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/config/protractor.conf.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/src/commands/build-app.js
  packages/yoshi/src/commands/build-monorepo.js
  packages/yoshi/src/commands/build.js
  packages/yoshi/src/commands/release-monorepo.js
  packages/yoshi/src/commands/start-app.js
  packages/yoshi/src/commands/start-monorepo.js
  packages/yoshi/src/commands/test.js
  packages/yoshi/src/commands/utils/build-apps.js
  packages/yoshi/src/commands/utils/build-libs.js
  packages/yoshi/src/commands/utils/copy-assets.js
  packages/yoshi/src/commands/utils/index.js
  packages/yoshi/src/commands/utils/print-build-results.js
  packages/yoshi/src/commands/utils/start-single-app.js
  packages/yoshi/src/commands/utils/write-manifest.js
  packages/yoshi/src/server-process.js
  packages/yoshi/src/tasks/app-server/index.js
  packages/yoshi/src/webpack-manager.js
  packages/yoshi/src/webpack-utils.js
Labels: PR: New Feature :rocket:

#1559 Transpile yoshi-server-client and yoshi-server-react to run on all browsers (ES5)
  packages/yoshi-server-client/tsconfig.json
  packages/yoshi-server-react/tsconfig.json
Labels: PR: Polish :nail_care:, 💁‍♂️ Yoshi Server

#1556 Align BM template react versions with BM
  packages/create-yoshi-app/templates/business-manager-module/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
Labels: PR: New Feature :rocket:

#1562 Update SVG usage
  docs/guides/svg.md
Labels: PR: Docs :memo:

#1566 Adjustments to monorepo setup
  packages/yoshi/src/commands/build-monorepo.js
  packages/yoshi/src/commands/start-monorepo.js
  packages/yoshi/src/commands/utils/build-libs.js
  packages/yoshi/src/commands/utils/index.js
Labels: PR: Polish :nail_care:

#1567 Fix a bug with passing incorrect arguments to Lerna's APIs
  packages/yoshi/src/commands/utils/index.js
Labels: PR: Bug Fix :bug:

#1572 Run type-check based on app's tsconfig rather than the root tsconfig
  packages/yoshi/config/webpack.config.js
Labels: PR: Polish :nail_care:

#1573 Jest preset asset transforms
  packages/jest-yoshi-preset/jest-preset.js
  packages/yoshi/types.d.ts
  test/projects/kitchensink-javascript/__node_modules__/asset-module/index.js
  test/projects/kitchensink-javascript/__node_modules__/asset-module/large-bart-simpson.gif
  test/projects/kitchensink-javascript/integration/loaders.test.js
  test/projects/kitchensink-javascript/src/components/features/large-external-image-inclusion.js
  test/projects/kitchensink-javascript/src/components/features/large-external-image-inclusion.spec.js
  test/projects/kitchensink-typescript/__node_modules__/asset-module/index.d.ts
  test/projects/kitchensink-typescript/__node_modules__/asset-module/index.js
  test/projects/kitchensink-typescript/__node_modules__/asset-module/large-bart-simpson.gif
  test/projects/kitchensink-typescript/integration/loaders.test.js
  test/projects/kitchensink-typescript/src/components/features/large-external-image-inclusion.spec.tsx
  test/projects/kitchensink-typescript/src/components/features/large-external-image-inclusion.tsx
Labels: PR: Bug Fix :bug:

#1561 explicit error on missing server entry
  packages/yoshi/config/webpack.config.js
  packages/yoshi/src/webpack-utils.js
  test/projects/kitchensink-javascript/integration/output.test.js
  test/projects/kitchensink-typescript/integration/output.test.js
Labels: PR: Bug Fix :bug:, 🐛 Bug
