Repository wix/yoshi, pull requests merged in 2019-03, with the labels that each got.

#1020 Change app-flow tests to support testing Yoshi's testing infra
  packages/jest-environment-yoshi-puppeteer/utils.js
  packages/yoshi-helpers/package.json
  packages/yoshi-helpers/queries.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
  packages/yoshi/src/webpack-utils.js
  scripts/runKitchensink.js
  scripts/utils/setupProject.js
  scripts/utils/testProject.js
  test/config/buildEnvironment.js
  test/config/buildGlobalSetup.js
  test/config/buildGlobalTeardown.js
  test/config/plainGlobalSetup.js
  test/config/startEnvironment.js
  test/config/startGlobalSetup.js
  test/config/startGlobalTeardown.js
  test/projects/kitchensink-javascript/.gitignore
  test/projects/kitchensink-javascript/__tests__/simple.e2e.js
  test/projects/kitchensink-javascript/integration/dev-server.test.js
  test/projects/kitchensink-javascript/integration/hmr.test.js
  test/projects/kitchensink-javascript/integration/loaders.test.js
  test/projects/kitchensink-javascript/jest.development.config.js
  test/projects/kitchensink-javascript/jest.production.config.js
  test/projects/kitchensink-javascript/src/components/features/__tests__/css-inclusion.spec.js
  test/projects/kitchensink-typescript/.gitignore
  test/projects/kitchensink-typescript/__tests__/simple.e2e.js
  test/projects/kitchensink-typescript/integration/dev-server.test.js
  test/projects/kitchensink-typescript/integration/hmr.test.js
  test/projects/kitchensink-typescript/integration/loaders.test.js
  test/projects/kitchensink-typescript/jest.development.config.js
  test/projects/kitchensink-typescript/jest.production.config.js
  test/projects/kitchensink-typescript/package.json
  test/projects/kitchensink-typescript/src/components/features/__tests__/css-inclusion.spec.tsx
  test/scripts.js
  test/utils.js
Labels: PR: Internal :house:

#1059 handle svg in tests (mocha,jest,jest-yoshi-preset) for react 15
  packages/jest-yoshi-preset/transforms/file.js
  packages/yoshi/config/svg-transformer.js
  packages/yoshi/src/ignore-extensions.js
Labels: PR: Bug Fix :bug:

#1061 use base on globs, add __tests__ to the new base
  packages/yoshi-config/globs.js
Labels: PR: Bug Fix :bug:

#1065 Fix deprecated resolve-url-loader config
  packages/yoshi/config/webpack.config.js
Labels: PR: Polish :nail_care:

#1066 faster TS for appflow, using incremental build
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
  packages/yoshi/src/commands/start-app.js
  test/projects/kitchensink-typescript/integration/hmr.test.js
Labels: PR: Polish :nail_care:

#1047 run eslint even after stylelint errors
  packages/yoshi/src/commands/lint.js
  packages/yoshi/test/lint.spec.js
Labels: PR: Bug Fix :bug:

#1064 Remove redundant files
  packages/yoshi/config/postcss.config.js
Labels: PR: Internal :house:

#1058 test improvements
  test/config/buildEnvironment.js
  test/config/startEnvironment.js
  test/projects/kitchensink-typescript/integration/hmr.test.js
  test/scripts.js
Labels: PR: Internal :house:

#1067 Add default Puppeteer timeouts
  packages/jest-environment-yoshi-puppeteer/index.js
Labels: PR: Breaking Change :boom:

#1071 Fix webpack version to v4.28.4
  packages/yoshi-config/package.json
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#1073 Support old flow cli options: --ssl and --entry-point
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/src/commands/start-app.js
Labels: PR: Polish :nail_care:

#1072 Fix https flag/option not starting webpack-dev-server in https
  packages/yoshi/src/commands/start-app.js
Labels: PR: Bug Fix :bug:

#1075 Support writing a stats file when running app-flow build
  packages/yoshi/src/commands/build-app.js
  test/projects/kitchensink-javascript/integration/stats.test.js
  test/projects/kitchensink-javascript/jest.plain.config.js
  test/projects/kitchensink-typescript/integration/stats.test.js
  test/projects/kitchensink-typescript/jest.plain.config.js
  test/scripts.js
Labels: PR: Bug Fix :bug:

#1076 Fix protractor glob to use new e2eTest glob
  packages/yoshi/config/protractor.conf.js
Labels: PR: Bug Fix :bug:

#1081 Fix setup docs according to new globs
  docs/guides/jest-setup.md
Labels: PR: Docs :memo:

#1028 add an option to load the config without validating it
  packages/yoshi-config/index.js
  packages/yoshi-config/loadConfig.js
Labels: PR: New Feature :rocket:

#1085 Bump puppeteer version to make sure a lower version is never installed
  package.json
  packages/jest-environment-yoshi-puppeteer/package.json
  packages/yoshi/package.json
  test/projects/kitchensink-javascript/package.json
  test/projects/kitchensink-typescript/package.json
Labels: PR: Bug Fix :bug:

#1084 Support opening the browser on a different url with `--url`
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/src/commands/start-app.js
Labels: PR: New Feature :rocket:

#1078 Polish the output of build-app to show file sizes
  packages/yoshi/package.json
  packages/yoshi/src/commands/build-app.js
Labels: PR: Polish :nail_care:

#1089 Remove deprecated fields from erb files in business manager generator
  packages/create-yoshi-app/templates/business-manager-module-typescript/templates/module_{%PROJECT_NAME%}.json.erb
  packages/create-yoshi-app/templates/business-manager-module/templates/module_{%PROJECT_NAME%}.json.erb
Labels: PR: Internal :house:

#1094 Transpile server code with default compiler options for angular apps
  packages/yoshi/config/webpack.config.js
Labels: PR: Bug Fix :bug:

#1095 Fix loader dependencies
  packages/yoshi-angular-dependencies/ng-annotate-loader.js
  packages/yoshi-angular-dependencies/package.json
  packages/yoshi-style-dependencies/css-hot-loader.js
  packages/yoshi-style-dependencies/css-loader.js
  packages/yoshi-style-dependencies/package.json
  packages/yoshi-style-dependencies/postcss-loader.js
  packages/yoshi-style-dependencies/resolve-url-loader.js
  packages/yoshi-style-dependencies/sass-loader.js
  packages/yoshi-style-dependencies/style-loader.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#1096 Update React to Version 16
  packages/create-yoshi-app/templates/business-manager-module-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/{%packagejson%}
  packages/create-yoshi-app/templates/client-typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/client-typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/client-typescript/src/index.vm
  packages/create-yoshi-app/templates/client-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/client/src/index.vm
  packages/create-yoshi-app/templates/client/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack-typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/fullstack-typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/fullstack-typescript/src/index.ejs
  packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/fullstack/src/index.ejs
  packages/create-yoshi-app/templates/fullstack/{%packagejson%}
  packages/eslint-config-yoshi/index.js
Labels: PR: New Feature :rocket:

#1106 Add back global regenerator-runtime
  packages/jest-yoshi-preset/jest-preset.js
  packages/jest-yoshi-preset/package.json
Labels: PR: Bug Fix :bug:

#1100 Update wallaby-jest.js
  packages/yoshi/config/wallaby-jest.js
Labels: PR: Polish :nail_care:

#1087 add an option to load the config without validating it
  packages/yoshi-config/index.js
  packages/yoshi-config/loadConfig.js
Labels: PR: Internal :house:

#1111 Use requireDefault helper for babel plugins.
  packages/babel-preset-yoshi/index.js
Labels: PR: Internal :house:

#1108 Version 4 migration guide/blog draft
  docs/assets/24-app-flow.png
  docs/guides/app-flow.md
  docs/migration/version-4.md
  website/blog/2019-03-12-yoshi-4.md
  website/blog/assets/24-app-flow.png
  website/sidebars.json
Labels: PR: Docs :memo:, 📝 WIP

#1120 Remove `haste-task-babel` dependency
  packages/yoshi/package.json
Labels: PR: Internal :house:

#1125 change old link to you documentation site in starting link
  packages/create-yoshi-app/templates/client-typescript/src/locales/messages_de.json
  packages/create-yoshi-app/templates/client-typescript/src/locales/messages_en.json
  packages/create-yoshi-app/templates/client/src/locales/messages_de.json
  packages/create-yoshi-app/templates/client/src/locales/messages_en.json
  packages/create-yoshi-app/templates/fullstack-typescript/src/locales/messages_de.json
  packages/create-yoshi-app/templates/fullstack-typescript/src/locales/messages_en.json
  packages/create-yoshi-app/templates/fullstack/src/locales/messages_de.json
  packages/create-yoshi-app/templates/fullstack/src/locales/messages_en.json
Labels: PR: Polish :nail_care:

#1123 migrate fullstack template to use app flow
  packages/create-yoshi-app/templates/fullstack-typescript/index.js
  packages/create-yoshi-app/templates/fullstack-typescript/src/server.ts
  packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/index.js
  packages/create-yoshi-app/templates/fullstack/src/server.js
  packages/create-yoshi-app/templates/fullstack/{%packagejson%}
Labels: PR: New Feature :rocket:

#1127 add title (babel) for babel task instead of a full path
  packages/yoshi/src/commands/build.js
  packages/yoshi/src/commands/start.js
Labels: PR: Bug Fix :bug:

#1128 use jests's default moduleFileExtensions configuration
  packages/jest-yoshi-preset/jest-preset.js
Labels: PR: Polish :nail_care:

#1129 Remove babel-core 7 bridge
  packages/jest-yoshi-preset/package.json
  packages/yoshi/package.json
Labels: PR: Polish :nail_care:

#1122 Verify that all yoshi related dependencies are in the same major version
  packages/yoshi-helpers/utils.js
  packages/yoshi/package.json
  packages/yoshi/src/cli.js
  packages/yoshi/src/commands/build-app.js
  packages/yoshi/src/verify-dependencies.js
Labels: PR: Polish :nail_care:

#1130 Support using setup file from test and not only from __tests__
  packages/jest-yoshi-preset/jest-preset.js
  packages/jest-yoshi-preset/package.json
Labels: PR: New Feature :rocket:

#1103 Minimize the impact of conflicting sass versions
  packages/yoshi-style-dependencies/node-sass.js
  packages/yoshi-style-dependencies/package.json
  packages/yoshi/config/webpack.config.js
Labels: PR: Polish :nail_care:

#1131 Remove redundant setup file, change default e2e timeout to 10s
  docs/guides/jest-setup.md
  packages/create-yoshi-app/templates/business-manager-module-typescript/__tests__/e2e-setup.ts
  packages/create-yoshi-app/templates/business-manager-module/__tests__/e2e-setup.js
  packages/create-yoshi-app/templates/client-typescript/__tests__/e2e-setup.ts
  packages/create-yoshi-app/templates/client/__tests__/e2e-setup.js
  packages/create-yoshi-app/templates/fullstack-typescript/__tests__/e2e-setup.ts
  packages/create-yoshi-app/templates/fullstack/__tests__/e2e-setup.js
  packages/jest-yoshi-preset/jest-preset.js
  packages/jest-yoshi-preset/setup/e2e.js
Labels: PR: Polish :nail_care:

#1115 Server side rendering: generate long/short class names in prod/dev respectively
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
  packages/yoshi/src/commands/test.js
  packages/yoshi/test/build.spec.js
  packages/yoshi/test/loaders.spec.js
Labels: PR: Bug Fix :bug:

#1132 adds sensible defaults for bootstrap environment
  packages/create-yoshi-app/templates/fullstack-typescript/environment.js
  packages/create-yoshi-app/templates/fullstack-typescript/index-dev.js
  packages/create-yoshi-app/templates/fullstack-typescript/jest-yoshi.config.js
  packages/create-yoshi-app/templates/fullstack/environment.js
  packages/create-yoshi-app/templates/fullstack/index-dev.js
  packages/create-yoshi-app/templates/fullstack/jest-yoshi.config.js
  packages/jest-environment-yoshi-bootstrap/constants.js
  packages/jest-environment-yoshi-bootstrap/index.js
  packages/yoshi/src/tasks/app-server/index.js
Labels: PR: Polish :nail_care:

#1137 replaced enzyme with react-testing-library
  packages/create-yoshi-app/templates/client-typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/client-typescript/src/components/App/App.spec.tsx
  packages/create-yoshi-app/templates/client-typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/client-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/client/src/components/App/App.js
  packages/create-yoshi-app/templates/client/src/components/App/App.spec.js
  packages/create-yoshi-app/templates/client/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack-typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/fullstack-typescript/src/components/App/App.spec.tsx
  packages/create-yoshi-app/templates/fullstack-typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/fullstack/src/components/App/App.js
  packages/create-yoshi-app/templates/fullstack/src/components/App/App.spec.js
  packages/create-yoshi-app/templates/fullstack/{%packagejson%}
Labels: PR: Polish :nail_care:

#1141 support environment parameters also in app flow
  packages/yoshi/src/server-process.js
Labels: PR: Bug Fix :bug:

#1142 supply a better default for new relic log level in user's app servers
  packages/yoshi/src/server-process.js
  packages/yoshi/src/tasks/app-server/index.js
Labels: PR: Polish :nail_care:

#1145 Document app flow scripts; fix typos
  docs/guides/app-flow.md
  website/blog/2019-03-12-yoshi-4.md
Labels: PR: Docs :memo:

#1148 Remove statics base url from client & fullstack templates
  packages/create-yoshi-app/templates/client-typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/client-typescript/src/index.vm
  packages/create-yoshi-app/templates/client/src/index.vm
  packages/create-yoshi-app/templates/fullstack-typescript/index.js
  packages/create-yoshi-app/templates/fullstack-typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/fullstack-typescript/src/index.ejs
  packages/create-yoshi-app/templates/fullstack/index.js
  packages/create-yoshi-app/templates/fullstack/src/index.ejs
  test/projects/kitchensink-typescript/src/external-types.d.ts
Labels: PR: Polish :nail_care:

#1140 Add Stylable Webpack plugin project level hashing
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#1152 Parse properly lint --fix argument
  packages/yoshi/src/commands/lint.js
  packages/yoshi/test/lint.spec.js
  test-helpers/fixtures.js
Labels: PR: Bug Fix :bug:

#1150 Add jest-watch-typeahead plugins
  packages/jest-yoshi-preset/jest-preset.js
  packages/jest-yoshi-preset/package.json
Labels: PR: New Feature :rocket:

#1153 Don't use node platform defaults if a project has old config folder
  packages/yoshi-config/paths.js
  packages/yoshi/src/server-process.js
  packages/yoshi/src/tasks/app-server/index.js
Labels: PR: Bug Fix :bug:

#1154 Add Stylable Webpack plugin project level hashing
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#1163 Update links in docs
  docs/migration/version-4.md
  website/blog/2019-03-12-yoshi-4.md
Labels: PR: Docs :memo:

#1151 Polish generators
  packages/create-yoshi-app/templates/client-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack-typescript/__tests__/browser.e2e.ts
  packages/create-yoshi-app/templates/fullstack-typescript/src/components/App/App.spec.tsx
  packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/__tests__/browser.e2e.js
  packages/create-yoshi-app/templates/fullstack/src/components/App/App.spec.js
  packages/create-yoshi-app/templates/fullstack/{%packagejson%}
Labels: PR: Polish :nail_care:

#1164 Update app-flow docs for client, add section about installing source-map-support
  docs/guides/app-flow.md
  packages/create-yoshi-app/templates/client-typescript/dev/server.js
  packages/create-yoshi-app/templates/client-typescript/dev/velocity.data.json
  packages/create-yoshi-app/templates/client-typescript/dev/velocity.private.data.json
  packages/create-yoshi-app/templates/client-typescript/dev/vm.js
  packages/create-yoshi-app/templates/client-typescript/jest-yoshi.config.js
  packages/create-yoshi-app/templates/client-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/dev/server.js
  packages/create-yoshi-app/templates/client/dev/velocity.data.json
  packages/create-yoshi-app/templates/client/dev/velocity.private.data.json
  packages/create-yoshi-app/templates/client/dev/vm.js
  packages/create-yoshi-app/templates/client/jest-yoshi.config.js
  packages/create-yoshi-app/templates/client/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/{%packagejson%}
  packages/yoshi/config/source-map-support.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/package.json
Labels: PR: Breaking Change :boom:

#1161 Defaults for rpc and petri testkits
  packages/jest-environment-yoshi-bootstrap/index.js
  packages/yoshi-helpers/bootstrap-utils.js
  packages/yoshi-helpers/index.js
  packages/yoshi/src/server-process.js
  packages/yoshi/src/tasks/app-server/index.js
  packages/yoshi/test/start.spec.js
Labels: PR: Polish :nail_care:

#1166 Support opening the browser on a different url with `--url` (for !appFlow)
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/src/commands/start.js
Labels: PR: New Feature :rocket:

#1167 Business Manager template opens correct url on `npm start`
  packages/create-yoshi-app/templates/business-manager-module-typescript/README.md
  packages/create-yoshi-app/templates/business-manager-module-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/README.md
  packages/create-yoshi-app/templates/business-manager-module/{%packagejson%}
Labels: PR: Polish :nail_care:

#1170 Remove redundant .eslintrc files and remove lint warnings on react version
  .eslintrc
  packages/eslint-config-yoshi-base/__tests__/eslint-config-yoshi-base.spec.js
  packages/yoshi/config/wallaby-jest.js
  packages/yoshi/test/.eslintrc
  packages/yoshi/test/lint.spec.js
  packages/yoshi/test/start.spec.js
  website/.eslintrc
Labels: PR: Internal :house:

#1168 Require yoshi-helpers files directly and simplify bootstrap env vars logic
  packages/eslint-config-yoshi/index.js
  packages/jest-environment-yoshi-bootstrap/constants.js
  packages/jest-environment-yoshi-bootstrap/index.js
  packages/jest-environment-yoshi-puppeteer/cdnProxy.js
  packages/jest-environment-yoshi-puppeteer/globalSetup.js
  packages/jest-environment-yoshi-puppeteer/globalTeardown.js
  packages/jest-environment-yoshi-puppeteer/index.js
  packages/jest-yoshi-preset/transforms/babel.js
  packages/yoshi-helpers/__tests__/utils.spec.js
  packages/yoshi-helpers/bootstrap-utils.js
  packages/yoshi-helpers/index.js
  packages/yoshi-helpers/package.json
  packages/yoshi-helpers/require-hooks/babel-register.js
  packages/yoshi-helpers/rewrite-forward-proxy.js
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/config/jasmine-setup.js
  packages/yoshi/config/jest-transformer.js
  packages/yoshi/config/jest.config.js
  packages/yoshi/config/karma.conf.js
  packages/yoshi/config/protractor.conf.js
  packages/yoshi/config/test-setup.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/src/commands/build-app.js
  packages/yoshi/src/commands/build.js
  packages/yoshi/src/commands/lint.js
  packages/yoshi/src/commands/start.js
  packages/yoshi/src/commands/test.js
  packages/yoshi/src/server-process.js
  packages/yoshi/src/tasks/app-server/index.js
  packages/yoshi/src/tasks/cdn/index.js
  packages/yoshi/src/tasks/migrate-to-scoped-packages/index.js
  packages/yoshi/src/webpack-debug-callback.js
  packages/yoshi/src/webpack-production-callback.js
  packages/yoshi/test/e2e.spec.js
  packages/yoshi/test/jasmine.spec.js
  packages/yoshi/test/migrate-to-scoped-packages.spec.js
  packages/yoshi/test/start.spec.js
  packages/yoshi/test/test.spec.js
  packages/yoshi/test/webpack-config.spec.js
Labels: PR: Internal :house:

#1158 Update husky && lint-staged
  packages/create-yoshi-app/templates/business-manager-module-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/{%packagejson%}
  packages/create-yoshi-app/templates/client-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/{%packagejson%}
  packages/create-yoshi-app/templates/server-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/server/{%packagejson%}
Labels: PR: Polish :nail_care:

#1175 Fix ESLint warnings and set maximum warnings to 0
  .eslintrc
  package.json
  packages/tslint-config-yoshi-base/__tests__/tslint-config-yoshi-base.spec.js
  packages/yoshi-helpers/utils.js
  packages/yoshi/src/tasks/app-server/index.js
  packages/yoshi/src/tasks/maven-statics/utils.js
  packages/yoshi/src/tasks/protractor/index.js
  packages/yoshi/test/build.spec.js
  packages/yoshi/test/drivers/runner.js
  packages/yoshi/test/start.spec.js
  packages/yoshi/test/test.spec.js
  packages/yoshi/test/webpack-config.spec.js
  test/projects/kitchensink-javascript/src/components/features/graphql-inclusion.spec.js
  test/projects/kitchensink-javascript/src/components/features/transpile-configured-external.spec.js
  test/projects/kitchensink-javascript/src/components/features/transpile-default-external.spec.js
Labels: PR: Internal :house:

#1182 Don't run Stylelint during `yoshi lint`
  packages/create-yoshi-app/templates/business-manager-module-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/{%packagejson%}
  packages/create-yoshi-app/templates/client-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/{%packagejson%}
  packages/create-yoshi-app/templates/server-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/server/{%packagejson%}
  packages/yoshi/src/commands/lint.js
  packages/yoshi/test/lint.spec.js
Labels: PR: Polish :nail_care:

#1184 tiny fix for app-flow guide (fix image url)
  docs/guides/app-flow.md
Labels: PR: Docs :memo:

#1186 Update husky && lint-staged use new recommended config format ("husky field in package.json")
  packages/create-yoshi-app/templates/business-manager-module-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/{%packagejson%}
  packages/create-yoshi-app/templates/client-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/{%packagejson%}
  packages/create-yoshi-app/templates/server-typescript/{%packagejson%}
  packages/create-yoshi-app/templates/server/{%packagejson%}
Labels: PR: Polish :nail_care:
