Repository wix/yoshi, pull requests merged in 2019-06, with the labels that each got.

#1347 Bump dependencies on Sunday instead of Thursday
  renovate.json
Labels: PR: Chore :construction_worker:

#1346 Bump Axios to v0.19.0
  packages/create-yoshi-app/templates/business-manager-module/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/server/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
  test/projects/kitchensink-javascript/package.json
  test/projects/kitchensink-typescript/package.json
Labels: PR: Polish :nail_care:

#1348 Use multi glob pattern instead of a set
  packages/jest-yoshi-preset/jest-preset.js
  packages/yoshi-config/globs.js
  packages/yoshi-helpers/queries.js
  packages/yoshi/config/jasmine-config.js
  packages/yoshi/config/protractor.conf.js
  packages/yoshi/config/webpack.config.specs.js
  packages/yoshi/src/commands/build.js
  packages/yoshi/src/commands/lint.js
  packages/yoshi/src/commands/start.js
  packages/yoshi/src/commands/test.js
  packages/yoshi/test/globs.spec.js
Labels: PR: Polish :nail_care:

#1351 support startUrl option and accept multiple urls for `--url` flag
  docs/api/cli.md
  docs/api/configuration.md
  jest.unit.config.js
  packages/yoshi-config/loadConfig.js
  packages/yoshi-config/schema/yoshi-config-schema.js
  packages/yoshi/src/commands/start-app.js
  packages/yoshi/src/commands/start.js
  packages/yoshi/src/commands/utils/__tests__/open-browser.test.js
  packages/yoshi/src/commands/utils/open-browser.js
Labels: PR: New Feature :rocket:

#1359 move yoshi test directory to be an inner directory
  test-helpers/test-phases.js
Labels: PR: Internal :house:

#1358 Server template - improvements
  packages/create-yoshi-app/templates/server/javascript/README.md
  packages/create-yoshi-app/templates/server/javascript/index.js
  packages/create-yoshi-app/templates/server/javascript/src/config.js
  packages/create-yoshi-app/templates/server/javascript/src/server.js
  packages/create-yoshi-app/templates/server/javascript/templates/{%projectName%}.json.erb
  packages/create-yoshi-app/templates/server/javascript/test/configs/{%projectName%}.json
  packages/create-yoshi-app/templates/server/javascript/test/environment.js
  packages/create-yoshi-app/templates/server/javascript/test/it/server.it.js
  packages/create-yoshi-app/templates/server/typescript/README.md
  packages/create-yoshi-app/templates/server/typescript/index.js
  packages/create-yoshi-app/templates/server/typescript/src/config.ts
  packages/create-yoshi-app/templates/server/typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/server/typescript/src/server.ts
  packages/create-yoshi-app/templates/server/typescript/templates/{%projectName%}.json.erb
  packages/create-yoshi-app/templates/server/typescript/test/configs/{%projectName%}.json
  packages/create-yoshi-app/templates/server/typescript/test/environment.ts
  packages/create-yoshi-app/templates/server/typescript/test/it/server.it.ts
  packages/create-yoshi-app/templates/server/typescript/tsconfig.json
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
Labels: PR: Polish :nail_care:

#1353 allow hmr over production site
  packages/yoshi/config/webpack.config.js
  packages/yoshi/src/webpack-utils.js
Labels: PR: New Feature :rocket:

#1361 Remove Hebrew talks links from Yoshi's site
  docs/guides/app-flow.md
  website/blog/2019-03-12-yoshi-4.md
  website/versioned_docs/version-4.x/guides/app-flow.md
Labels: PR: Docs :memo:

#1356 feat(create-yoshi-app): remove organization form wizard and pom.xml
  packages/create-yoshi-app/README.md
  packages/create-yoshi-app/__tests__/__fixtures__/fake-template/typescript/template.txt
  packages/create-yoshi-app/__tests__/__snapshots__/generateProject.spec.js.snap
  packages/create-yoshi-app/__tests__/createApp.spec.js
  packages/create-yoshi-app/__tests__/generateProject.spec.js
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/src/TemplateModel.js
  packages/create-yoshi-app/src/getQuestions.js
  packages/create-yoshi-app/src/getValuesMap.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/pom.xml
  packages/create-yoshi-app/templates/business-manager-module/typescript/pom.xml
  packages/create-yoshi-app/templates/client/javascript/pom.xml
  packages/create-yoshi-app/templates/client/typescript/pom.xml
  packages/create-yoshi-app/templates/fullstack/javascript/pom.xml
  packages/create-yoshi-app/templates/fullstack/typescript/pom.xml
  packages/create-yoshi-app/templates/library/javascript/pom.xml
  packages/create-yoshi-app/templates/library/typescript/pom.xml
  packages/create-yoshi-app/templates/out-of-iframe/javascript/pom.xml
  packages/create-yoshi-app/templates/out-of-iframe/typescript/pom.xml
  packages/create-yoshi-app/templates/server/javascript/pom.xml
  packages/create-yoshi-app/templates/server/typescript/pom.xml
  test-helpers/fixtures.js
  test/projects/kitchensink-javascript/pom.xml
  test/projects/kitchensink-typescript/pom.xml
Labels: PR: Polish :nail_care:

#1362 open both editor and viewer + move to js config
  packages/create-yoshi-app/templates/out-of-iframe/javascript/yoshi.config.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/yoshi.config.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
Labels: PR: New Feature :rocket:

#1363 Improve symlink modules by removing the existing modules before
  packages/create-yoshi-app/scripts/dev.js
  scripts/utils/setupProject.js
  scripts/utils/symlinkModules.js
Labels: PR: Internal :house:

#1350 refactor of the out-of-iframe template readme (app -> widget)
  packages/create-yoshi-app/templates/out-of-iframe/javascript/README.md
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/App/index.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/Widget/Widget.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/Widget/Widget.spec.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/Widget/Widget.st.css
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/Widget/appController.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/Widget/appController.spec.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/Widget/index.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/editorApp/editorApp.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerApp/viewerScript.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerApp/viewerScript.spec.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerApp/viewerWidget.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/yoshi.config.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/README.md
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/App/index.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/Widget.spec.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/Widget.st.css
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/Widget.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/appController.spec.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/appController.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/index.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/editorApp/editorApp.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/viewerApp/viewerScript.spec.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/viewerApp/viewerScript.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/viewerApp/viewerWidget.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/yoshi.config.js
Labels: PR: Polish :nail_care:

#1371 fix a bug with ooi viewer app css path
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerApp/viewerWidget.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/viewerApp/viewerWidget.tsx
Labels: PR: Bug Fix :bug:

#1367 create-yoshi-app: custom entry point for server project templates
  packages/create-yoshi-app/templates/server/javascript/index-dev.js
  packages/create-yoshi-app/templates/server/javascript/test/environment.js
  packages/create-yoshi-app/templates/server/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/server/typescript/index-dev.js
  packages/create-yoshi-app/templates/server/typescript/test/environment.ts
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
Labels: PR: Polish :nail_care:

#1369 Run minimal number of tests on PR CI
  packages/yoshi-config/loadConfig.js
  packages/yoshi-config/schema/yoshi-config-schema.js
  packages/yoshi-helpers/queries.js
  packages/yoshi/package.json
  packages/yoshi/src/commands/test.js
  packages/yoshi/src/commands/utils/dependency-resolver.js
Labels: PR: New Feature :rocket:

#1373 Adjust to deprecated autoprefixer API
  packages/yoshi/config/webpack.config.js
Labels: PR: Bug Fix :bug:

#1374 Improve the ooi templates readme
  packages/create-yoshi-app/templates/out-of-iframe/javascript/README.md
  packages/create-yoshi-app/templates/out-of-iframe/javascript/dev/sites.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerApp/viewerApp.e2e.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/yoshi.config.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/README.md
  packages/create-yoshi-app/templates/out-of-iframe/typescript/dev/sites.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/viewerApp/viewerApp.e2e.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/yoshi.config.js
Labels: PR: Polish :nail_care:

#1378 update ooi development site
  packages/create-yoshi-app/templates/out-of-iframe/javascript/dev/sites.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/dev/sites.js
Labels: PR: Polish :nail_care:

#1381 server TypeScript template - bump target to es6
  packages/create-yoshi-app/templates/server/typescript/tsconfig.json
Labels: PR: Polish :nail_care:

#1384 Remove the dependency on @stylable/cli
  packages/yoshi/package.json
Labels: PR: Polish :nail_care:

#1394 Upgrade verdaccio
  package.json
Labels: PR: Chore :construction_worker:

#1391 Publish monorepo libs only in master CI
  packages/yoshi/src/commands/release-monorepo.js
Labels: PR: Bug Fix :bug:

#1390 Detect an available port for server HMR
  packages/yoshi/config/hot.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/src/commands/start-app.js
  packages/yoshi/src/server-process.js
  packages/yoshi/src/socket-server.js
Labels: PR: Polish :nail_care:

#1396 Remove Sentry from code-base
  packages/create-yoshi-app/package.json
  packages/yoshi/bin/yoshi-cli.js
  packages/yoshi/package.json
  packages/yoshi/src/cli.js
  packages/yoshi/src/constants.js
  packages/yoshi/src/sentry.js
  website/static/error-feedback.html
Labels: PR: Internal :house:

#1398 Dependencies: replace `react-testing-library` with `@testing-library/react`
  packages/create-yoshi-app/templates/client/javascript/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/client/javascript/src/components/App/App.spec.js
  packages/create-yoshi-app/templates/client/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/client/typescript/src/components/App/App.spec.tsx
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/javascript/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/fullstack/javascript/src/components/App/App.spec.js
  packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/fullstack/typescript/src/components/App/App.spec.tsx
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
Labels: PR: Polish :nail_care:

#1399 Run wnpm-ci prepareForRelase() only in master CI
  packages/yoshi/src/commands/release-monorepo.js
Labels: PR: Polish :nail_care:

#1402 Skip a flaky test which fails very often
  packages/yoshi/test/start.spec.js
Labels: PR: Internal :house:

#1370 Bump node to v10 for library generator and kitchensink tests
  packages/create-yoshi-app/templates/library/javascript/.nvmrc
  packages/create-yoshi-app/templates/library/typescript/.nvmrc
  test/projects/kitchensink-javascript/.nvmrc
  test/projects/kitchensink-typescript/.nvmrc
Labels: PR: Polish :nail_care:

#1400 Bump Lerna to v3
  lerna.json
  package.json
  scripts/createVersion.js
  scripts/utils/publishMonorepo.js
Labels: PR: Internal :house:

#1405 Remove unused/dead code
  packages/yoshi-helpers/queries.js
  packages/yoshi-helpers/utils.js
  packages/yoshi/config/mocha-setup.js
Labels: PR: Internal :house:

#1406 Fix out-dated Stylelint docs
  docs/guides/stylelint-setup.md
Labels: PR: Docs :memo:

#1414 Lock terser to v4.0.0 to fix a bug in v4.0.1
  package.json
  packages/eslint-config-yoshi/package.json
  packages/yoshi-config/package.json
  packages/yoshi-config/schema/WebpackOptions.json
  packages/yoshi-config/schema/yoshi-config-schema.js
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#1416 Bump typa-style-webpack-plugin
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#1417 Fix terser-webpack-plugin
  packages/yoshi/package.json
Labels: PR: Bug Fix :bug:

#1419 Update verifyRegistry to check if Wix private registry is reachable (#1403)
  packages/create-yoshi-app/__tests__/verifyRegistry.spec.js
  packages/create-yoshi-app/src/utils.js
  packages/create-yoshi-app/src/verifyRegistry.js
Labels: PR: Bug Fix :bug:

#1377 Support web-worker bundle in Yoshi
  package.json
  packages/create-yoshi-app/templates/out-of-iframe/javascript/yoshi.config.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/yoshi.config.js
  packages/yoshi-config/loadConfig.js
  packages/yoshi-config/schema/yoshi-config-schema.js
  packages/yoshi-helpers/queries.js
  packages/yoshi/config/webpack.config.js
  packages/yoshi/src/commands/build-app.js
  packages/yoshi/src/commands/start-app.js
  packages/yoshi/src/webpack-utils.js
  test/config/buildEnvironment.js
  test/projects/kitchensink-javascript/integration/hmr.test.js
  test/projects/kitchensink-javascript/integration/web-worker.test.js
  test/projects/kitchensink-javascript/jest.development.config.js
  test/projects/kitchensink-javascript/jest.production.config.js
  test/projects/kitchensink-javascript/package.json
  test/projects/kitchensink-javascript/src/components/features/web-worker.js
  test/projects/kitchensink-javascript/src/server.js
  test/projects/kitchensink-javascript/src/web-worker-wrapper.js
  test/projects/kitchensink-javascript/src/worker.js
  test/projects/kitchensink-typescript/integration/hmr.test.js
  test/projects/kitchensink-typescript/integration/web-worker.test.js
  test/projects/kitchensink-typescript/jest.development.config.js
  test/projects/kitchensink-typescript/jest.production.config.js
  test/projects/kitchensink-typescript/package.json
  test/projects/kitchensink-typescript/src/components/features/web-worker.tsx
  test/projects/kitchensink-typescript/src/server.tsx
  test/projects/kitchensink-typescript/src/web-worker-wrapper.js
  test/projects/kitchensink-typescript/src/worker.ts
Labels: PR: New Feature :rocket:
