Repository wix/yoshi, pull requests merged in 2020-01, with the labels that each got.

#1803 use unversioned public path on prod bundle only
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1801 moving to sync requiring for ssr
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/config/i18n.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/config/i18n.ts
Labels: PR: Bug Fix :bug:

#1807 Fix `.tsbuildinfo` (TypeScript cache file) bug with external types.
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/external-types.d.ts
  packages/yoshi-common/src/sync-petri-specs.ts
  packages/yoshi-common/src/utils/suricate.ts
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Internal :house:

#1808 Fix a bug - missing a return statement
  test/utils.js
Labels: PR: Internal :house:

#1809 drop `haml` tests
  packages/yoshi-flow-legacy/test/loaders.spec.js
Labels: PR: Internal :house:

#1795 show warning in case a devDependency (yoshi) is in dependencies
  packages/yoshi-common/package.json
  packages/yoshi-common/src/verify-dependencies.ts
  test/projects/kitchensink-javascript/integration/verify-dependencies.test.js
  test/projects/kitchensink-javascript/jest.plain.config.js
  test/projects/kitchensink-typescript/integration/verify-dependencies.test.js
  test/projects/kitchensink-typescript/jest.plain.config.js
Labels: PR: Chore :construction_worker:

#1788 Separate jest overrides supported type by project type.
  docs/guides/jest-setup.md
  packages/jest-yoshi-preset/jest-preset.js
  packages/yoshi-config/src/jest/config.ts
  packages/yoshi-config/src/jest/index.ts
  packages/yoshi-config/src/jest/validConfig.ts
  test/projects/kitchensink-javascript/__tests__/simple.e2e.js
Labels: PR: Breaking Change :boom:

#1818 replace @ with _ in tunnel ids
  packages/yoshi-common/src/utils/suricate.ts
Labels: PR: Bug Fix :bug:

#1737 installing dependencies when needed
  package.json
  scripts/post-merge.js
Labels: PR: Internal :house:

#1810 Move suricate private dependency to be loaded by the consumer
  packages/yoshi-common/package.json
  packages/yoshi-common/src/server-process.ts
  packages/yoshi-common/src/utils/suricate.ts
  yarn.lock
Labels: PR: Bug Fix :bug:

#1805 jest-yoshi-preset - jest debug watch mode plugin.
  docs/guides/debugging.md
  packages/eslint-config-yoshi-base/test.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/constants.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/globalSetup.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/index.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/utils.js
  packages/jest-yoshi-preset/jest-preset.js
  packages/jest-yoshi-preset/plugins/jest-watch-debug.js
  packages/jest-yoshi-preset/setup/e2e.js
  packages/jest-yoshi-preset/types.d.ts
Labels: PR: New Feature :rocket:

#1780 New testing infra
  .eslintignore
  .eslintrc
  .gitignore
  jest-puppeteer.config.js
  jest-setup.js
  jest.config.js
  package.json
  packages/yoshi-common/src/webpack.config.ts
  scripts/utils/testProject.js
  test/config/plainGlobalSetup.js
  test/globalSetup.js
  test/globalTeardown.js
  test/javascript/features/css-inclusion/css-inclusion.test.js
  test/javascript/features/css-inclusion/src/component.js
  test/javascript/features/css-inclusion/src/style.css
  test/javascript/features/externals/externals.test.js
  test/javascript/features/externals/package.json
  test/javascript/features/externals/src/component.js
  test/javascript/features/externals/src/index.ejs
  test/javascript/features/json-inclusion/json-inclusion.test.js
  test/javascript/features/json-inclusion/src/abstract.json
  test/javascript/features/json-inclusion/src/component.js
  test/javascript/fixtures/base-template/package.json
  test/javascript/fixtures/base-template/src/client.js
  test/javascript/fixtures/base-template/src/component.spec.js
  test/javascript/fixtures/base-template/src/index.ejs
  test/javascript/fixtures/base-template/src/server.js
  test/projects/kitchensink-javascript/integration/output.test.js
  test/projects/kitchensink-typescript/integration/output.test.js
  test/scripts.js
  test/typescript/features/css-inclusion/css-inclusion.test.js
  test/typescript/features/css-inclusion/src/component.tsx
  test/typescript/features/json-inclusion/json-inclusion.test.js
  test/typescript/features/json-inclusion/src/abstract.json
  test/typescript/features/json-inclusion/src/component.tsx
  test/typescript/fixtures/base-template/package.json
  test/typescript/fixtures/base-template/src/client.tsx
  test/typescript/fixtures/base-template/src/component.spec.tsx
  test/typescript/fixtures/base-template/src/index.ejs
  test/typescript/fixtures/base-template/src/server.js
  test/typescript/fixtures/base-template/src/style.css
  test/typescript/fixtures/base-template/tsconfig.json
  test/utils.js
  test/yoshi-publish/package.json
  yarn.lock
Labels: PR: Internal :house:

#1823 Reduce verdaccio logger output
  verdaccio.yaml
Labels: PR: Internal :house:

#1828 test infra: fix a naming bug
  package.json
Labels: PR: Internal :house:

#1822 `create-yoshi-app` - perform initial commit
  packages/create-yoshi-app/__tests__/createApp.test.ts
  packages/create-yoshi-app/src/createApp.ts
  packages/create-yoshi-app/src/utils.ts
Labels: PR: New Feature :rocket:

#1811 Generate `stats.json` during build and start into `dist/statics`
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-flow-monorepo/src/webpack.config.ts
  yarn.lock
Labels: PR: Polish :nail_care:

#1834 reduce lerna's log level from default (notice) to 'warn'
  scripts/utils/publishMonorepo.js
Labels: PR: Internal :house:

#1825 Install with yarn in e2e tests
  test/globalSetup.js
Labels: PR: Internal :house:

#1835 serve statics from dev server in monorepo flow
  packages/yoshi-common/src/dev-environment.ts
Labels: PR: Bug Fix :bug:

#1836 Do not try to publish on pullrequest CI
  scripts/customPublish.ts
Labels: PR: Internal :house:

#1842 Fix externals not resolving correctly with monorepos
  packages/yoshi-common/package.json
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-editor/package.json
  yarn.lock
Labels: PR: Bug Fix :bug:, 🏘️ Monorepo

#1838 Test infra: move tests to new infra
  test/javascript/features/transpile-configured-external-javascript/__node_modules__/untranspiled-dependency/javascript.js
  test/javascript/features/transpile-configured-external-javascript/package.json
  test/javascript/features/transpile-configured-external-javascript/src/component.js
  test/javascript/features/transpile-configured-external-javascript/transpile-configured-external-javascript.test.js
  test/javascript/features/transpile-whitelisted-external/__node_modules__/wix-style-react/src/index.js
  test/javascript/features/transpile-whitelisted-external/src/component.js
  test/javascript/features/transpile-whitelisted-external/transpile-whitelisted-external.test.js
  test/projects/kitchensink-javascript/integration/transpile-externals.test.js
  test/projects/kitchensink-javascript/src/components/features/transpile-default-external.spec.js
  test/projects/kitchensink-typescript/integration/transpile-externals.test.js
  test/scripts.js
  test/typescript/features/transpile-configured-external-javascript/__node_modules__/untranspiled-dependency/javascript.js
  test/typescript/features/transpile-configured-external-javascript/package.json
  test/typescript/features/transpile-configured-external-javascript/src/component.tsx
  test/typescript/features/transpile-configured-external-javascript/transpile-configured-external-javascript.test.js
  test/typescript/features/transpile-configured-external-typescript/__node_modules__/untranspiled-dependency/typescript.tsx
  test/typescript/features/transpile-configured-external-typescript/package.json
  test/typescript/features/transpile-configured-external-typescript/src/component.tsx
  test/typescript/features/transpile-configured-external-typescript/transpile-configured-external-typescript.test.js
  test/typescript/features/transpile-whitelisted-external/__node_modules__/wix-style-react/src/index.js
  test/typescript/features/transpile-whitelisted-external/src/component.tsx
  test/typescript/features/transpile-whitelisted-external/transpile-whitelisted-external.test.js
Labels: PR: Internal :house:

#1847 change babel-preset-yoshi to be loaded from yoshi-common
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/globalSetup.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/index.js
  packages/jest-yoshi-preset/jest-preset.js
  packages/jest-yoshi-preset/package.json
  packages/jest-yoshi-preset/transforms/babel.js
  packages/yoshi-common/create-babel-config.d.ts
  packages/yoshi-common/create-babel-config.js
  packages/yoshi-common/package.json
  packages/yoshi-common/require-hooks.d.ts
  packages/yoshi-common/require-hooks.js
  packages/yoshi-common/src/create-babel-config.ts
  packages/yoshi-common/src/require-hooks/babel-register.ts
  packages/yoshi-common/src/require-hooks/index.ts
  packages/yoshi-common/src/require-hooks/ts-node-register.ts
  packages/yoshi-common/src/utils/heuristics.ts
  packages/yoshi-common/src/utils/should-transpile-file.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-config/src/config.ts
  packages/yoshi-flow-legacy/config/jest-transformer.js
  packages/yoshi-flow-legacy/config/protractor.conf.js
  packages/yoshi-flow-legacy/config/test-setup.js
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-legacy/src/commands/build.js
  packages/yoshi-flow-legacy/src/commands/start.js
  packages/yoshi-helpers/package.json
  packages/yoshi-helpers/src/require-hooks/babel-register.ts
  packages/yoshi-helpers/src/utils.ts
  yarn.lock
Labels: PR: Bug Fix :bug:

#1781 fix eslint not finding any file
  packages/yoshi-flow-legacy/src/commands/lint.js
  packages/yoshi-flow-legacy/test/lint.spec.js
Labels: PR: Bug Fix :bug:

#1848 Reconfigure renovate with minor and patch updates
  renovate.json
Labels: PR: Internal :house:

#1849 aggregate two tests into one and improve the first to include the later
  packages/yoshi-flow-legacy/test/lint.spec.js
Labels: PR: Chore :construction_worker:

#1851 migration readme - babel config clarification
  docs/migration/version-4.md
Labels: PR: Docs :memo:

#1853 remove the renovate config in order to re-onboard
  renovate.json
Labels: PR: Chore :construction_worker:

#1812 Svelte SSR transform
  packages/yoshi-common/src/svelte-server-side-preprocess.ts
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: New Feature :rocket:

#1860 always generate stats on build for monorepo flow
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#1858 Use async attribute instead of defer for injected script tags
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#1862 Add new status checks for new test infra
  package.json
Labels: PR: Internal :house:

#1857 Update stale-bot config to extend time until stale and time until close
  .github/stale.yml
Labels: PR: Internal :house:

#1865 Fix a bug with regex lookbehind not supported in Node v8
  packages/yoshi-common/src/svelte-server-side-preprocess.ts
Labels: PR: Bug Fix :bug:

#1864 Always use Svelte as an external dependency in server bundle
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#1866 during create-yoshi-app:dev perform initial commit only on first time generation
  packages/create-yoshi-app/scripts/dev.js
Labels: PR: Internal :house:

#1869 [editor-flow] disconnect cli and bin file
  packages/yoshi-flow-editor/bin/yoshi-flow-editor.js
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-editor/src/cli.ts
  packages/yoshi-flow-editor/src/commands/build.ts
  packages/yoshi-flow-editor/src/commands/start.ts
Labels: PR: Internal :house:

#1871 add basic linting guidelines
  packages/eslint-config-yoshi-base/README.md
Labels: PR: Internal :house:

#1872 fix server template environment.ts
  packages/create-yoshi-app/templates/server/typescript/test/environment.ts
Labels: PR: Bug Fix :bug:

#1874 Lock file maintanance 👷‍♂️
  package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm-runtime/src/hooks/useExperiments.tsx
  yarn.lock
Labels: PR: Chore :construction_worker:

#1863 Clean old tests status checks
  package.json
Labels: PR: Internal :house:

#1877 Change npm scripts names
  package.json
  packages/create-yoshi-app/package.json
Labels: PR: Internal :house:

#1878 Fix a bug in notExternalModules regex patterns
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1852 Fix broken link
  website/versioned_docs/version-4.x/api/cli.md
Labels: PR: Docs :memo:, 📜 Documentation

#1880 add immutable true to svelte options
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#1881 Update integration tests timeout
  jest-setup.js
Labels: PR: Internal :house:

#1876 yarn upgrade 👷‍♀️
  yarn.lock
Labels: PR: Chore :construction_worker:

#1887 Improve release process - install website during publish.
  scripts/createVersion.js
Labels: PR: Internal :house:

#1883 Fix svelte-server-side-preprocess to report svelte filename
  packages/yoshi-common/src/svelte-server-side-preprocess.ts
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#1886 Add tests for `babel-preset-yoshi`
  test/javascript/features/babel-preset-yoshi/class-properties/class-properties.test.js
  test/javascript/features/babel-preset-yoshi/class-properties/src/component.js
  test/javascript/features/babel-preset-yoshi/decorators/decorators.test.js
  test/javascript/features/babel-preset-yoshi/decorators/src/component.js
Labels: PR: Internal :house:

#1889 Chore: remove redundant files
  scripts/utils/setupProject.js
  scripts/utils/testProject.js
Labels: PR: Internal :house:

#1892 Chore: align integration tests to use new infra
  test/javascript/features/babel-preset-yoshi/class-properties/class-properties.test.js
  test/javascript/features/babel-preset-yoshi/decorators/decorators.test.js
  test/javascript/features/entries/entries.test.js
  test/javascript/features/env-vars/env-vars.test.js
  test/javascript/features/externals/externals.test.js
  test/javascript/features/loaders/json/json-inclusion/json-inclusion.test.js
  test/typescript/features/entries/entries.test.js
  test/typescript/features/env-vars/env-vars.test.js
  test/typescript/features/externals/externals.test.js
  test/typescript/features/loaders/json/json-inclusion/json-inclusion.test.js
Labels: PR: Internal :house:

#1890 Prompt when running integration tests with publish locally
  test/globalSetup.js
Labels: PR: Internal :house:

#1898 Remove .npmrc
  .npmrc
Labels: PR: Internal :house:

#1901 configure renovate to work with wix registry
  renovate.json
Labels: PR: Internal :house:

#1885 jest-environment-yoshi-puppeteer`: detect network errors + add a message for missing cdn server
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/globalSetup.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/index.js
  test/javascript/features/request-errors/__tests__/request-errors.e2e.js
  test/javascript/features/request-errors/jest-yoshi.config.js
  test/javascript/features/request-errors/request-errors.test.js
  test/javascript/features/request-errors/src/component.js
  test/javascript/features/request-errors/src/index.ejs
  test/typescript/features/request-errors/__tests__/request-errors.e2e.tsx
  test/typescript/features/request-errors/jest-yoshi.config.js
  test/typescript/features/request-errors/request-errors.test.js
  test/typescript/features/request-errors/src/component.tsx
  test/typescript/features/request-errors/src/index.ejs
Labels: PR: Internal :house:

#1909 Add content hash to webworker output for experimental build html
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1908 Improve test performance
  test/fixtures/javascript/base-template/package.json
  test/fixtures/typescript/base-template/package.json
  test/javascript/features/entries/package.json
  test/javascript/features/externals/package.json
  test/javascript/features/hmr/hmr/package.json
  test/javascript/features/hmr/web-worker/package.json
  test/javascript/features/non-transpiled-externals/transpile-configured-external-javascript/package.json
  test/javascript/features/output/output-error-no-client-entry/package.json
  test/javascript/features/output/output-error-no-server-entry/package.json
  test/javascript/features/tree-shaking/package.json
  test/javascript/features/verify-dependencies/package.json
  test/javascript/features/web-worker/web-worker-externals/package.json
  test/javascript/features/web-worker/web-worker/package.json
  test/typescript/features/entries/package.json
  test/typescript/features/externals/package.json
  test/typescript/features/hmr/hmr/package.json
  test/typescript/features/non-transpiled-externals/transpile-configured-external-javascript/package.json
  test/typescript/features/non-transpiled-externals/transpile-configured-external-typescript/package.json
  test/typescript/features/output/output-error-no-client-entry/package.json
  test/typescript/features/output/output-error-no-server-entry/package.json
  test/typescript/features/tree-shaking/package.json
  test/typescript/features/verify-dependencies/package.json
  test/typescript/features/web-worker/web-worker-externals/package.json
  test/typescript/features/web-worker/web-worker/package.json
Labels: PR: Internal :house:

#1894 Transpile webworker importScripts into fetch and eval
  packages/yoshi-common/src/AsyncWebWorkerTarget/AsyncWebWorkerPlugin.ts
  packages/yoshi-common/src/AsyncWebWorkerTarget/AsyncWebWorkerTarget.ts
  packages/yoshi-common/src/AsyncWebWorkerTarget/WebWorkerMainTemplatePlugin.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: New Feature :rocket:

#1906 remove the restriction from mini-css-extract-plugin
  renovate.json
Labels: PR: Internal :house:
