Repository wix/yoshi, pull requests merged in 2020-07, with the labels that each got.

#2655 DOCS: Update migration-guide.md
  website/versioned_docs/version-4.x/migration-guide.md
Labels: PR: Docs :memo:

#2642 Jest connection error message
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/index.js
  test/typescript/features/jest-preset-errors/__tests__/simple.e2e.tsx
  test/typescript/features/jest-preset-errors/e2e.test.ts
  test/typescript/features/jest-preset-errors/jest-yoshi.config.js
  test/typescript/features/jest-preset-errors/src/component.tsx
Labels: PR: New Feature :rocket:

#2656 Update `migration-guide.md` (source)
  website/docs/migration-guide.md
Labels: PR: Docs :memo:

#2496 Add bm-flow migration guide
  website/docs/business-manager-flow/migration.md
  website/docs/business-manager-flow/overview.md
  website/docs/welcome.md
  website/flows.json
  website/sidebars.js
Labels: PR: Docs :memo:

#2623 Yoshi serverless tests
  packages/yoshi-common/src/templates/serverless/serverless.js
  packages/yoshi-helpers/src/utils.ts
  packages/yoshi-serverless/package.json
  packages/yoshi-serverless/src/index.ts
  packages/yoshi-serverless/src/render.ts
  test/fixtures/yoshi-serverless-typescript/base-template/environment.js
  test/fixtures/yoshi-serverless-typescript/base-template/index-dev.js
  test/fixtures/yoshi-serverless-typescript/base-template/package.json
  test/fixtures/yoshi-serverless-typescript/base-template/pom.xml
  test/fixtures/yoshi-serverless-typescript/base-template/src/client.tsx
  test/fixtures/yoshi-serverless-typescript/base-template/src/component.tsx
  test/fixtures/yoshi-serverless-typescript/base-template/src/templates/app.ejs
  test/fixtures/yoshi-serverless-typescript/base-template/tsconfig.json
  test/scripts.ts
  test/typescript/features/yoshi-server/api-client-serverless/api-client-serverless.test.ts
  test/typescript/features/yoshi-server/api-client-serverless/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/api-client-serverless/src/client.tsx
  test/typescript/features/yoshi-server/api-client-serverless/src/component.tsx
  test/typescript/features/yoshi-server/api-client-serverless/src/routes/app.ts
  test/typescript/features/yoshi-server/api-client-serverless/src/templates/app.ejs
  test/yoshi-publish/package.json
  yarn.lock
Labels: PR: Internal :house:

#2659 Add support for experimental Stylable loader under a flag (env var)
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: New Feature :rocket:

#2661 Bump bob-widget-services version
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/{each%flowData.components:name%each}/viewer.controller.ts
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/{%packagejson%}.json
  packages/yoshi-flow-editor/package.json
  yarn.lock
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2664 Fix multilingual for settings.
  packages/yoshi-flow-editor-runtime/src/i18next/index.ts
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2665 fix: requestfinished event -> check for response
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/index.js
Labels: PR: Bug Fix :bug:

#2653 Fix BM method call without `{ module, moduleParams }`
  packages/yoshi-flow-bm-runtime/src/createModule.ts
Labels: PR: Bug Fix :bug:

#2624 Add `legacyBundle` config option to pages & exported-components in BM Flow
  packages/yoshi-flow-bm/src/config/types.ts
  packages/yoshi-flow-bm/src/config/validConfig.ts
  packages/yoshi-flow-bm/src/constants.ts
  packages/yoshi-flow-bm/src/entries.ts
  packages/yoshi-flow-bm/src/exportedComponent.ts
  packages/yoshi-flow-bm/src/legacyExportedComponent.ts
  packages/yoshi-flow-bm/src/legacyPage.ts
  packages/yoshi-flow-bm/src/model.ts
  packages/yoshi-flow-bm/src/module.ts
  packages/yoshi-flow-bm/src/moduleConfig.ts
  packages/yoshi-flow-bm/src/page.ts
  packages/yoshi-flow-bm/src/scripts/build.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  website/versioned_docs/version-4.x/business-manager-flow.md
Labels: PR: New Feature :rocket:

#2667 Update stylable to v3.7.2
  packages/yoshi-stylable-dependencies/package.json
Labels: PR: Chore :construction_worker:

#2666 Update babel to v7.10.4
  packages/babel-plugin-transform-hmr-runtime/package.json
  packages/babel-preset-yoshi/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-server-tools/package.json
  packages/yoshi/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2672 Deprecated Legacy Decorators Support
  packages/babel-preset-yoshi/index.js
Labels: PR: New Feature :rocket:

#2669 use experimentalMonorepoPublish
  package.json
  scripts/customPublish.ts
Labels: PR: Internal :house:

#2668 Remove next docs and simplify working with the documentation
  scripts/createVersion.js
  website/docs/Testing.md
  website/docs/app-flow.md
  website/docs/business-manager-flow/migration.md
  website/docs/business-manager-flow/overview.md
  website/docs/create-yoshi-app.md
  website/docs/development/bundle-analyze.md
  website/docs/development/debugging.md
  website/docs/development/environment-variables.md
  website/docs/development/hmr.md
  website/docs/development/momentjs-optimization.md
  website/docs/development/split-chunks.md
  website/docs/dummy.txt
  website/docs/editor-flow/cli-API.md
  website/docs/editor-flow/dev-center-registration.md
  website/docs/editor-flow/getting-started.md
  website/docs/editor-flow/local-development.md
  website/docs/editor-flow/overview.md
  website/docs/editor-flow/platform-apps-support.md
  website/docs/editor-flow/runtime-api/flow-api.md
  website/docs/editor-flow/runtime-api/yoshi-flow-editor-runtime.md
  website/docs/editor-flow/structure-api/application.md
  website/docs/editor-flow/structure-api/component.md
  website/docs/editor-flow/structure-api/overview.md
  website/docs/editor-flow/testing.md
  website/docs/legacy-flow.md
  website/docs/library-flow/configuration.md
  website/docs/library-flow/migration-guide.md
  website/docs/library-flow/overview.md
  website/docs/migration-guide.md
  website/docs/node-api.md
  website/docs/styles-and-assets/assets.md
  website/docs/styles-and-assets/disable-css-modules.md
  website/docs/styles-and-assets/stylelint-setup.md
  website/docs/styles-and-assets/svg.md
  website/docs/templates.md
  website/docs/welcome.md
  website/docs/yoshi-config.md
  website/docs/yoshi-server/consuming-data-from-the-server.md
  website/docs/yoshi-server/custom-server.md
  website/docs/yoshi-server/exposing-route.md
  website/docs/yoshi-server/getting-started.md
  website/docs/yoshi-server/initializing-server-data.md
  website/docs/yoshi-server/middlewares.md
  website/docs/yoshi-server/react-binding.md
  website/docs/yoshi-server/testing.md
  website/sidebars.js
  website/src/pages/versions.js
Labels: PR: Docs :memo:

#2663 Add a BI logger support for editor flow
  packages/create-yoshi-app/templates/flow-editor/typescript/.application.json
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/helpers/flowAPI.mock.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.spec.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/config/bi.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-editor-runtime/src/EditorAppWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/FlowAPI.ts
  packages/yoshi-flow-editor-runtime/src/SettingsWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/WidgetWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/constants.ts
  packages/yoshi-flow-editor-runtime/src/external-types.ts
  packages/yoshi-flow-editor-runtime/src/generated/bi-logger-types.d.ts
  packages/yoshi-flow-editor-runtime/src/generated/bi-logger-types.ts
  packages/yoshi-flow-editor-runtime/src/react/BILogger/BILoggerContext.ts
  packages/yoshi-flow-editor-runtime/src/react/BILogger/BILoggerProvider.tsx
  packages/yoshi-flow-editor-runtime/src/react/BILogger/BILoggerRenderProp.tsx
  packages/yoshi-flow-editor-runtime/src/react/BILogger/useBILogger.ts
  packages/yoshi-flow-editor-runtime/src/test.ts
  packages/yoshi-flow-editor-runtime/src/test/BILogger/BILoggerProvider.tsx
  packages/yoshi-flow-editor-runtime/src/utils.ts
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-editor/postinstall.js
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/commands/build.ts
  packages/yoshi-flow-editor/src/commands/start.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/scripts/generate-bi-types.ts
  packages/yoshi-flow-editor/src/utils.ts
  packages/yoshi-flow-editor/src/wrappers/biLoggerTypes.ts
  packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/editorAppWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/settingsWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/BiLoggerTypes.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/ControllerEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/EditorAppEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/SettingsAppEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/WidgetViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/EditorAppEntryContent.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/EditorAppEntryContent.test.ts.snap
  website/versioned_docs/version-4.x/editor-flow/runtime-api/yoshi-flow-editor-runtime.md
  website/versioned_docs/version-4.x/editor-flow/structure-api/application.md
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2673 Experimentally support skipping type check in monorepo flow
  packages/yoshi-flow-monorepo/src/scripts/build.ts
Labels: PR: New Feature :rocket:

#2671 Yoshi Serverless: remove local setup
  packages/yoshi-serverless-testing/package.json
  packages/yoshi-serverless-testing/src/index.ts
  packages/yoshi-serverless-testing/tsconfig.json
  test/fixtures/yoshi-serverless-typescript/base-template/index-dev.js
Labels: PR: New Feature :rocket:

#2675 Prevent cases of editor flow app generation w/o components.
  packages/create-yoshi-app/src/dev-center-registration/getQuestions.ts
  packages/create-yoshi-app/src/dev-center-registration/runPrompt.ts
  packages/create-yoshi-app/src/extended-prompts.ts
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2676 Fix typescript errors in editor flow
  packages/yoshi-flow-editor-runtime/src/generated/bi-logger-types.d.ts
  packages/yoshi-flow-editor-runtime/src/generated/bi-logger-types.ts
  packages/yoshi-flow-editor/types.d.ts
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2677 Remove lodash from the widget
  packages/yoshi-flow-editor/src/buildEntires.ts
  packages/yoshi-flow-editor/src/commands/build.ts
  packages/yoshi-flow-editor/src/commands/start.ts
  packages/yoshi-flow-editor/src/server/templates/editorApp.vm
  packages/yoshi-flow-editor/src/server/templates/settingsApp.vm
  packages/yoshi-flow-editor/src/webpack.config.ts
Labels: PR: Polish :nail_care:, 🖼 Flow Editor

#2674 Add Sentry integration to BM Flow
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/src/createApp.ts
  packages/create-yoshi-app/src/templates.ts
  packages/create-yoshi-app/src/utils.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/.module.json
  packages/yoshi-flow-bm-runtime/src/ErrorBoundary.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/SentryProvider.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/withSentry.tsx
  packages/yoshi-flow-bm-runtime/src/sentry.tsx
  packages/yoshi-flow-bm/src/config/types.ts
  packages/yoshi-flow-bm/src/config/validConfig.ts
  packages/yoshi-flow-bm/src/exportedComponent.ts
  packages/yoshi-flow-bm/src/module.ts
  packages/yoshi-flow-bm/src/page.ts
  packages/yoshi-flow-bm/src/queries.ts
  website/versioned_docs/version-4.x/business-manager-flow/overview.md
  yarn.lock
Labels: PR: New Feature :rocket:

#2678 Add module lifecycle hooks (`init`, `config`) to BM Flow
  packages/yoshi-flow-bm-runtime/src/createModule.ts
  packages/yoshi-flow-bm-runtime/src/types.ts
  packages/yoshi-flow-bm/src/constants.ts
  packages/yoshi-flow-bm/src/model.ts
  packages/yoshi-flow-bm/src/module.ts
  website/versioned_docs/version-4.x/business-manager-flow/overview.md
  yarn.lock
Labels: PR: New Feature :rocket:, 💼 Flow BM

#2681 Create `.chunks.jsons` files per compilation
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: New Feature :rocket:

#2680 Refactor translations. Add it to editor script.
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/helpers/controllerConfig.mock.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/helpers/i18n.mock.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.spec.ts
  packages/yoshi-flow-editor-runtime/src/EditorAppWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/editorScript.ts
  packages/yoshi-flow-editor-runtime/src/flow-api/Base.ts
  packages/yoshi-flow-editor-runtime/src/flow-api/EditorScript.ts
  packages/yoshi-flow-editor-runtime/src/flow-api/ViewerScript.ts
  packages/yoshi-flow-editor-runtime/src/i18next/Translations.ts
  packages/yoshi-flow-editor-runtime/src/i18next/index.ts
  packages/yoshi-flow-editor-runtime/src/test.ts
  packages/yoshi-flow-editor-runtime/src/test/controller/FlowAPI.mock.ts
  packages/yoshi-flow-editor-runtime/src/test/controller/controllerConfig.mock.ts
  packages/yoshi-flow-editor-runtime/src/types.ts
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/src/buildEntires.ts
  packages/yoshi-flow-editor/src/commands/build.ts
  packages/yoshi-flow-editor/src/commands/start.ts
  packages/yoshi-flow-editor/src/wrappers/commonEditorScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonEditorScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonEditorScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonEditorScriptEntry.test.ts.snap
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
  website/versioned_docs/version-4.x/editor-flow/runtime-api/flow-api.md
  website/versioned_docs/version-4.x/editor-flow/runtime-api/yoshi-flow-editor-runtime.md
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2682 Yoshi Serverless - wait for GA
  packages/yoshi-server-tools/package.json
  packages/yoshi-server-tools/src/serverless-publish.ts
Labels: PR: New Feature :rocket:

#2684 Fix wallaby config for `*-setup` files
  packages/yoshi/config/wallaby-common.js
Labels: PR: Bug Fix :bug:

#2687 fix: templates counter constructor suites rename
  packages/create-yoshi-app/templates/flow-library/typescript/src/__tests__/counter.spec.ts
  packages/create-yoshi-app/templates/library/javascript/__tests__/counter.spec.js
  packages/create-yoshi-app/templates/library/typescript/__tests__/counter.spec.ts
Labels: PR: Bug Fix :bug:

#2683 fix(flow-app): add isAnalyze to web worker webpack config
  packages/yoshi-flow-app/src/scripts/build.ts
  packages/yoshi-flow-app/src/webpack.config.ts
Labels: PR: New Feature :rocket:

#2692 Added `YOSHI_PUBLIC_PATH` documentation
  website/versioned_docs/version-4.x/development/environment-variables.md
Labels: PR: Docs :memo:

#2690 Fix `generate-bi-types` call
  packages/yoshi-flow-editor/postinstall.js
  packages/yoshi-flow-editor/src/scripts/generate-bi-types.ts
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2694 reprint initial server logs
  packages/yoshi-common/src/dev-environment-logger.ts
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/server-process.ts
Labels: PR: Bug Fix :bug:

#2695 Yoshi Serverless: add `requireHttps` by default
  packages/yoshi-common/src/templates/serverless/serverless.js
Labels: PR: New Feature :rocket:

#2698 Yoshi Serverless: fix flaky test
  package.json
  test/scripts.ts
  test/typescript/features/yoshi-server/api-client-serverless/api-client-serverless.test.ts
  test/typescript/features/yoshi-server/serverless-api-error-message/serverless-api-error-message.test.ts
Labels: PR: Bug Fix :bug:

#2679 Add a `files` module "hook" in BM Flow
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm-runtime/src/createModule.tsx
  packages/yoshi-flow-bm-runtime/src/types.ts
  packages/yoshi-flow-bm/src/constants.ts
  packages/yoshi-flow-bm/src/model.ts
  packages/yoshi-flow-bm/src/module.ts
  website/versioned_docs/version-4.x/business-manager-flow/overview.md
  yarn.lock
Labels: PR: New Feature :rocket:, 💼 Flow BM

#2685 Add a `resolve` module "hook" in BM Flow
  packages/yoshi-flow-bm-runtime/src/createModule.tsx
  packages/yoshi-flow-bm-runtime/src/types.ts
  packages/yoshi-flow-bm/src/module.ts
  website/versioned_docs/version-4.x/business-manager-flow/overview.md
Labels: PR: New Feature :rocket:

#2700 Run fork-ts-checker-webpack-plugin only on client debug compilation
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#2691 Add `getSiteOwnerId`to settings e2e test mock
  packages/yoshi-flow-editor-runtime/src/wixPrivateMockPath.ts
Labels: PR: Bug Fix :bug:

#2693 Add BI Logger integration to BM Flow
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm-runtime/src/bi.tsx
  packages/yoshi-flow-bm-runtime/src/createModule.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/BILoggerProvider.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/useBILogger.ts
  packages/yoshi-flow-bm-runtime/src/hooks/withBILogger.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/withSentry.tsx
  packages/yoshi-flow-bm-runtime/src/index.ts
  packages/yoshi-flow-bm/.gitignore
  packages/yoshi-flow-bm/generated/biLogger.d.ts
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-bm/postinstall.js
  packages/yoshi-flow-bm/src/biLoggerDefinitions.ts
  packages/yoshi-flow-bm/src/config/types.ts
  packages/yoshi-flow-bm/src/config/validConfig.ts
  packages/yoshi-flow-bm/src/constants.ts
  packages/yoshi-flow-bm/src/module.ts
  packages/yoshi-flow-bm/src/page.ts
  packages/yoshi-flow-bm/src/queries.ts
  website/versioned_docs/version-4.x/business-manager-flow/overview.md
  yarn.lock
Labels: PR: New Feature :rocket:, 💼 Flow BM

#2712 Remove a comment which is no longer relevant
  website/versioned_docs/version-4.x/yoshi-config.md
Labels: PR: Docs :memo:

#2726 auto release
  CI_RELEASE.md
  CONTRIBUTING.md
  package.json
  scripts/release.ts
  yarn.lock
Labels: PR: Internal :house:, 🛠 Infrastructure

#2729 Fix BI integration for exported-components in BM flow
  packages/yoshi-flow-bm/src/component.ts
  packages/yoshi-flow-bm/src/exportedComponent.ts
  packages/yoshi-flow-bm/src/page.ts
Labels: PR: Bug Fix :bug:, 💼 Flow BM

#2703 Update babel monorepo
  packages/babel-plugin-transform-hmr-runtime/package.json
  packages/babel-preset-yoshi/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-server-tools/package.json
  packages/yoshi/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2710 Update dependency chrome-launcher to v0.13.4
  packages/create-yoshi-app/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2709 Update dependency autoprefixer to v9.8.5
  packages/yoshi-common/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2706 Update dependency @types/lodash to v4.14.157
  package.json
  packages/yoshi-flow-library/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-server-testing/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2704 Update dependency @types/babel__traverse to v7.0.13
  packages/yoshi-server-tools/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2705 Update dependency @types/express to v4.17.7
  packages/bootstrap-hot-loader/package.json
  packages/create-yoshi-app/package.json
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-server/package.json
  packages/yoshi-serverless/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2711 Update dependency eslint-plugin-import to v2.22.0
  package.json
  packages/yoshi-flow-legacy/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2713 Update dependency eslint-plugin-react to v7.20.3
  package.json
  packages/yoshi-flow-legacy/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2714 Update dependency fp-ts to v2.7.0
  packages/yoshi-server/package.json
  packages/yoshi-serverless/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2715 Update dependency graphql to v14.7.0
  packages/jest-yoshi-preset/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-legacy/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2717 Update dependency io-ts to v2.2.9
  packages/yoshi-server/package.json
  packages/yoshi-serverless/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2720 Update dependency petri-specs to v1.3.288
  packages/yoshi-common/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2721 Update dependency react-module-container to v1.0.2320
  packages/yoshi-flow-bm-runtime/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2722 Update dependency type-fest to v0.16.0
  packages/yoshi-server/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2718 Update dependency lodash to v4.17.19
  package.json
  packages/eslint-config-yoshi/package.json
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-library/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server-testing/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2716 Update dependency graphql-tag to v2.10.4
  packages/jest-yoshi-preset/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-legacy/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2741 Update dependency typescript to v3.9.7
  package.json
  packages/jest-yoshi-preset/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-helpers/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2743 Update stylable to v3.8.1
  package.json
  packages/yoshi-stylable-dependencies/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2699 Use the ci-build-info library
  package.json
  packages/create-yoshi-app/scripts/e2e.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/cdnProxy.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/globalSetup.js
  packages/yoshi-common/src/webpack-utils.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-legacy/config/protractor.conf.js
  packages/yoshi-flow-legacy/test/config.spec.js
  packages/yoshi-flow-legacy/test/test.spec.js
  packages/yoshi-flow-legacy/test/webpack-config.spec.js
  packages/yoshi-flow-monorepo/src/webpack.config.ts
  packages/yoshi-helpers/package.json
  packages/yoshi-helpers/src/queries.ts
  packages/yoshi-helpers/src/utils.ts
  packages/yoshi-server-tools/src/serverless-publish.ts
  packages/yoshi-serverless-testing/src/index.ts
  scripts/utils/constants.ts
  test-helpers/env-variables.js
  test-helpers/test-phases.js
  test/javascript/features/env-vars/env-vars.test.ts
  test/scripts.ts
  test/typescript/features/env-vars/env-vars.test.ts
  test/typescript/features/monorepo/basic.test.ts
  test/typescript/features/monorepo/serve.test.ts
  test/typescript/features/yoshi-server/api-client-serverless/api-client-serverless.test.ts
  test/typescript/features/yoshi-server/serverless-api-error-message/serverless-api-error-message.test.ts
  yarn.lock
Labels: PR: Internal :house:

#2754 Revert "Use the ci-build-info library"
  package.json
  packages/create-yoshi-app/scripts/e2e.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/cdnProxy.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/globalSetup.js
  packages/yoshi-common/src/webpack-utils.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-legacy/config/protractor.conf.js
  packages/yoshi-flow-legacy/test/config.spec.js
  packages/yoshi-flow-legacy/test/test.spec.js
  packages/yoshi-flow-legacy/test/webpack-config.spec.js
  packages/yoshi-flow-monorepo/src/webpack.config.ts
  packages/yoshi-helpers/package.json
  packages/yoshi-helpers/src/queries.ts
  packages/yoshi-helpers/src/utils.ts
  packages/yoshi-server-tools/src/serverless-publish.ts
  packages/yoshi-serverless-testing/src/index.ts
  scripts/utils/constants.ts
  test-helpers/env-variables.js
  test-helpers/test-phases.js
  test/javascript/features/env-vars/env-vars.test.ts
  test/scripts.ts
  test/typescript/features/env-vars/env-vars.test.ts
  test/typescript/features/monorepo/basic.test.ts
  test/typescript/features/monorepo/serve.test.ts
  test/typescript/features/yoshi-server/api-client-serverless/api-client-serverless.test.ts
  test/typescript/features/yoshi-server/serverless-api-error-message/serverless-api-error-message.test.ts
  yarn.lock
Labels: PR: Bug Fix :bug:

#2752 Yoshi Serverless: deploy to Yoshi Serverless sandbox
  packages/yoshi-server-tools/src/serverless-publish.ts
Labels: PR: New Feature :rocket:

#2702 Pin dependencies
  package.json
  packages/babel-plugin-transform-hmr-runtime/package.json
  packages/bootstrap-hot-loader/package.json
  packages/create-yoshi-app/package.json
  packages/eslint-config-yoshi/package.json
  packages/jest-yoshi-preset/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-library/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server-react/package.json
  packages/yoshi-server-tools/package.json
  packages/yoshi-server/package.json
  packages/yoshi-serverless/package.json
  packages/yoshi-template-intro/package.json
  website/package.json
  website/yarn.lock
  yarn.lock
Labels: PR: Chore :construction_worker:

#2728 require babel helpers instead of inlining them
  packages/babel-preset-yoshi/index.js
Labels: PR: New Feature :rocket:

#2740 Update dependency tempy to v0.6.0
  package.json
  packages/create-yoshi-app/package.json
  packages/yoshi-flow-legacy/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2763 Update dependency @sentry/webpack-plugin to v1.12.0
  packages/yoshi-flow-monorepo/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2756 Update dependency @types/webpack-bundle-analyzer to v3
  packages/yoshi-common/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2750 Update dependency @types/node-fetch to v2
  packages/yoshi-server-client/package.json
  packages/yoshi-serverless-client/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2755 Update dependency @types/semver to v7
  package.json
  packages/create-yoshi-app/package.json
  packages/yoshi-common/package.json
  packages/yoshi-helpers/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2759 Update dependency chokidar to v3.4.1
  package.json
  packages/create-yoshi-app/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-helpers/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2751 Update dependency wix-bi-logger-client to v0.0.790
  packages/yoshi-common/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2745 Update dependency @types/ejs to v3
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-server/package.json
  packages/yoshi-serverless/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2766 Revert "Update dependency wix-bi-logger-client (#2751)"
  packages/yoshi-common/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2747 Update dependency @types/fs-extra to v9
  package.json
  packages/create-yoshi-app/package.json
  packages/jest-yoshi-preset/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-library/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server-tools/package.json
  packages/yoshi-server/package.json
  packages/yoshi-serverless/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2757 Remove dependency build-url
  packages/yoshi-common/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2730 Add `@wix/wix-i18n-config` integration to BM flow
  packages/create-yoshi-app/templates/flow-bm/typescript/.module.json
  packages/create-yoshi-app/templates/flow-bm/typescript/__tests__/e2e/app.e2e.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/assets/locale/messages_de.json
  packages/create-yoshi-app/templates/flow-bm/typescript/src/assets/locale/messages_en.json
  packages/create-yoshi-app/templates/flow-bm/typescript/src/pages/index.scss
  packages/create-yoshi-app/templates/flow-bm/typescript/src/pages/index.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/translations/de.json
  packages/create-yoshi-app/templates/flow-bm/typescript/translations/en.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm-runtime/src/i18n.tsx
  packages/yoshi-flow-bm-runtime/src/index.ts
  packages/yoshi-flow-bm-runtime/src/wrapComponent.tsx
  packages/yoshi-flow-bm/src/component.ts
  packages/yoshi-flow-bm/src/config/normalize.ts
  packages/yoshi-flow-bm/src/config/types.ts
  packages/yoshi-flow-bm/src/config/validConfig.ts
  packages/yoshi-flow-bm/src/constants.ts
  packages/yoshi-flow-bm/src/queries.ts
  website/versioned_docs/version-4.x/business-manager-flow/overview.md
  yarn.lock
Labels: PR: New Feature :rocket:, 💼 Flow BM

#2761 Support stylable manifest plugin [EXPERIMENTAL_STYLABLE_LOADER]
  packages/yoshi-common/package.json
  packages/yoshi-common/src/@stylable/manifest-plugin.ts
  packages/yoshi-common/src/webpack.config.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2778 upgrade lerna-changelog 1.0.1
  package.json
  scripts/release.ts
  yarn.lock
Labels: PR: Bug Fix :bug:

#2777 Allow using separate controller bundles instead of single viewer script one.
  packages/yoshi-flow-editor-runtime/src/constants.ts
  packages/yoshi-flow-editor-runtime/src/controllerWrapper.ts
  packages/yoshi-flow-editor-runtime/src/flow-api/ViewerScript.ts
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/buildEntires.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/utils.ts
  packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/controllerWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/ControllerEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/WidgetViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2771 correctly provide the user email on build and start bi events
  packages/create-yoshi-app/src/telemetry.ts
  packages/yoshi-common/src/getWixEmail.ts
  packages/yoshi-common/src/telemetry.ts
Labels: PR: Internal :house:

#2785 Update nvmrc tests to match CYA and template versions
  __tests__/verifyNvmrc.test.ts
Labels: PR: Internal :house:

#2767 Update dependency jest-teamcity to v1.8.0
  package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-library/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2788 fixed a small bug with certificates on legacy cdn
  packages/yoshi-flow-legacy/src/tasks/cdn/index.js
Labels: PR: Bug Fix :bug:

#2786 Yoshi Serverless Client: temporary replace `isomorphic-unfetch`
  packages/yoshi-serverless-client/package.json
  packages/yoshi-serverless-client/src/index.ts
  packages/yoshi-serverless-client/src/isomorphic-unfetch/browser.js
  packages/yoshi-serverless-client/src/isomorphic-unfetch/index.js
  packages/yoshi-serverless-client/src/isomorphic-unfetch/package.json
  packages/yoshi-serverless-client/src/utils.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2794 Use full `pkgJson.name` as compilation name in Library Flow
  packages/yoshi-flow-library/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#2739 Add "App Loaded" inntegration to Flow BM
  packages/create-yoshi-app/templates/flow-bm/typescript/src/pages/index.tsx
  packages/yoshi-flow-bm-runtime/src/appLoaded.tsx
  packages/yoshi-flow-bm-runtime/src/componentInfo.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/ComponentInfoProvider.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/useAppLoaded.ts
  packages/yoshi-flow-bm-runtime/src/hooks/useComponentInfo.ts
  packages/yoshi-flow-bm-runtime/src/index.ts
  packages/yoshi-flow-bm/src/component.ts
  packages/yoshi-flow-bm/src/exportedComponent.ts
  packages/yoshi-flow-bm/src/page.ts
  website/versioned_docs/version-4.x/business-manager-flow/runtime-api.md
  website/versioned_docs/version-4.x/business-manager-flow/runtimes.md
  website/versioned_sidebars/version-4.x-sidebars.json
Labels: PR: New Feature :rocket:, 💼 Flow BM

#2795 upgrade ci-build-info to ^1.0.30
  package.json
  packages/yoshi-helpers/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2793 docs structure
  website/versioned_docs/version-4.x/editor-flow/runtime-api.md
  website/versioned_docs/version-4.x/editor-flow/structure-api/component.md
Labels: PR: Docs :memo:

#2791 Extend controller with flowAPI features.
  packages/yoshi-flow-editor-runtime/src/controllerWrapper.ts
  packages/yoshi-flow-editor-runtime/src/fetchExperiments.ts
  packages/yoshi-flow-editor-runtime/src/flow-api/Base.ts
  packages/yoshi-flow-editor-runtime/src/flow-api/ViewerScript.ts
  packages/yoshi-flow-editor-runtime/src/helpers/wrapUserController.ts
  packages/yoshi-flow-editor-runtime/src/i18next/Translations.ts
  packages/yoshi-flow-editor-runtime/src/test/controller/FlowAPI.mock.ts
  packages/yoshi-flow-editor-runtime/src/types.ts
  packages/yoshi-flow-editor-runtime/src/utils.ts
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/src/wrappers/controllerWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/ControllerEntry.ts
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2737 Bump react & react-dom for BM projects
  packages/create-yoshi-app/templates/business-manager-module/javascript/{%packagejson%}.json
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}.json
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}.json
  packages/yoshi-flow-bm-runtime/package.json
Labels: PR: Templates :building_construction:

#2801 Add `react-custom-scroll` to be transpiled for editor flow projects.
  packages/yoshi-flow-editor/src/yoshi.config.js
Labels: PR: Bug Fix :bug:, 🐛 Bug, 🖼 Flow Editor

#2764 Update dependency bi-logger-yoshi to v1.0.217
  packages/yoshi-common/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2769 Update dependency simple-git to v2.15.0
  packages/yoshi-server-tools/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2768 Update dependency react-module-container to v1.0.2327
  packages/yoshi-flow-bm-runtime/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2797 Upgrade docusaurus
  website/docusaurus.config.js
  website/package.json
  website/yarn.lock
Labels: PR: Docs :memo:

#2773 Update dependency clipboardy to v2
  packages/create-yoshi-app/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2772 Update dependency @types/npm-package-arg to v6
  packages/yoshi-flow-monorepo/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2770 Update dependency verdaccio to v4.8.0
  package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2798 Pin dependencies
  package.json
  packages/yoshi-common/package.json
  packages/yoshi-helpers/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2814 Fix ci-build-info monorepo support
  package.json
  packages/yoshi-helpers/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2789 restart server on r keypress
  packages/yoshi-common/src/dev-environment-logger.ts
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/server-process.ts
  packages/yoshi-common/src/user-actions-watcher.ts
  packages/yoshi-flow-editor/src/commands/dev-environment-logger.ts
Labels: PR: New Feature :rocket:

#2818 Fix default suspense in BM flow
  packages/yoshi-flow-bm-runtime/src/wrapComponent.tsx
Labels: PR: Chore :construction_worker:

#2821 Fix path for mobile css bundle
  packages/yoshi-flow-editor/src/server/templates/settingsApp.vm
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2813 Reorganize BM Flow docs
  website/versioned_docs/version-4.x/business-manager-flow/configuration.md
  website/versioned_docs/version-4.x/business-manager-flow/lifecycle-hooks.md
  website/versioned_docs/version-4.x/business-manager-flow/migration.md
  website/versioned_docs/version-4.x/business-manager-flow/overview.md
  website/versioned_docs/version-4.x/business-manager-flow/runtime-api.md
  website/versioned_sidebars/version-4.x-sidebars.json
Labels: PR: Docs :memo:, 💼 Flow BM

#2817 Update BUG_REPORT.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
Labels: PR: Chore :construction_worker:

#2790 publish website to janet from CI
  .travis.yml
  website/docusaurus.config.js
  website/janet.json
  website/package.json
  website/yarn.lock
Labels: PR: Docs :memo:

#2802 Algolia search bar eject
  website/dev-server-proxy-plugin.js
  website/docusaurus.config.js
  website/src/theme/SearchBar/index.js
  website/src/theme/SearchBar/styles.css
Labels: PR: Docs :memo:
