Repository wix/yoshi, pull requests merged in 2020-05, with the labels that each got.

#2320 Update devDependencies (weekly)
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-server-tools/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2279 Customize module topology through `.module.json`
  packages/create-yoshi-app/templates/flow-bm/typescript/src/pages/index.tsx
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm-runtime/src/external-types.d.ts
  packages/yoshi-flow-bm-runtime/src/hooks/ModuleProvider.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/TranslationProvider.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/useTranslate.tsx
  packages/yoshi-flow-bm-runtime/src/index.ts
  packages/yoshi-flow-bm-runtime/src/withBM.tsx
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-bm/src/config.ts
  packages/yoshi-flow-bm/src/config/index.ts
  packages/yoshi-flow-bm/src/config/normalize.ts
  packages/yoshi-flow-bm/src/config/types.ts
  packages/yoshi-flow-bm/src/config/validConfig.ts
  packages/yoshi-flow-bm/src/createFlowBMModel.ts
  packages/yoshi-flow-bm/src/renderModuleConfig.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2321 Yoshi server docs - getting started
  website/docs/yoshi-server/consuming-data-from-the-server.md
  website/docs/yoshi-server/exposing-route.md
  website/docs/yoshi-server/getting-started.md
  website/docs/yoshi-server/react-binding.md
  website/sidebars.js
Labels: PR: Docs :memo:

#2319 Update dependencies (weekly)
  packages/eslint-config-yoshi-base/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-server/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2324 Watch config files for flow-bm model changes
  packages/yoshi-flow-bm/src/config/index.ts
  packages/yoshi-flow-bm/src/constants.ts
  packages/yoshi-flow-bm/src/createFlowBMModel.ts
Labels: PR: New Feature :rocket:

#2318 Implement dev center wizard
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/src/TemplateModel.ts
  packages/create-yoshi-app/src/createApp.ts
  packages/create-yoshi-app/src/dev-center-registration/TemplateModel.ts
  packages/create-yoshi-app/src/dev-center-registration/appService.ts
  packages/create-yoshi-app/src/dev-center-registration/auth.ts
  packages/create-yoshi-app/src/dev-center-registration/defaultAnswers.ts
  packages/create-yoshi-app/src/dev-center-registration/extended-prompts.ts
  packages/create-yoshi-app/src/dev-center-registration/getQuestions.ts
  packages/create-yoshi-app/src/dev-center-registration/runPrompt.ts
  packages/create-yoshi-app/src/generateProject.ts
  packages/create-yoshi-app/src/getValuesMap.ts
  packages/create-yoshi-app/src/index.ts
  packages/create-yoshi-app/src/replaceTemplates.ts
  packages/create-yoshi-app/src/template-utils.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/.application.json
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/viewerApp.e2e.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/viewerScript.spec.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/dev/sites.js
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/.component.json
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/Settings.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/.component.json
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.e2e.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.global.scss
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.scss
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.spec.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/index.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.e2e.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.spec.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.st.css
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/index.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.spec.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/yoshi.config.js
  packages/yoshi-flow-editor-runtime/src/constants.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
  yarn.lock
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2305 Add template for platform apps
  packages/create-yoshi-app/src/templates.ts
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/.application.json
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/.editorconfig
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/.nvmrc
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/.{%gitignore%}
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/README.md
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/__tests__/viewerApp.e2e.ts
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/dev/sites.js
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/jest-yoshi.config.js
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/pom.xml
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/firstWidget/.component.json
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/firstWidget/Settings.tsx
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/firstWidget/editor.controller.ts
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/firstWidget/firstWidgetSettings.global.scss
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/firstWidget/viewer.controller.ts
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/editor.app.ts
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/editor/appAPI.ts
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/utils/editor.ts
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/viewer.app.ts
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/tsconfig.json
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/wallaby.js
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/yoshi.config.js
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/{%packagejson%}.json
  packages/yoshi-flow-editor-runtime/src/styles/wix-base-ui.global.scss
  packages/yoshi-flow-editor/types.d.ts
Labels: PR: Templates :building_construction:, 🖼 Flow Editor

#2322 Open Business-Manager (testkit) url on `yoshi-bm start`
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-bm/src/model.ts
  packages/yoshi-flow-bm/src/renderModule.ts
  packages/yoshi-flow-bm/src/renderModuleConfig.ts
  packages/yoshi-flow-bm/src/scripts/build.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2329 Yoshi server docs: testing
  website/docs/yoshi-server/testing.md
Labels: PR: Docs :memo:

#2326 Yoshi Server - Initialise server data
  website/docs/yoshi-server/initializing-server-data.md
  website/sidebars.js
Labels: PR: Docs :memo:

#2331 Remove JS project for editor flow and update template tests
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/templates/flow-editor/javascript/.application.json
  packages/create-yoshi-app/templates/flow-editor/javascript/.editorconfig
  packages/create-yoshi-app/templates/flow-editor/javascript/.nvmrc
  packages/create-yoshi-app/templates/flow-editor/javascript/.{%gitignore%}
  packages/create-yoshi-app/templates/flow-editor/javascript/README.md
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/e2e-setup.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/e2e-ssr/verify-ssr.ssr.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/editorApp.e2e.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/helpers/i18n.mock.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/jest-setup-ssr.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/settingsPanel.e2e.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/viewerApp.e2e.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/viewerScript.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/dev/sites.js
  packages/create-yoshi-app/templates/flow-editor/javascript/jest-ssr.config.js
  packages/create-yoshi-app/templates/flow-editor/javascript/jest-yoshi.config.js
  packages/create-yoshi-app/templates/flow-editor/javascript/pom.xml
  packages/create-yoshi-app/templates/flow-editor/javascript/src/assets/locales/messages_de.json
  packages/create-yoshi-app/templates/flow-editor/javascript/src/assets/locales/messages_en.json
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/.component.json
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Settings.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Settings/Settings.global.scss
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Settings/Settings.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Settings/Settings.scss
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Settings/Settings.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Widget.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Widget.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Widget.st.css
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/controller.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/controller.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/config/constants.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/config/i18n.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/viewer.app.js
  packages/create-yoshi-app/templates/flow-editor/javascript/velocity.data.json
  packages/create-yoshi-app/templates/flow-editor/javascript/velocity.private.data.json
  packages/create-yoshi-app/templates/flow-editor/javascript/yoshi.config.js
  packages/create-yoshi-app/templates/flow-editor/javascript/{%packagejson%}.json
Labels: PR: Templates :building_construction:, 🖼 Flow Editor

#2333 Use `data-hook` instead of `data-testid` in templates
  packages/create-yoshi-app/templates/business-manager-module/javascript/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/src/components/App/App.js
  packages/create-yoshi-app/templates/business-manager-module/typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/client/javascript/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/client/javascript/src/components/App/App.js
  packages/create-yoshi-app/templates/client/typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/client/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.spec.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.tsx
  packages/create-yoshi-app/templates/fullstack/javascript/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/fullstack/javascript/src/components/App/App.js
  packages/create-yoshi-app/templates/fullstack/typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/fullstack/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/out-of-iframe/javascript/__tests__/spec-setup.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/Settings/Settings.spec.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/Widget/Widget.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/__tests__/spec-setup.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Settings/Settings.spec.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/Widget.tsx
Labels: PR: Templates :building_construction:

#2332 Improve thunderbolt progress bar with showing all compilations
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/utils.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:, PR: New Feature :rocket:, ⚡️ Thunderbolt

#2336 Use single brackets for i18next interpolation in templates
  packages/create-yoshi-app/templates/client/javascript/src/components/__mocks__/i18n.js
  packages/create-yoshi-app/templates/client/javascript/src/i18n.js
  packages/create-yoshi-app/templates/client/typescript/src/components/__mocks__/i18n.ts
  packages/create-yoshi-app/templates/client/typescript/src/i18n.ts
  packages/create-yoshi-app/templates/fullstack/javascript/src/components/__mocks__/i18n.js
  packages/create-yoshi-app/templates/fullstack/javascript/src/i18n.js
  packages/create-yoshi-app/templates/fullstack/typescript/src/components/__mocks__/i18n.ts
  packages/create-yoshi-app/templates/fullstack/typescript/src/i18n.ts
  packages/create-yoshi-app/templates/out-of-iframe/javascript/__tests__/helpers/i18n.mock.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/config/i18n.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/__tests__/helpers/i18n.mock.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/config/i18n.ts
Labels: PR: Templates :building_construction:

#2330 Yoshi Server docs: custom server
  website/docs/yoshi-server/custom-server.md
Labels: PR: Docs :memo:

#2327 Yoshi Server Docs - middlwares
  packages/yoshi-server/src/index.ts
  packages/yoshi-server/src/runMiddleware.ts
  packages/yoshi-server/src/server.ts
  test/javascript/features/yoshi-server/route/src/routes/app.js
  test/javascript/features/yoshi-server/server-error/src/routes/app.js
  test/typescript/features/yoshi-server/route/src/routes/app.ts
  test/typescript/features/yoshi-server/server-error/src/routes/app.ts
  website/docs/yoshi-server/consuming-data-from-the-server.md
  website/docs/yoshi-server/exposing-route.md
  website/docs/yoshi-server/middlewares.md
Labels: PR: Docs :memo:, PR: New Feature :rocket:

#2340 Add content hash to Stylable files
  packages/yoshi-common/src/manifest-webpack-plugin.ts
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#2346 Add lodash to create yoshi app deps
  packages/create-yoshi-app/package.json
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2344 Do not show the progress bar in case there are many compilations
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
Labels: PR: Chore :construction_worker:, 🏘️ Monorepo

#2349 Include only monorepo packages in transpilation
  packages/yoshi-common/src/utils/should-transpile-file.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/scripts/start.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:, 🏘️ Monorepo

#2341 run webpackbar in basic mode in every ci environment
  packages/yoshi-common/package.json
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#2351 fix link to OOI docs
  website/versioned_docs/version-4.x/templates.md
Labels: PR: Docs :memo:, 📜 Documentation

#2337 [templates] set `esModuleInterop` for all typescript templates
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.tsx
  packages/create-yoshi-app/templates/flow-library/typescript/tsconfig.json
  packages/create-yoshi-app/templates/library/typescript/tsconfig.json
  packages/create-yoshi-app/templates/out-of-iframe/typescript/__tests__/helpers/i18n.mock.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Settings/Settings.spec.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Settings/Settings.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/Widget.spec.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Widget/Widget.tsx
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/config/i18n.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/tsconfig.json
  packages/create-yoshi-app/templates/server/typescript/test/environment.ts
  packages/create-yoshi-app/templates/server/typescript/tsconfig.json
Labels: PR: Templates :building_construction:

#2354 Verify that the `target` directory exists before writing the `server.log`
  packages/yoshi-common/src/server-process.ts
Labels: PR: Bug Fix :bug:

#2348 Prevent asking language for projects if only one is supported
  packages/create-yoshi-app/__tests__/TemplateModel.test.ts
  packages/create-yoshi-app/__tests__/createApp.test.ts
  packages/create-yoshi-app/__tests__/generateProject.test.ts
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/src/TemplateModel.ts
  packages/create-yoshi-app/src/createApp.ts
  packages/create-yoshi-app/src/dev-center-registration/getQuestions.ts
  packages/create-yoshi-app/src/getQuestions.ts
  packages/create-yoshi-app/src/runPrompt.ts
  packages/create-yoshi-app/src/templates.ts
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2361 Update devDependencies (weekly)
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-helpers/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2356 Make `react` a `peerDep` of `yoshi-flow-bm-runtime`
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}.json
  packages/yoshi-flow-bm-runtime/package.json
Labels: PR: Polish :nail_care:

#2358 Write module config file into `target`
  packages/create-yoshi-app/templates/flow-bm/typescript/dev/environment.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/dev/server.ts
  packages/yoshi-flow-bm/src/config/index.ts
  packages/yoshi-flow-bm/src/constants.ts
  packages/yoshi-flow-bm/src/model.ts
  packages/yoshi-flow-bm/src/renderModuleConfig.ts
Labels: PR: Polish :nail_care:

#2353 Yoshi Server: add HMR support for new files
  package.json
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-flow-app/src/scripts/start.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  packages/yoshi-flow-editor/src/commands/start.ts
  test/javascript/features/yoshi-server/hmr-new-api/hmr.test.ts
  test/javascript/features/yoshi-server/hmr-new-api/src/api/greeting.js
  test/javascript/features/yoshi-server/hmr-new-api/src/app.js
  test/javascript/features/yoshi-server/hmr-new-api/src/routes/dummy.js
  test/javascript/features/yoshi-server/hmr-new-route/hmr.test.ts
  test/javascript/features/yoshi-server/hmr-new-route/src/api/greeting.api.js
  test/javascript/features/yoshi-server/hmr-new-route/src/routes/app.js
  yarn.lock
Labels: PR: New Feature :rocket:

#2355 Split BM flow output bundles to selectively add deps
  packages/create-yoshi-app/templates/flow-bm/typescript/.module.json
  packages/create-yoshi-app/templates/flow-bm/typescript/src/pages/index.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}.json
  packages/yoshi-flow-bm-runtime/.npmignore
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm-runtime/src/createModule.ts
  packages/yoshi-flow-bm-runtime/src/experiments.tsx
  packages/yoshi-flow-bm-runtime/src/fedops.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/ExperimentsProvider.tsx
  packages/yoshi-flow-bm-runtime/src/hooks/useExperiments.tsx
  packages/yoshi-flow-bm-runtime/src/index.ts
  packages/yoshi-flow-bm-runtime/src/moduleParams.ts
  packages/yoshi-flow-bm-runtime/src/sentry.tsx
  packages/yoshi-flow-bm-runtime/src/withBM.tsx
  packages/yoshi-flow-bm-runtime/src/wrapComponent.tsx
  packages/yoshi-flow-bm-runtime/tsconfig.esm.json
  packages/yoshi-flow-bm-runtime/tsconfig.json
  packages/yoshi-flow-bm/src/config/normalize.ts
  packages/yoshi-flow-bm/src/config/types.ts
  packages/yoshi-flow-bm/src/config/validConfig.ts
  packages/yoshi-flow-bm/src/constants.ts
  packages/yoshi-flow-bm/src/model.ts
  packages/yoshi-flow-bm/src/queries.ts
  packages/yoshi-flow-bm/src/renderExportedComponent.ts
  packages/yoshi-flow-bm/src/renderModule.ts
  packages/yoshi-flow-bm/src/renderPage.ts
  scripts/build.ts
  yarn.lock
Labels: PR: Polish :nail_care:

#2364 Fix broken links in website
  website/docs/create-yoshi-app.md
  website/docs/editor-flow/overview.md
  website/docs/legacy-flow.md
  website/docs/migration-guide.md
  website/docs/welcome.md
  website/versioned_docs/version-3.x/api/cli.md
  website/versioned_docs/version-3.x/api/configuration.md
  website/versioned_docs/version-3.x/getting-started/create-app.md
  website/versioned_docs/version-4.x/create-yoshi-app.md
  website/versioned_docs/version-4.x/editor-flow/overview.md
  website/versioned_docs/version-4.x/legacy-flow.md
  website/versioned_docs/version-4.x/migration-guide.md
  website/versioned_docs/version-4.x/welcome.md
Labels: PR: Docs :memo:

#2372 Custom publish can now publish new packages to npm from the CI
  scripts/customPublish.ts
Labels: PR: Internal :house:, 🛠 Infrastructure

#2370 better error handling for webpack errors during build
  packages/yoshi-common/src/webpack-utils.ts
Labels: PR: Bug Fix :bug:

#2343 createVersion: Commit also when there are just untracked files
  scripts/createVersion.js
Labels: PR: Internal :house:, 🛠 Infrastructure

#2371 Exclude `mergeLonghand` plugin from cssnano optimizations
  packages/yoshi-common/package.json
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-legacy/test/build.spec.js
  yarn.lock
Labels: PR: Bug Fix :bug:, ⚡️ Thunderbolt

#2373 Yoshi Server: add a Business Manager default baseUrl
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-server-client/src/index.ts
  test/javascript/features/yoshi-server/api-client-server-react/src/client.js
  test/javascript/features/yoshi-server/bm-route/package.json
  test/javascript/features/yoshi-server/bm-route/src/client.js
  test/javascript/features/yoshi-server/bm-route/src/server.js
  test/typescript/features/yoshi-server/api-client-server-react/src/client.tsx
  test/typescript/features/yoshi-server/bm-route/package.json
  test/typescript/features/yoshi-server/bm-route/src/client.tsx
Labels: PR: New Feature :rocket:

#2282 Yoshi Server: update BM template
  .eslintrc
  packages/create-yoshi-app/templates/business-manager-module/javascript/Dockerfile
  packages/create-yoshi-app/templates/business-manager-module/javascript/__tests__/e2e/drivers/app.driver.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/dev/server.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/environment.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/index-dev.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/jest-yoshi.config.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/src/client.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/{%packagejson%}.json
  packages/create-yoshi-app/templates/business-manager-module/typescript/Dockerfile
  packages/create-yoshi-app/templates/business-manager-module/typescript/__tests__/e2e/drivers/app.driver.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/dev/server.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/environment.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/index-dev.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/jest-yoshi.config.js
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/client.tsx
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/test-types.d.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/tsconfig.json
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}.json
Labels: PR: New Feature :rocket:

#2342 Yoshi server Docs: add to sidebar
  website/docs/yoshi-server/getting-started.md
  website/docs/yoshi-server/middlewares.md
  website/docusaurus.config.js
  website/flows.json
  website/sidebars.js
  website/versioned_docs/version-4.x/yoshi-server/consuming-data-from-the-server.md
  website/versioned_docs/version-4.x/yoshi-server/custom-server.md
  website/versioned_docs/version-4.x/yoshi-server/exposing-route.md
  website/versioned_docs/version-4.x/yoshi-server/getting-started.md
  website/versioned_docs/version-4.x/yoshi-server/initializing-server-data.md
  website/versioned_docs/version-4.x/yoshi-server/middlewares.md
  website/versioned_docs/version-4.x/yoshi-server/react-binding.md
  website/versioned_docs/version-4.x/yoshi-server/testing.md
Labels: PR: Docs :memo:

#2376 Yoshi Server: remove the 'under development' message
  website/docs/yoshi-server/getting-started.md
Labels: PR: Docs :memo:

#2360 Update dependencies (weekly)
  packages/create-yoshi-app/package.json
  packages/eslint-config-yoshi-base/package.json
  packages/jest-yoshi-preset/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-library/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-server/package.json
  packages/yoshi-stylable-dependencies/package.json
  packages/yoshi-style-dependencies/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2380 Separate yoshi config docs into their own page
  website/docs/app-flow.md
  website/docs/legacy-flow.md
  website/docs/yoshi-config.md
  website/sidebars.js
Labels: PR: Docs :memo:

#2316 yoshi serve support for monorepo
  packages/yoshi-common/src/cdn.ts
  packages/yoshi-common/src/commands/serve.ts
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/server-process.ts
  packages/yoshi-common/src/utils/constants.ts
  packages/yoshi-config/src/config.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-config/src/validConfig.ts
  packages/yoshi-flow-app/src/scripts/start.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  packages/yoshi-flow-editor/src/commands/start.ts
  packages/yoshi-flow-legacy/src/commands/start.js
  packages/yoshi-flow-legacy/src/tasks/app-server/index.js
  packages/yoshi-flow-library/src/commands/test.ts
  packages/yoshi-flow-monorepo/serve.d.ts
  packages/yoshi-flow-monorepo/serve.js
  packages/yoshi-flow-monorepo/src/load-package-graph.ts
  packages/yoshi-flow-monorepo/src/scripts/start.ts
  packages/yoshi-flow-monorepo/src/serve.ts
  packages/yoshi-helpers/__tests__/server-start-file.test.ts
  packages/yoshi-helpers/src/server-start-file.ts
  target/server.log
  test/fixtures/monorepo-typescript/base-template/packages/app-b/index-dev.ts
  test/fixtures/monorepo-typescript/base-template/packages/app-b/package.json
  test/fixtures/monorepo-typescript/base-template/packages/app-b/src/component.tsx
  test/fixtures/monorepo-typescript/base-template/packages/app-b/src/index.ejs
  test/fixtures/monorepo-typescript/base-template/packages/app-b/src/server.tsx
  test/fixtures/monorepo-typescript/base-template/packages/app/index-dev.ts
  test/fixtures/monorepo-typescript/base-template/packages/app/src/component.tsx
  test/fixtures/monorepo-typescript/base-template/packages/app/src/server.tsx
  test/javascript/features/serve/http/serve.test.ts
  test/javascript/features/serve/monorepo/monorepo.test.ts
  test/scripts.ts
  test/typescript/features/monorepo/basic.test.ts
  test/typescript/features/monorepo/serve.test.ts
  test/typescript/features/serve/http/serve.test.ts
  test/typescript/features/serve/monorepo/monorepo.test.ts
  website/docs/node-api.md
Labels: PR: New Feature :rocket:

#2374 Fix yoshi-flow-bm-runtime ESM build and root exports
  packages/yoshi-flow-bm-runtime/src/moduleParams.ts
  packages/yoshi-flow-bm-runtime/tsconfig.esm.json
Labels: PR: Bug Fix :bug:

#2381 Yoshi Server: fix context type
  packages/yoshi-server/src/types.ts
Labels: PR: New Feature :rocket:

#2382 Yoshi Server: fix docs
  website/docs/yoshi-server/getting-started.md
  website/versioned_docs/version-4.x/yoshi-server/consuming-data-from-the-server.md
  website/versioned_docs/version-4.x/yoshi-server/getting-started.md
Labels: PR: Docs :memo:

#2335 Allow configuring serverExternals
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-config/src/config.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-config/src/validConfig.ts
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: New Feature :rocket:, ⚡️ Thunderbolt

#2377 Fix BM template
  packages/create-yoshi-app/templates/business-manager-module/javascript/environment.js
  packages/create-yoshi-app/templates/business-manager-module/typescript/environment.js
Labels: PR: Bug Fix :bug:

#2384 Integrate sled to yoshi flow editor ooi template
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/templates/flow-editor/typescript/sled/config.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/sled/sled.json
  packages/create-yoshi-app/templates/flow-editor/typescript/sled/ssr/CommonViewerDriver.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/sled/ssr/{each%flowData.components:name%each}/{%name%}.e2e.driver.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/sled/ssr/{each%flowData.components:name%each}/{%name%}.e2e.spec.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}.json
Labels: PR: Templates :building_construction:, 🖼 Flow Editor

#2357 Add platform app studio component to be generated via wizard and generate editor builder automatically
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/scripts/dev.js
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/scripts/runE2E.js
  packages/create-yoshi-app/src/TemplateModel.ts
  packages/create-yoshi-app/src/createApp.ts
  packages/create-yoshi-app/src/dev-center-registration/defaultAnswers.ts
  packages/create-yoshi-app/src/dev-center-registration/getDefaultAnswers.ts
  packages/create-yoshi-app/src/dev-center-registration/getQuestions.ts
  packages/create-yoshi-app/src/dev-center-registration/runPrompt.ts
  packages/create-yoshi-app/src/generateProject.ts
  packages/create-yoshi-app/src/getQuestions.ts
  packages/create-yoshi-app/src/templates.ts
  packages/create-yoshi-app/src/utils.ts
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/.application.json
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/firstWidget/.component.json
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/{each%flowData.components:name%each}/.component.json
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/{each%flowData.components:name%each}/Settings.global.scss
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/{each%flowData.components:name%each}/Settings.tsx
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/{each%flowData.components:name%each}/editor.controller.ts
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/{each%flowData.components:name%each}/viewer.controller.e2e.ts
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/{each%flowData.components:name%each}/viewer.controller.ts
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/editor.app.ts
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/{%packagejson%}.json
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-editor/src/wrappers/commonEditorScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonEditorScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonEditorScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonEditorScriptEntry.test.ts.snap
  yarn.lock
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2386 Fix website publishing on master using travis
  website/yarn.lock
Labels: PR: Internal :house:

#2389 Upload serve.js & serve.d.ts files to npm
  packages/yoshi-flow-monorepo/package.json
Labels: PR: Bug Fix :bug:, 🏘️ Monorepo

#2388 Remove `yoshi server` from being a planet on the website (Flow)
  website/flows.json
Labels: PR: Docs :memo:

#2379 fix 'a different process is already running on port 3200' error when root folder has whitespace
  packages/yoshi-helpers/src/utils.ts
Labels: PR: Bug Fix :bug:

#2391 Skip a highly flaky stylable ssr test
  test/typescript/features/stylable/ssr/ssr-st-css.test.ts
Labels: PR: Internal :house:

#2385 Remove the generic get started from the readme, and update tagline
  README.md
Labels: PR: Docs :memo:

#2352 Add a unique chunkCallbackName according to package name
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#2393 Hotfix for editor script related to default export.
  packages/yoshi-flow-editor/src/wrappers/templates/CommonEditorScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonEditorScriptEntry.test.ts.snap
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2394 Update to typescript 3.9.2
  .gitignore
  .vscode/settings.json
  package.json
  packages/create-yoshi-app/src/dev-center-registration/getQuestions.ts
  packages/yoshi-flow-editor/src/webpack.config.ts
  yarn.lock
Labels: PR: Internal :house:

#2395 add a workflow for deploying the website from github actions
  .github/workflows/deploy-website.yml
Labels: PR: Internal :house:

#2367 Editor flow docs
  website/docs/editor-flow/cli-API.md
  website/docs/editor-flow/dev-center-registration.md
  website/docs/editor-flow/editor-and-settings-apps.md
  website/docs/editor-flow/getting-started.md
  website/docs/editor-flow/local-development.md
  website/docs/editor-flow/migration-guide.md
  website/docs/editor-flow/overview.md
  website/docs/editor-flow/runtime-API.md
  website/docs/editor-flow/structure-API.md
  website/docs/editor-flow/testing.md
  website/sidebars.js
  website/versioned_docs/version-4.x/editor-flow/cli-API.md
  website/versioned_docs/version-4.x/editor-flow/dev-center-registration.md
  website/versioned_docs/version-4.x/editor-flow/editor-and-settings-apps.md
  website/versioned_docs/version-4.x/editor-flow/getting-started.md
  website/versioned_docs/version-4.x/editor-flow/local-development.md
  website/versioned_docs/version-4.x/editor-flow/migration-guide.md
  website/versioned_docs/version-4.x/editor-flow/overview.md
  website/versioned_docs/version-4.x/editor-flow/runtime-API.md
  website/versioned_docs/version-4.x/editor-flow/structure-API.md
  website/versioned_docs/version-4.x/editor-flow/testing.md
  website/versioned_sidebars/version-4.x-sidebars.json
Labels: PR: Docs :memo:, 📜 Documentation

#2397 Fix the website's particles
  website/src/pages/Universe/space.module.css
Labels: PR: Docs :memo:

#2400 Use absolute URLs for CSS assets in Thunderbolt and Elements
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#2398 Yoshi Server, BM generator: run testkit as fork
  packages/create-yoshi-app/templates/business-manager-module/javascript/environment.js
  packages/create-yoshi-app/templates/business-manager-module/typescript/environment.js
Labels: PR: New Feature :rocket:

#2399 Update yoshi server testing with new api
  packages/yoshi-server-testing/src/index.ts
  test/javascript/features/yoshi-server/api-client-server-react/src/components/App/App.spec.js
  test/javascript/features/yoshi-server/api-client-server/src/component.spec.js
  test/javascript/features/yoshi-server/custom-server/src/component.spec.jsx
  test/typescript/features/yoshi-server/api-client-server-react/src/components/App/App.spec.tsx
  test/typescript/features/yoshi-server/api-client-server/src/component.spec.tsx
  test/typescript/features/yoshi-server/custom-server/src/component.spec.tsx
  website/docs/yoshi-server/testing.md
  website/versioned_docs/version-4.x/yoshi-server/testing.md
Labels: PR: New Feature :rocket:

#2401 Documentation website improvements 📒 🧽 💫
  packages/babel-preset-yoshi/README.md
  website/docs/Testing.md
  website/docs/app-flow.md
  website/docs/development/bundle-analyze.md
  website/docs/development/debugging.md
  website/docs/development/hmr.md
  website/docs/development/momentjs-optimization.md
  website/docs/development/split-chunks.md
  website/docs/legacy-flow.md
  website/docs/legacy-guides/ab-translate.md
  website/docs/legacy-guides/assets.md
  website/docs/legacy-guides/enzyme-support.md
  website/docs/legacy-guides/export-es-modules.md
  website/docs/legacy-guides/managing-dependencies.md
  website/docs/library-flow.md
  website/docs/styles-and-assets/disable-css-modules.md
  website/docs/styles-and-assets/stylelint-setup.md
  website/docs/styles-and-assets/svg.md
  website/docs/welcome.md
  website/docs/yoshi-config.md
  website/docusaurus.config.js
  website/sidebars.js
Labels: PR: Docs :memo:

#2402 Add sentry support for editor flow
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/src/TemplateModel.ts
  packages/create-yoshi-app/src/createApp.ts
  packages/create-yoshi-app/src/dev-center-registration/getQuestions.ts
  packages/create-yoshi-app/src/dev-center-registration/runPrompt.ts
  packages/create-yoshi-app/src/extended-prompts.ts
  packages/create-yoshi-app/src/external-types.d.ts
  packages/create-yoshi-app/src/getQuestions.ts
  packages/create-yoshi-app/src/getValuesMap.ts
  packages/create-yoshi-app/src/runPrompt.ts
  packages/create-yoshi-app/src/sentry-registration/TemplateModel.ts
  packages/create-yoshi-app/src/sentry-registration/addSentry.ts
  packages/create-yoshi-app/src/sentry-registration/getQuestions.ts
  packages/create-yoshi-app/src/sentry-registration/runPrompt.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/.application.json
  packages/create-yoshi-app/templates/flow-editor/typescript/dev/sites.js
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.e2e.ts
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-editor-runtime/src/EditorAppWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/SettingsWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/WidgetWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/constants.ts
  packages/yoshi-flow-editor-runtime/src/react/ErrorBoundary.tsx
  packages/yoshi-flow-editor-runtime/src/utils.ts
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/commands/htmlGenerator.ts
  packages/yoshi-flow-editor/src/external-types.d.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/server/server.ts
  packages/yoshi-flow-editor/src/server/templates/editorApp.vm
  packages/yoshi-flow-editor/src/server/templates/settingsApp.vm
  packages/yoshi-flow-editor/src/server/vm.ts
  packages/yoshi-flow-editor/src/utils.ts
  packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/componentWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/editorAppWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/settingsWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/ComponentWidgetEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/EditorAppEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/SettingsAppEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
  yarn.lock
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2408 Add fedops logger to editor-flow template
  packages/create-yoshi-app/src/template-utils.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/fedops.json
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.spec.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.ts
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2413 Yoshi Server - change client-server api
  packages/yoshi-server-client/src/index.ts
  packages/yoshi-server-react/src/hooks.ts
  packages/yoshi-server-testing/src/index.ts
  test/javascript/features/yoshi-server/api-client-server/src/component.js
  test/javascript/features/yoshi-server/api-error/__tests__/server.e2e.js
  test/javascript/features/yoshi-server/api-not-a-json-error/__tests__/server.e2e.js
  test/javascript/features/yoshi-server/api-server-server/src/routes/app.js
  test/javascript/features/yoshi-server/bm-route/src/component.js
  test/javascript/features/yoshi-server/config/src/component.js
  test/javascript/features/yoshi-server/csrf/src/component.js
  test/javascript/features/yoshi-server/custom-server/src/component.js
  test/javascript/features/yoshi-server/hmr-new-api/src/app.js
  test/javascript/features/yoshi-server/hmr-new-route/src/routes/app.js
  test/javascript/features/yoshi-server/hmr/src/routes/app.js
  test/javascript/features/yoshi-server/init-server/src/component.js
  test/javascript/features/yoshi-server/return-values/return-a-string/src/routes/app.js
  test/typescript/features/yoshi-server/api-client-server/src/component.tsx
  test/typescript/features/yoshi-server/api-error/__tests__/server.e2e.ts
  test/typescript/features/yoshi-server/api-not-a-json-error/__tests__/server.e2e.ts
  test/typescript/features/yoshi-server/api-server-server/src/routes/app.ts
  test/typescript/features/yoshi-server/bm-route/src/component.tsx
  test/typescript/features/yoshi-server/config/src/component.tsx
  test/typescript/features/yoshi-server/csrf/src/component.tsx
  test/typescript/features/yoshi-server/custom-server/src/component.tsx
  test/typescript/features/yoshi-server/init-server/src/component.tsx
  test/typescript/features/yoshi-server/return-values/return-a-string/src/routes/app.ts
  website/docs/yoshi-server/consuming-data-from-the-server.md
  website/docs/yoshi-server/getting-started.md
  website/docs/yoshi-server/testing.md
  website/versioned_docs/version-4.x/yoshi-server/consuming-data-from-the-server.md
  website/versioned_docs/version-4.x/yoshi-server/getting-started.md
  website/versioned_docs/version-4.x/yoshi-server/testing.md
Labels: PR: Breaking Change :boom:, PR: New Feature :rocket:

#2406 Add example BILogger to Editor flow template
  packages/create-yoshi-app/src/dev-center-registration/getQuestions.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/config/bi.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/types/external-modules.d.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}.json
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/components/Settings/Settings.tsx
  packages/yoshi-flow-editor-runtime/src/index.ts
  packages/yoshi-flow-editor-runtime/src/react/BILogger/BILoggerContext.ts
  packages/yoshi-flow-editor-runtime/src/react/BILogger/BILoggerProvider.tsx
  packages/yoshi-flow-editor-runtime/src/react/BILogger/BILoggerRenderProp.tsx
  packages/yoshi-flow-editor-runtime/src/react/BILogger/useBILogger.ts
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2414 Build site-assets Webpack config instead of client in monorepo start script
  packages/yoshi-flow-monorepo/src/scripts/start.ts
Labels: PR: Bug Fix :bug:, ⚡️ Thunderbolt

#2421 Library Flow: fix typescript and react babel bug
  packages/yoshi-common/package.json
  packages/yoshi-common/src/typescript/run-babel.ts
  yarn.lock
Labels: PR: Bug Fix :bug:

#2422 Update stylable to new version
  packages/yoshi-stylable-dependencies/package.json
Labels: PR: Chore :construction_worker:

#2411 Skip renovate updates for react in flow-bm
  renovate.json
Labels: PR: Chore :construction_worker:

#2423 Move babel & stylable into own renovate groups
  renovate.json
Labels: PR: Chore :construction_worker:

#2363 Migrate BM templates to use `wix-i18n-config`
  packages/create-yoshi-app/templates/business-manager-module/javascript/app-config-templates/module_{%PROJECT_NAME%}.json
  packages/create-yoshi-app/templates/business-manager-module/javascript/src/assets/locale/messages_de.json
  packages/create-yoshi-app/templates/business-manager-module/javascript/src/assets/locale/messages_en.json
  packages/create-yoshi-app/templates/business-manager-module/javascript/src/client.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/src/components/App/App.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/src/components/App/App.spec.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/src/components/__mocks__/i18n.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/src/i18n.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/{%packagejson%}.json
  packages/create-yoshi-app/templates/business-manager-module/typescript/app-config-templates/module_{%PROJECT_NAME%}.json
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/assets/locale/messages_de.json
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/assets/locale/messages_en.json
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/client.tsx
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/components/App/App.spec.tsx
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/components/__mocks__/i18n.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/config.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/i18n.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}.json
Labels: PR: Templates :building_construction:

#2426 Fix dev.js script to support template loops
  packages/create-yoshi-app/scripts/dev.js
  packages/create-yoshi-app/src/generateProject.ts
  packages/create-yoshi-app/src/index.ts
Labels: PR: Bug Fix :bug:, PR: Internal :house:, 🐛 Bug

#2425 Create temporary pkg.json for sentry configuration
  packages/create-yoshi-app/src/sentry-registration/addSentry.ts
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2419 Use a different runtime id in case we use stylable 3
  packages/yoshi-common/src/@stylable/webpack-plugin.ts
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#2428 Don't load server HMR entry if Suricate is used
  packages/yoshi-common/src/dev-environment.ts
Labels: PR: Bug Fix :bug:

#2409 Update dependencies (weekly)
  packages/babel-preset-yoshi/package.json
  packages/eslint-config-yoshi-base/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server-testing/package.json
  packages/yoshi-server-tools/package.json
  packages/yoshi-server/package.json
  packages/yoshi-stylable-dependencies/package.json
  packages/yoshi/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2424 Update experiments usage for editor flow.
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/viewer.app.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/.application.json
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/helpers/experiments.mock.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/helpers/fedops.mock.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.spec.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/config/constants.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/viewer.app.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-editor-runtime/src/EditorAppWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/constants.ts
  packages/yoshi-flow-editor-runtime/src/fetchExperiments.ts
  packages/yoshi-flow-editor-runtime/src/fetchFrameworkData.ts
  packages/yoshi-flow-editor-runtime/src/types.ts
  packages/yoshi-flow-editor-runtime/src/utils.ts
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/editorAppWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/EditorAppEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
  website/docs/editor-flow/platform-apps-support.md
  website/docs/editor-flow/structure-API.md
  website/versioned_docs/version-4.x/editor-flow/platform-apps-support.md
  website/versioned_docs/version-4.x/editor-flow/structure-API.md
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2434 allow to always override SURICATE_TUNNEL_ID
  packages/yoshi-common/src/utils/suricate.ts
Labels: PR: Bug Fix :bug:

#2410 Update devDependencies (weekly)
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-legacy/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2431 Update docs on shipping a `.css` bundle in library-flow
  website/docs/library-flow.md
Labels: PR: Docs :memo:

#2427 Prevent running template tests twice for single-language templates
  packages/create-yoshi-app/scripts/e2e.js
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2435 Yoshi Server: update docs to use Ambassador
  website/docs/yoshi-server/consuming-data-from-the-server.md
  website/docs/yoshi-server/getting-started.md
Labels: PR: Docs :memo:

#2436 Simplify the cdn module and add compression
  packages/yoshi-common/package.json
  packages/yoshi-common/src/cdn.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2439 Ignore snapshot files when copying assets in monorepo flow
  packages/yoshi-flow-monorepo/src/build.ts
Labels: PR: Bug Fix :bug:

#2443 Type `serve.d.ts` correctly
  packages/yoshi-flow-monorepo/serve.d.ts
Labels: PR: Bug Fix :bug:

#2444 Adjust create new editor flow app instructions in docs
  website/versioned_docs/version-4.x/editor-flow/getting-started.md
Labels: PR: Docs :memo:

#2447 Hotfixes for editor script and controller flow options
  packages/yoshi-flow-editor-runtime/src/FlowAPI.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonEditorScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonEditorScriptEntry.test.ts.snap
Labels: PR: Bug Fix :bug:, 🐛 Bug, 🖼 Flow Editor

#2446 fix umdNamedDefine config property
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
  website/docs/yoshi-config.md
Labels: PR: Bug Fix :bug:

#2441 Update dependencies (weekly)
  packages/yoshi-common/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-server-testing/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2449 Pass `dataCallback` to editor sentry
  packages/yoshi-flow-editor-runtime/src/FlowAPI.ts
  packages/yoshi-flow-editor-runtime/src/utils.ts
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2442 Update devDependencies (weekly)
  package.json
  packages/create-yoshi-app/package.json
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-helpers/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2452 Use npm lint script for lint-staged in flow-library template
  packages/create-yoshi-app/templates/flow-library/typescript/{%packagejson%}.json
Labels: PR: Templates :building_construction:

#2455 Update dependencies (weekly)
  packages/yoshi-common/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-library/package.json
  packages/yoshi-server/package.json
  packages/yoshi-stylable-dependencies/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2450 Yoshi Server: fix request/response types
  packages/yoshi-server/package.json
  packages/yoshi-server/src/types.ts
  test/typescript/features/yoshi-server/api-client-server/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/api-client-server/src/routes/app.ts
  test/typescript/features/yoshi-server/api-client-server/src/templates/app.ejs
Labels: PR: New Feature :rocket:

#2270 Lock file maintenance
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-library/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server-react/package.json
  packages/yoshi-server-tools/package.json
  packages/yoshi-server/src/bo-auth.ts
  packages/yoshi-server/src/require-login.ts
  test/yoshi-publish/package.json
  website/yarn.lock
  yarn.lock
Labels: PR: Chore :construction_worker:

#2453 [docs] adding docs for assets.md
  website/docs/styles-and-assets/assets.md
  website/sidebars.js
Labels: PR: Docs :memo:

#2458 Start BM loader during first render
  packages/create-yoshi-app/templates/business-manager-module/javascript/src/client.js
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/client.tsx
Labels: PR: Templates :building_construction:

#2459 Use public npm registry in website
  website/.yarnrc
  website/yarn.lock
Labels: PR: Chore :construction_worker:

#2454 Fix editor script for bob apps.
  packages/yoshi-flow-editor/src/wrappers/templates/CommonEditorScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonEditorScriptEntry.test.ts.snap
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2463 Allow overriding the module bundle name
  packages/yoshi-flow-bm/src/config/normalize.ts
  packages/yoshi-flow-bm/src/config/types.ts
  packages/yoshi-flow-bm/src/config/validConfig.ts
  packages/yoshi-flow-bm/src/renderModule.ts
  packages/yoshi-flow-bm/src/scripts/build.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  website/docs/business-manager-flow.md
Labels: PR: New Feature :rocket:

#2466 Add correct types version to flow-bm's comsmiconfig
  packages/yoshi-flow-bm/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2462 Run Suricate with cache enabled and update it between compilations
  packages/yoshi-common/src/utils/suricate.ts
  packages/yoshi-common/src/webpack-dev-server.ts
Labels: PR: Polish :nail_care:

#2470 Update js-sdk; Update iframe-bi-logger
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}.json
  packages/yoshi-flow-editor-runtime/src/constants.ts
Labels: PR: Polish :nail_care:, 🖼 Flow Editor

#2471 Allow initAppForPage to return a data to use it in controller
  packages/yoshi-flow-editor-runtime/src/EditorAppWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/ControllerEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
  website/docs/editor-flow/platform-apps-support.md
  website/docs/editor-flow/structure-api/application.md
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2472 Site Assets web compilation for running site-assets code in the browser
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/print-build-results.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/scripts/start.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: New Feature :rocket:, ⚡️ Thunderbolt

#2445 Yoshi Server: error toast message
  packages/yoshi-common/src/webpack-utils.ts
  packages/yoshi-server-client/package.json
  packages/yoshi-server-client/src/external-types.d.ts
  packages/yoshi-server-client/src/index.ts
  packages/yoshi-server-client/src/utils.ts
  packages/yoshi-server-client/tsconfig.json
  packages/yoshi-server/package.json
  packages/yoshi-server/src/routes/launchEditor.ts
  test/javascript/features/yoshi-server/api-error-message/api-client-server.test.ts
  test/javascript/features/yoshi-server/api-error-message/src/api/greeting.api.js
  test/javascript/features/yoshi-server/api-error-message/src/client.js
  test/javascript/features/yoshi-server/api-error-message/src/component.js
  test/javascript/features/yoshi-server/api-error-message/src/routes/app.js
  test/javascript/features/yoshi-server/api-error-message/src/templates/app.ejs
  test/typescript/features/yoshi-server/api-error-message/api-client-server.test.ts
  test/typescript/features/yoshi-server/api-error-message/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/api-error-message/src/client.tsx
  test/typescript/features/yoshi-server/api-error-message/src/component.tsx
  test/typescript/features/yoshi-server/api-error-message/src/routes/app.ts
  test/typescript/features/yoshi-server/api-error-message/src/templates/app.ejs
  yarn.lock
Labels: PR: New Feature :rocket:

#2465 Yoshi Server: copy Dockerfile
  packages/yoshi-common/src/copy-docker.ts
  packages/yoshi-common/src/templates/Dockerfile
  packages/yoshi-common/src/utils/template-utils.ts
  packages/yoshi-config/src/paths.ts
  packages/yoshi-flow-app/src/scripts/build.ts
  packages/yoshi-flow-bm/src/scripts/build.ts
  packages/yoshi-flow-editor/src/commands/build.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  test/javascript/features/yoshi-server/create-docker/create-docker.test.ts
  test/javascript/features/yoshi-server/create-docker/package.json
  test/typescript/features/yoshi-server/create-docker/create-docker.test.ts
  test/typescript/features/yoshi-server/create-docker/package.json
Labels: PR: New Feature :rocket:

#2461 Lock file maintenance
  website/yarn.lock
  yarn.lock
Labels: PR: Chore :construction_worker:

#2475 await for initAppForPage result.
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
Labels: PR: Bug Fix :bug:, 🖼 Flow Editor

#2473 Remove `cssBaseUrl` prop from template.
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.spec.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.ts
Labels: PR: Templates :building_construction:, 🖼 Flow Editor

#2483 disable emit source maps on site-assets compilation
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:, ⚡️ Thunderbolt

#2480 Remove sentry from dev/sites
  packages/create-yoshi-app/templates/flow-editor/typescript/.application.json
  packages/create-yoshi-app/templates/flow-editor/typescript/dev/sites.js
Labels: PR: Polish :nail_care:, 🖼 Flow Editor

#2482 Use default config for editor flow jest. Remove ssr files
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/e2e-ssr/verify-ssr.ssr.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/jest-setup-ssr.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/jest-ssr.config.js
  packages/create-yoshi-app/templates/flow-editor/typescript/tsconfig.json
  packages/jest-yoshi-preset/defaults/editor-flow.js
  packages/jest-yoshi-preset/jest-environment-yoshi-bootstrap/environment-setup.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/globalSetup.js
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/index.js
  packages/jest-yoshi-preset/jest-preset.js
  packages/jest-yoshi-preset/load-jest-config.js
  packages/jest-yoshi-preset/package.json
  packages/yoshi-flow-editor/src/cli.ts
Labels: PR: Polish :nail_care:, PR: Templates :building_construction:, 🖼 Flow Editor

#2484 fix a bug with two manifests with the same name for site-assets
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#2485 Update use rule of externalize-relative-module-loader
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2486 Remove Settings scss file from template
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.scss
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.tsx
Labels: PR: Templates :building_construction:, 🖼 Flow Editor

#2489 Exclude babel & stylable in renovate groups
  renovate.json
Labels: PR: Chore :construction_worker:

#2488 Update devDependencies (weekly)
  package.json
  packages/create-yoshi-app/package.json
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-helpers/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2493 Update stylable to v3.6.0
  packages/yoshi-stylable-dependencies/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2403 Allow to set `controllerType` for component configuration
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/{each%flowData.components:name%each}/viewer.controller.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
Labels: PR: New Feature :rocket:, 🖼 Flow Editor
