Repository wix/yoshi, pull requests merged in 2020-04, with the labels that each got.

#2175 Yoshi Server: support yoshi-server for storybook
  packages/yoshi-flow-legacy/config/webpack.config.js
Labels: PR: Polish :nail_care:, 💁‍♂️ Yoshi Server

#2160 Update dependencies (weekly)
  packages/bootstrap-hot-loader/package.json
  packages/eslint-config-yoshi-base/package.json
  packages/jest-yoshi-preset/package.json
  packages/yoshi-angular-dependencies/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2174 Configure Renovate to ignore `@babel/*` deps
  renovate.json
Labels: PR: Chore :construction_worker:

#2169 add node-api doc to the website's sidebar
  website/sidebars.json
Labels: PR: Docs :memo:

#2177 Use debug: false value for editor bundles.
  packages/yoshi-flow-editor/src/commands/htmlGenerator.ts
  packages/yoshi-flow-editor/src/server/vm.ts
Labels: PR: Bug Fix :bug:

#2173 Fix BM `moduleParams` type breakage
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm-runtime/src/createModule.ts
  packages/yoshi-flow-bm-runtime/src/hooks/TranslationProvider.tsx
  packages/yoshi-flow-bm/src/renderModule.ts
  yarn.lock
Labels: PR: Internal :house:

#2178 Separate Renovate runs for deps & devDeps
  renovate.json
Labels: PR: Chore :construction_worker:

#2179 Update dependency html-webpack-plugin to v4.0.4
  packages/yoshi-common/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2182 Update dependency screenshot-reporter to v1.1.326
  packages/yoshi-flow-legacy/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2170 Support bundling `st.css` files in SSR
  packages/yoshi-common/src/webpack.config.ts
  test/javascript/features/stylable/ssr/package.json
  test/javascript/features/stylable/ssr/src/component.js
  test/javascript/features/stylable/ssr/src/index.ejs
  test/javascript/features/stylable/ssr/src/server.js
  test/javascript/features/stylable/ssr/src/style.st.css
  test/javascript/features/stylable/ssr/ssr-st-css.test.ts
  test/typescript/features/stylable/ssr/package.json
  test/typescript/features/stylable/ssr/src/component.tsx
  test/typescript/features/stylable/ssr/src/index.ejs
  test/typescript/features/stylable/ssr/src/server.tsx
  test/typescript/features/stylable/ssr/src/style.st.css
  test/typescript/features/stylable/ssr/src/test-types.d.ts
  test/typescript/features/stylable/ssr/ssr-st-css.test.ts
  test/typescript/features/stylable/ssr/tsconfig.json
Labels: PR: New Feature :rocket:

#2171 Webpack stats output to a file by default on CI
  packages/yoshi-common/package.json
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-app/src/external-types.d.ts
  packages/yoshi-flow-app/src/scripts/build.ts
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-bm/src/external-types.d.ts
  packages/yoshi-flow-bm/src/scripts/build.ts
  packages/yoshi-flow-bm/src/webpack.config.ts
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-editor/src/commands/build.ts
  packages/yoshi-flow-editor/src/external-types.d.ts
  packages/yoshi-flow-editor/src/webpack.config.ts
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-library/package.json
  packages/yoshi-flow-library/src/commands/build.ts
  packages/yoshi-flow-library/src/external-types.d.ts
  packages/yoshi-flow-library/src/webpack.config.ts
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-flow-monorepo/src/external-types.d.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2184 Prevent throwing errors for `publicData` getter when value is not loaded yet.
  packages/yoshi-flow-editor-runtime/src/WidgetWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/react/PublicDataProviderEditor.tsx
  packages/yoshi-flow-editor-runtime/src/react/PublicDataProviderViewer.tsx
Labels: PR: Bug Fix :bug:, 🐛 Bug, 🖼 Flow Editor

#2185 [editor-flow] Add BoB apps support and allow users override platform hooks.
  packages/create-yoshi-app/templates/flow-editor/javascript/src/init.app.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/viewer.app.js
  packages/create-yoshi-app/templates/flow-editor/typescript/src/init.app.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/viewer.app.ts
  packages/yoshi-flow-editor-runtime/src/EditorAppWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/constants.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/componentWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/editorAppWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/ControllerEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/EditorAppEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/WidgetViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
  packages/yoshi-flow-editor/src/wrappers/widgetViewerScriptWrapping.ts
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2188 Update dependency screenshot-reporter to v1.1.329
  packages/yoshi-flow-legacy/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2186 add the option to override the `globals` object in `e2eOptions` (#2102)
  docs/guides/jest-setup.md
  packages/jest-yoshi-preset/jest-preset.js
  packages/yoshi-config/src/jest/config.ts
  packages/yoshi-config/src/jest/validConfig.ts
  test/javascript/features/jest-preset-overrides/__tests__/jest-preset-overrides.e2e.js
  test/javascript/features/jest-preset-overrides/jest-yoshi.config.js
Labels: PR: New Feature :rocket:

#2183 Generators: bump `bootstrap-hot-loader` to V4
  packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}.json
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}.json
Labels: PR: New Feature :rocket:

#2191 [flow-editor] Add `commonjs2` external for lodash.
  packages/yoshi-flow-editor/src/buildEditorEntires.ts
Labels: PR: Bug Fix :bug:, 🖼 Flow Editor

#2192 Remove strict implicit compiler options
  packages/create-yoshi-app/templates/flow-library/typescript/tsconfig.json
Labels: PR: Templates :building_construction:

#2193 Move transpilation target to ES5 (e.g. support IE11)
  packages/yoshi-common/src/typescript/tsconfig-enforcer.ts
Labels: PR: Flow Library 📚

#2194 Add jest and jest-teamcity-reporter as dependencies
  packages/yoshi-flow-library/package.json
Labels: PR: Bug Fix :bug:, PR: Flow Library 📚

#2195 Update timeout for a flaky test
  test/typescript/features/yoshi-server/api-client-server-react/yoshi-server.test.ts
  test/typescript/features/yoshi-server/api-client-server/api-client-server.test.ts
Labels: PR: Internal :house:

#2197 bump wnpm-ci to 8.0.121
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-monorepo/package.json
Labels: PR: Bug Fix :bug:

#2161 Yoshi Server: refactor InternalServerError
  packages/yoshi-server/src/httpErrors.ts
Labels: PR: Polish :nail_care:

#2181 Update dependencies (weekly)
  packages/yoshi-angular-dependencies/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server/package.json
  packages/yoshi-stylable-dependencies/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2198 Split yoshi server tests
  package.json
Labels: PR: Internal :house:

#2196 Yoshi Server: handle non json response
  packages/yoshi-server-client/src/index.ts
  test/javascript/features/yoshi-server/api-error/__tests__/server.e2e.js
  test/javascript/features/yoshi-server/api-error/api-error.test.ts
  test/javascript/features/yoshi-server/api-error/src/api/greeting.api.js
  test/javascript/features/yoshi-server/api-not-a-json-error/__tests__/server.e2e.js
  test/javascript/features/yoshi-server/api-not-a-json-error/api-error.test.ts
  test/javascript/features/yoshi-server/api-not-a-json-error/index.js
  test/javascript/features/yoshi-server/api-not-a-json-error/package.json
  test/javascript/features/yoshi-server/api-not-a-json-error/pom.xml
  test/javascript/features/yoshi-server/api-not-a-json-error/src/api/greeting.api.js
  test/javascript/features/yoshi-server/api-not-a-json-error/src/server.js
  test/typescript/features/yoshi-server/api-error/__tests__/server.e2e.ts
  test/typescript/features/yoshi-server/api-error/api-error.test.ts
  test/typescript/features/yoshi-server/api-error/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/api-not-a-json-error/__tests__/server.e2e.ts
  test/typescript/features/yoshi-server/api-not-a-json-error/api-error.test.ts
  test/typescript/features/yoshi-server/api-not-a-json-error/index.js
  test/typescript/features/yoshi-server/api-not-a-json-error/package.json
  test/typescript/features/yoshi-server/api-not-a-json-error/pom.xml
  test/typescript/features/yoshi-server/api-not-a-json-error/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/api-not-a-json-error/src/server.tsx
  test/typescript/features/yoshi-server/api-not-a-json-error/tsconfig.json
  test/yoshi-publish/package.json
Labels: PR: New Feature :rocket:

#2205 Fix link in create-app.md
  docs/getting-started/create-app.md
Labels: PR: Docs :memo:

#2200 Remove no-non-null-assertion eslint rule
  .eslintrc
  packages/eslint-config-yoshi-base/index.js
  packages/eslint-config-yoshi/__tests__/rules/no-non-null-assertion/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-non-null-assertion/valid.ts
Labels: PR: Polish :nail_care:

#2108 Lock file maintenance
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-library/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server-react/package.json
  packages/yoshi-server-tools/package.json
  packages/yoshi-server/src/httpErrors.ts
  packages/yoshi-storybook-dependencies/package.json
  test/yoshi-publish/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2210 Move all convention-based files & dirs into `src`
  packages/create-yoshi-app/templates/flow-bm/typescript/src/components/LegacyTodoList.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/methods/getTodo.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/methods/getTodos.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/moduleInit.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/pages/index.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/tsconfig.json
  packages/yoshi-flow-bm-runtime/src/index.ts
  packages/yoshi-flow-bm/src/createFlowBMModel.ts
Labels: PR: Flow BM 💼

#2199 Verify dependency tree for dependency conflicts
  packages/yoshi-common/package.json
  packages/yoshi-common/src/preflight-checks.ts
  packages/yoshi-common/src/verify-dependency-tree.ts
  packages/yoshi-flow-app/src/bin/yoshi-app.ts
  packages/yoshi-flow-bm/src/bin/yoshi-bm.ts
  packages/yoshi-flow-editor/src/cli.ts
  packages/yoshi-flow-legacy/src/cli.js
  packages/yoshi-flow-library/src/cli.ts
  packages/yoshi-flow-monorepo/src/bin/yoshi-monorepo.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2209 Rename BM special dir `components` -> `exported-components`
  packages/create-yoshi-app/templates/flow-bm/typescript/exported-components/LegacyTodoList.tsx
  packages/yoshi-flow-bm-runtime/src/createModule.ts
  packages/yoshi-flow-bm/src/createFlowBMModel.ts
  packages/yoshi-flow-bm/src/renderModule.ts
Labels: PR: Flow BM 💼

#2219 `BROWSER=none` instead of `false` for canceling browser from opening on `start`
  docs/api/cli.md
Labels: PR: Docs :memo:

#2202 Refactor Editor Flow to load Editor SDK dynamically and incapsulate it
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Settings/Settings.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Settings/Settings.spec.js
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/Settings/Settings.spec.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/Settings/Settings.tsx
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-editor-runtime/src/EditorAppWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/SettingsWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/WidgetWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/constants.ts
  packages/yoshi-flow-editor-runtime/src/index.ts
  packages/yoshi-flow-editor-runtime/src/react/Controller/ControllerContext.ts
  packages/yoshi-flow-editor-runtime/src/react/Controller/ControllerProvider.tsx
  packages/yoshi-flow-editor-runtime/src/react/Controller/ControllerRenderProp.tsx
  packages/yoshi-flow-editor-runtime/src/react/Controller/useController.ts
  packages/yoshi-flow-editor-runtime/src/react/PublicData/PublicDataContext.ts
  packages/yoshi-flow-editor-runtime/src/react/PublicData/PublicDataProvider.tsx
  packages/yoshi-flow-editor-runtime/src/react/PublicData/PublicDataProviderEditor.tsx
  packages/yoshi-flow-editor-runtime/src/react/PublicData/PublicDataProviderViewer.tsx
  packages/yoshi-flow-editor-runtime/src/react/PublicData/PublicDataRenderProp.tsx
  packages/yoshi-flow-editor-runtime/src/react/PublicData/usePublicData.ts
  packages/yoshi-flow-editor-runtime/src/react/SDK/EditorSDKProvider.tsx
  packages/yoshi-flow-editor-runtime/src/react/SDK/SDKContext.ts
  packages/yoshi-flow-editor-runtime/src/react/SDK/SDKProvider.tsx
  packages/yoshi-flow-editor-runtime/src/react/SDK/SDKRenderProp.tsx
  packages/yoshi-flow-editor-runtime/src/react/SDK/WixSDKProvider.tsx
  packages/yoshi-flow-editor-runtime/src/react/SDK/useSDK.ts
  packages/yoshi-flow-editor-runtime/src/utils.ts
  packages/yoshi-flow-editor-runtime/src/wixPrivateMockPath.ts
  packages/yoshi-flow-editor/src/server/server.ts
  packages/yoshi-flow-editor/src/server/templates/editorApp.vm
  packages/yoshi-flow-editor/src/server/templates/settingsApp.vm
  packages/yoshi-flow-editor/src/server/vm.ts
  packages/yoshi-flow-editor/src/wrappers/templates/EditorAppEntryContent.ts
  yarn.lock
Labels: PR: Breaking Change :boom:, PR: New Feature :rocket:, 🖼 Flow Editor

#2218 Enable setting mocha timeout as an environment variable
  docs/api/cli.md
  packages/yoshi-flow-legacy/src/commands/test.js
Labels: PR: New Feature :rocket:

#2221 Revert "Verify dependency tree for dependency conflicts (#2199)"
  packages/yoshi-common/package.json
  packages/yoshi-common/src/preflight-checks.ts
  packages/yoshi-common/src/verify-dependency-tree.ts
  packages/yoshi-flow-app/src/bin/yoshi-app.ts
  packages/yoshi-flow-bm/src/bin/yoshi-bm.ts
  packages/yoshi-flow-editor/src/cli.ts
  packages/yoshi-flow-legacy/src/cli.js
  packages/yoshi-flow-library/src/cli.ts
  packages/yoshi-flow-monorepo/src/bin/yoshi-monorepo.ts
  yarn.lock
Labels: 🐛 Bug

#2229 [flow-editor] Use ES5 in entry points.
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/ControllerEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/EditorAppEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/WidgetViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
Labels: PR: Bug Fix :bug:, 🐛 Bug, 🖼 Flow Editor

#2228 [yoshi-flow-editor-runtime] Use isEditor as an optional value
  packages/yoshi-flow-editor-runtime/src/react/SDK/SDKRenderProp.tsx
Labels: PR: Polish :nail_care:, 🖼 Flow Editor

#2237 Add flow editor entries to files needed to be transpiled.
  packages/yoshi-common/src/utils/should-transpile-file.ts
  packages/yoshi-flow-editor/.gitignore
  packages/yoshi-flow-editor/src/buildEditorEntires.ts
Labels: PR: Bug Fix :bug:, 🖼 Flow Editor

#2238 Remove yurynix from codeowners
  CODEOWNERS
Labels: PR: Internal :house:, 🛠 Infrastructure

#2241 Re-render module entry on model changes
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-bm/src/createFlowBMModel.ts
  packages/yoshi-flow-bm/src/renderModule.ts
  packages/yoshi-flow-bm/src/scripts/build.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  yarn.lock
Labels: PR: Flow BM 💼

#2233 Add `isAnalyze` option to Worker bundles for flow editor.
  packages/yoshi-flow-editor/src/commands/build.ts
  packages/yoshi-flow-editor/src/webpack.config.ts
Labels: PR: Polish :nail_care:, 🖼 Flow Editor

#2239 Add chunk names to flow-bm chunks
  packages/yoshi-flow-bm/src/renderModule.ts
Labels: PR: Flow BM 💼

#2243 Render module config in flow BM
  packages/create-yoshi-app/templates/flow-bm/typescript/__tests__/e2e/drivers/app.driver.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/dev/server.ts
  packages/yoshi-flow-bm-runtime/src/createModule.ts
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-bm/src/generateERB.ts
  packages/yoshi-flow-bm/src/renderModuleConfig.ts
  packages/yoshi-flow-bm/src/scripts/build.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  yarn.lock
Labels: PR: Flow BM 💼

#2222 Use `EditorSDKLoadedContext` interface for editorSDK render prop.
  packages/yoshi-flow-editor-runtime/src/react/SDK/SDKContext.ts
  packages/yoshi-flow-editor-runtime/src/react/SDK/SDKRenderProp.tsx
Labels: PR: Polish :nail_care:, 🖼 Flow Editor

#2217 separate wrapping for ooi widgets and platform widgets
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-editor-runtime/src/constants.ts
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/constants.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
  yarn.lock
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2227 Don't transpile Carmi's output with Typescript/Babel
  packages/yoshi-common/src/utils/should-transpile-file.ts
Labels: PR: Polish :nail_care:

#2247 Prep flow-bm template for demo
  packages/create-yoshi-app/templates/flow-bm/typescript/dev/environment.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/exported-components/LegacyTodoList.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/AddTodo.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/TodoItem.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/TodoList.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/pages/index.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/translations/en.json
Labels: PR: Flow BM 💼

#2248 fix bm flow e2e test
  packages/create-yoshi-app/templates/flow-bm/typescript/__tests__/e2e/app.e2e.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/translations/en.json
Labels: PR: Flow BM 💼

#2231 Update editor entry-point to accept `default` export with function
  packages/yoshi-flow-editor/src/wrappers/templates/CommonEditorScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonEditorScriptEntry.test.ts.snap
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2236 Fix lodash path for worker externals
  packages/yoshi-flow-editor/src/webpack.config.ts
Labels: PR: Chore :construction_worker:, 🖼 Flow Editor

#2252 Pass `componentId` to platform's Settings
  packages/yoshi-flow-editor-runtime/src/SettingsWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/index.ts
  packages/yoshi-flow-editor-runtime/src/react/SDK/SDKRenderProp.tsx
  packages/yoshi-flow-editor-runtime/src/utils.ts
  packages/yoshi-flow-editor/src/wrappers/templates/SettingsAppEntryContent.ts
Labels: PR: Polish :nail_care:, 🖼 Flow Editor

#2212 Update devDependencies (weekly)
  package.json
  packages/create-yoshi-app/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server-tools/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2235 Use an identity-proxy that supports both default & named imports
  packages/jest-yoshi-preset/identity-proxy.js
  packages/jest-yoshi-preset/jest-preset.js
Labels: PR: Bug Fix :bug:

#2254 Allow using flag to prevent prop type optimization
  packages/babel-preset-yoshi/index.js
Labels: PR: Internal :house:

#2230 Lock file maintenance
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-library/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server-react/package.json
  packages/yoshi-server-tools/package.json
  test/yoshi-publish/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2258 Remove specific names and use a team as the codeowners of the repo
  .github/CODEOWNERS
  CODEOWNERS
Labels: PR: Internal :house:

#2211 Update dependencies (weekly)
  packages/eslint-config-yoshi-base/package.json
  packages/yoshi-angular-dependencies/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-server-testing/package.json
  packages/yoshi-server/package.json
  packages/yoshi-stylable-dependencies/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2225 Fix flow library template tsconfig to support es5 transpilation
  packages/create-yoshi-app/templates/flow-library/typescript/tsconfig.json
Labels: PR: Templates :building_construction:

#2224 Add editorx domains to webpack-dev-server's allowed hosts
  packages/yoshi-common/src/webpack-dev-server.ts
Labels: PR: New Feature :rocket:

#2257 Add an option to use `@wix/wix-bootstrap-renderer`
  packages/yoshi-server/package.json
  packages/yoshi-server/src/bootstrap.ts
  packages/yoshi-server/src/index.ts
  packages/yoshi-server/src/renderView.ts
  packages/yoshi-server/src/server.ts
  test/fixtures/yoshi-server-javascript/base-template/environment.js
  test/fixtures/yoshi-server-javascript/base-template/index-dev.js
  test/fixtures/yoshi-server-javascript/base-template/index.js
  test/fixtures/yoshi-server-typescript/base-template/environment.js
  test/fixtures/yoshi-server-typescript/base-template/index-dev.js
  test/fixtures/yoshi-server-typescript/base-template/index.js
  test/javascript/features/yoshi-server/route-with-renderView/route.test.ts
  test/javascript/features/yoshi-server/route-with-renderView/src/routes/app.js
  test/typescript/features/yoshi-server/route-with-renderView/route.test.ts
  test/typescript/features/yoshi-server/route-with-renderView/src/routes/app.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2266 Change exports to export s to make the search work on API page
  docs/api/configuration.md
Labels: PR: Docs :memo:

#2264 Flow BM config overrides
  packages/create-yoshi-app/templates/flow-bm/typescript/.module.json
  packages/yoshi-flow-bm/src/config.ts
  packages/yoshi-flow-bm/src/constants.ts
  packages/yoshi-flow-bm/src/createFlowBMModel.ts
  packages/yoshi-flow-bm/src/renderModule.ts
  packages/yoshi-flow-bm/src/renderModuleConfig.ts
  packages/yoshi-helpers/package.json
  packages/yoshi-helpers/src/utils.ts
Labels: PR: Flow BM 💼

#2269 Make the `translations` dir optional in flow-bm
  packages/yoshi-flow-bm-runtime/src/createModule.ts
  packages/yoshi-flow-bm/src/createFlowBMModel.ts
  packages/yoshi-flow-bm/src/renderModule.ts
Labels: PR: Flow BM 💼

#2256 Bundle editor-elements-library similar to thudnerbolt-elements
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Internal :house:

#2267 Add a progress bar for all build & start commands
  packages/yoshi-common/package.json
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-legacy/config/webpack.config.js
  packages/yoshi-flow-library/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2272 Generate automatically bundle analyzer port
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-legacy/test/build.spec.js
  test/scripts.ts
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2274 Minimize node server code for Tb-Elements
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#2280 write only the minimal stats file and do it only when needed
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: New Feature :rocket:

#2275 Add docs for platform apps support with editor flow
  packages/yoshi-flow-editor/docs/EDITOR-AND-SETTINGS-APPS.md
  packages/yoshi-flow-editor/docs/PLATFORM_APPS_SUPPORT.md
Labels: PR: Docs :memo:, 📜 Documentation

#2284 Enable --stats for monorepo-flow worker bundle
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: New Feature :rocket:

#2278 Yoshi Server: fix types
  packages/yoshi-server/src/bootstrap.ts
  packages/yoshi-server/src/server.ts
  packages/yoshi-server/src/types.ts
Labels: PR: Internal :house:

#2277 Yoshi Server: fix a bug where there's no renderer
  packages/yoshi-server/src/server.ts
  test/javascript/features/yoshi-server/custom-server/custom-server.test.ts
  test/javascript/features/yoshi-server/custom-server/index.js
  test/javascript/features/yoshi-server/custom-server/src/api/greeting.api.js
  test/javascript/features/yoshi-server/custom-server/src/client.js
  test/javascript/features/yoshi-server/custom-server/src/component.js
  test/javascript/features/yoshi-server/custom-server/src/component.spec.jsx
  test/javascript/features/yoshi-server/custom-server/src/routes/app.js
  test/javascript/features/yoshi-server/custom-server/src/server.js
  test/javascript/features/yoshi-server/custom-server/src/templates/app.ejs
  test/typescript/features/yoshi-server/custom-server/custom-server.test.ts
  test/typescript/features/yoshi-server/custom-server/index.js
  test/typescript/features/yoshi-server/custom-server/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/custom-server/src/client.tsx
  test/typescript/features/yoshi-server/custom-server/src/component.spec.tsx
  test/typescript/features/yoshi-server/custom-server/src/component.tsx
  test/typescript/features/yoshi-server/custom-server/src/routes/app.ts
  test/typescript/features/yoshi-server/custom-server/src/server.tsx
  test/typescript/features/yoshi-server/custom-server/src/templates/app.ejs
Labels: PR: Bug Fix :bug:

#2287 Add flow editor to docs
  website/docs/editor-flow/dev-center-registration.md
  website/docs/editor-flow/editor-and-settings-apps.md
  website/docs/editor-flow/migration-guide.md
  website/docs/editor-flow/overview.md
  website/docs/editor-flow/platform-apps-support.md
  website/docusaurus.config.js
  website/sidebars.js
  website/versioned_docs/version-4.x/editor-flow/dev-center-registration.md
  website/versioned_docs/version-4.x/editor-flow/editor-and-settings-apps.md
  website/versioned_docs/version-4.x/editor-flow/migration-guide.md
  website/versioned_docs/version-4.x/editor-flow/overview.md
  website/versioned_docs/version-4.x/editor-flow/platform-apps-support.md
  website/versioned_sidebars/version-4.x-sidebars.json
Labels: PR: Docs :memo:, 📜 Documentation

#2285 Inline all assets used in the docs
  website/blog/2019-03-12-yoshi-4.md
  website/blog/assets/24-app-flow.png
  website/versioned_docs/version-3.x/guides/debugging.md
  website/versioned_docs/version-4.x/guides/app-flow.md
  website/versioned_docs/version-4.x/guides/debugging.md
Labels: PR: Docs :memo:

#2244 Import from yoshi-helpers/build
  packages/yoshi-flow-editor/src/model.ts
Labels: PR: Chore :construction_worker:

#2226 fix a bug that prevented library flow to work in some cases when yarn…
  packages/yoshi-common/src/typescript/run-babel.ts
Labels: PR: Bug Fix :bug:

#2288 Brand new main page based on yoshi flows universe idea 🚀
  website/docusaurus.config.js
  website/flows.json
  website/src/pages/Header/Planet.js
  website/src/pages/Header/Space.js
  website/src/pages/Header/header.module.css
  website/src/pages/Header/index.js
  website/src/pages/Header/planet.module.css
  website/src/pages/Header/space.module.css
  website/src/pages/index.js
  website/src/pages/styles.module.css
Labels: PR: Docs :memo:, 📜 Documentation

#2289 Change tagline and improve planets logic
  website/docusaurus.config.js
  website/src/pages/Universe/Planet.js
  website/src/pages/Universe/Space.js
  website/src/pages/Universe/header.module.css
  website/src/pages/Universe/index.js
  website/src/pages/Universe/planet.module.css
  website/src/pages/Universe/space.module.css
  website/src/pages/index.js
  website/src/pages/styles.module.css
Labels: PR: Docs :memo:

#2292 Update devDependencies (weekly)
  packages/bootstrap-hot-loader/package.json
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-legacy/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2245 Use `is-ci` package instead of reading TeamCity's env vars
  package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-legacy/src/tasks/protractor/index.js
  packages/yoshi-flow-legacy/test/e2e.spec.js
  packages/yoshi-helpers/package.json
  packages/yoshi-helpers/src/queries.ts
  test-helpers/env-variables.js
  test/globalSetup.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2291 Update dependencies (weekly)
  packages/eslint-config-yoshi-base/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-server/package.json
  packages/yoshi-stylable-dependencies/package.json
  packages/yoshi-style-dependencies/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2293 Register page components with componentName instead of id
  packages/yoshi-flow-bm-runtime/src/createModule.ts
  packages/yoshi-flow-bm/src/renderModule.ts
Labels: PR: Bug Fix :bug:, 💼 Flow BM

#2295 Pass --analyze in monorepo worker bundles
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: New Feature :rocket:

#2300 be able to profile a build using `PROFILE=true`
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: New Feature :rocket:

#2273 Yoshi Server: add a config object
  packages/yoshi-server/src/routes/api.ts
  packages/yoshi-server/src/server.ts
  packages/yoshi-server/src/types.ts
  test/fixtures/yoshi-server-javascript/base-template/environment.js
  test/fixtures/yoshi-server-typescript/base-template/environment.js
  test/javascript/features/yoshi-server/config/config.test.ts
  test/javascript/features/yoshi-server/config/package.json
  test/javascript/features/yoshi-server/config/src/api/greeting.api.js
  test/javascript/features/yoshi-server/config/src/component.js
  test/javascript/features/yoshi-server/config/src/routes/app.ts
  test/javascript/features/yoshi-server/config/src/templates/app.ejs
  test/javascript/features/yoshi-server/config/templates/yoshi-server-javascript-config.json.erb
  test/javascript/features/yoshi-server/config/test/configs/yoshi-server-javascript-config.json
  test/typescript/features/yoshi-server/config/config.test.ts
  test/typescript/features/yoshi-server/config/package.json
  test/typescript/features/yoshi-server/config/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/config/src/component.tsx
  test/typescript/features/yoshi-server/config/src/routes/app.ts
  test/typescript/features/yoshi-server/config/src/templates/app.ejs
  test/typescript/features/yoshi-server/config/templates/yoshi-server-typescript-config.json.erb
  test/typescript/features/yoshi-server/config/test/configs/yoshi-server-typescript-config.json
Labels: PR: New Feature :rocket:

#2180 Update yoshi server testing with new api
  packages/yoshi-server-testing/src/index.ts
  test/javascript/features/yoshi-server/api-client-server-react/src/components/App/App.spec.js
  test/javascript/features/yoshi-server/api-client-server/src/component.spec.js
  test/typescript/features/yoshi-server/api-client-server-react/src/components/App/App.spec.tsx
  test/typescript/features/yoshi-server/api-client-server/src/component.spec.tsx
Labels: PR: New Feature :rocket:

#2303 Revert "Update yoshi server testing with new api"
  packages/yoshi-server-testing/src/index.ts
  test/javascript/features/yoshi-server/api-client-server-react/src/components/App/App.spec.js
  test/javascript/features/yoshi-server/api-client-server/src/component.spec.js
  test/typescript/features/yoshi-server/api-client-server-react/src/components/App/App.spec.tsx
  test/typescript/features/yoshi-server/api-client-server/src/component.spec.tsx
Labels: PR: Internal :house:

#2301 Improve Elements' server bundle size
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#2302 Decrease the size of Elements/TB stats file
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#2283 Yoshi Server: Support BM routing
  packages/yoshi-server/src/server.ts
  test/javascript/features/yoshi-server/bm-route/bm-route.test.ts
  test/javascript/features/yoshi-server/bm-route/index.js
  test/javascript/features/yoshi-server/bm-route/src/api/greeting.api.js
  test/javascript/features/yoshi-server/bm-route/src/client.js
  test/javascript/features/yoshi-server/bm-route/src/component.js
  test/javascript/features/yoshi-server/bm-route/src/routes/app.js
  test/javascript/features/yoshi-server/bm-route/src/server.js
  test/javascript/features/yoshi-server/bm-route/src/templates/app.ejs
  test/typescript/features/yoshi-server/bm-route/bm-route.test.ts
  test/typescript/features/yoshi-server/bm-route/index.js
  test/typescript/features/yoshi-server/bm-route/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/bm-route/src/client.tsx
  test/typescript/features/yoshi-server/bm-route/src/component.tsx
  test/typescript/features/yoshi-server/bm-route/src/routes/app.ts
  test/typescript/features/yoshi-server/bm-route/src/server.tsx
  test/typescript/features/yoshi-server/bm-route/src/templates/app.ejs
Labels: PR: New Feature :rocket:

#2309 Fix `devtools` option in `jest-yoshi.config.js` not working bug
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/globalSetup.js
Labels: PR: Bug Fix :bug:

#2290 Add initial BM Flow docs
  website/docs/business-manager-flow.md
  website/flows.json
  website/sidebars.js
  website/versioned_docs/version-4.x/business-manager-flow.md
  website/versioned_sidebars/version-4.x-sidebars.json
  website/yarn.lock
Labels: PR: Docs :memo:

#2310 Create stats for Elements/TB with Webpack's publicPath
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#2311 Move `__tests__` directory to be inside `src`
  packages/create-yoshi-app/templates/flow-library/typescript/src/__tests__/browser.e2e.ts
  packages/create-yoshi-app/templates/flow-library/typescript/src/__tests__/counter.spec.ts
Labels: PR: Templates :building_construction:

#2251 Yoshi Server Client: use `wix-headers`
  packages/yoshi-server-client/package.json
  packages/yoshi-server-client/src/index.ts
  yarn.lock
Labels: PR: New Feature :rocket:
