Repository wix/yoshi, pull requests merged in 2020-06, with the labels that each got.

#2487 Remove yoshi config for editor flow
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/yoshi.config.js
  packages/create-yoshi-app/templates/flow-editor/typescript/yoshi.config.js
  packages/yoshi-config/src/loadConfig.ts
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/cli.ts
  packages/yoshi-flow-editor/src/commands/start.ts
  packages/yoshi-flow-editor/src/constants.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/utils.ts
  packages/yoshi-flow-editor/src/yoshi.config.js
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2494 petri-specs in a monorepo
  packages/yoshi-common/src/sync-petri-specs.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
Labels: PR: New Feature :rocket:

#2497 Fix `moduleInit` being required in flow-bm-runtime
  packages/yoshi-flow-bm-runtime/src/createModule.ts
Labels: PR: Bug Fix :bug:

#2500 Improve yoshi description points on the website main page
  website/src/pages/index.js
Labels: PR: Docs :memo:

#2501 Produce sourcemaps for site-assets modules
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:, ⚡️ Thunderbolt

#2503 Produce a `umd` bundle for site-assets web bundles
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: New Feature :rocket:, ⚡️ Thunderbolt

#2498 Configure `auto-release` by default
  packages/create-yoshi-app/scripts/dev.js
  packages/create-yoshi-app/src/api.ts
  packages/create-yoshi-app/src/auto-release/autoReleaseService.ts
  packages/create-yoshi-app/src/auto-release/setupAutoRelease.ts
  packages/create-yoshi-app/src/createApp.ts
  packages/create-yoshi-app/src/dev-center-registration/appService.ts
  packages/create-yoshi-app/src/dev-center-registration/getQuestions.ts
  packages/create-yoshi-app/src/dev-center-registration/runPrompt.ts
  packages/create-yoshi-app/src/sentry-registration/addSentry.ts
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2495 Add `moduleConfigurationId` to bm-flow config
  packages/yoshi-flow-bm-runtime/src/createModule.ts
  packages/yoshi-flow-bm/src/config/types.ts
  packages/yoshi-flow-bm/src/config/validConfig.ts
  packages/yoshi-flow-bm/src/model.ts
  packages/yoshi-flow-bm/src/renderModule.ts
  packages/yoshi-flow-bm/src/renderModuleConfig.ts
Labels: PR: New Feature :rocket:

#2504 kill child servers on serve process exit
  packages/yoshi-common/src/commands/serve.ts
  packages/yoshi-common/src/server-process.ts
Labels: PR: New Feature :rocket:

#2502 Fix nested route inference in flow-bm
  packages/yoshi-flow-bm/src/model.ts
  packages/yoshi-flow-bm/src/renderModuleConfig.ts
Labels: PR: Bug Fix :bug:

#2505 Read `{testEnv}-setup.(ts|js)` files from within `src/(__tests__|test)`
  packages/jest-yoshi-preset/jest-preset.js
Labels: PR: New Feature :rocket:

#2469 Add `--url` to `yoshi-bm start`
  packages/yoshi-flow-bm/src/scripts/start.ts
  website/docs/business-manager-flow.md
Labels: PR: New Feature :rocket:

#2418 Open production BM on `yoshi-bm start`
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-bm/src/bin/yoshi-bm.ts
  packages/yoshi-flow-bm/src/cache.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  packages/yoshi-flow-bm/src/start-url.ts
  website/docs/business-manager-flow.md
  yarn.lock
Labels: PR: New Feature :rocket:

#2506 Update runtime docs
  website/docs/editor-flow/runtime-API.md
  website/docs/editor-flow/structure-api/component.md
Labels: PR: Docs :memo:, 📜 Documentation, 🖼 Flow Editor

#2508 Update devDependencies (weekly)
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-server-tools/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2509 Update stylable to v3.6.2
  packages/yoshi-stylable-dependencies/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2510 Replace jest-teamcity-reporter with jest-teamcity
  jest.config.js
  jest.unit.config.js
  package.json
  packages/jest-yoshi-preset/jest-preset.js
  packages/yoshi-flow-legacy/config/jest.config.js
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-library/package.json
  yarn.lock
Labels: PR: Internal :house:

#2517 Improve contributing section - sort, arrange and ensure it's up to date
  CONTRIBUTING.md
Labels: PR: Docs :memo:

#2507 Make viewer.app.ts and editor.app.ts optional
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/wrappers/commonEditorScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/editorAppWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonEditorScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/ControllerEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/EditorAppEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/WidgetViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonEditorScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/EditorAppEntryContent.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonEditorScriptEntry.test.ts.snap
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/EditorAppEntryContent.test.ts.snap
  packages/yoshi-flow-editor/src/wrappers/widgetViewerScriptWrapping.ts
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2519 Pass unused arguments to jest in library-flow
  packages/yoshi-flow-library/src/commands/test.ts
Labels: PR: New Feature :rocket:

#2514 Endorse starting from wix-serverless when creating a server project
  packages/create-yoshi-app/package.json
  packages/create-yoshi-app/src/TemplateModel.ts
  packages/create-yoshi-app/src/dev-center-registration/runPrompt.ts
  packages/create-yoshi-app/src/getQuestions.ts
  yarn.lock
Labels: PR: Templates :building_construction:

#2521 Init flowAPI even if no viewer.app.ts was created
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/utils.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonEditorScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonEditorScriptEntry.test.ts.snap
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2522 Add warning about global installation
  website/docs/create-yoshi-app.md
Labels: PR: Docs :memo:

#2523 Fix a bug with server process and `--debug` argv
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/server-process.ts
  packages/yoshi-flow-app/src/scripts/start.ts
Labels: PR: Bug Fix :bug:

#2526 Support configuring webworker compilation's resolve.alias
  packages/yoshi-config/src/config.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-config/src/validConfig.ts
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: New Feature :rocket:

#2525 Do not show progress bar if `DEBUG=true`
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#2513 Create Sentry logs automatically
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.spec.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/editor.app.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/viewer.app.ts
  packages/yoshi-flow-editor-runtime/src/EditorAppWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/FlowAPI.ts
  packages/yoshi-flow-editor-runtime/src/editorScript.ts
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/cli.ts
  packages/yoshi-flow-editor/src/commands/ciConfigGenerator.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/wrappers/commonEditorScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonEditorScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
  website/docs/editor-flow/runtime-API.md
  website/static/img/sentry-error-row.png
  website/static/img/sentry-search.png
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2529 Publish yoshi's packages to http://npm.dev.wixpress.com/
  package.json
  scripts/customPublish.ts
Labels: PR: Internal :house:

#2490 Yoshi Serverless POC
  .eslintignore
  packages/yoshi-common/src/copy-serverless.ts
  packages/yoshi-common/src/templates/serverless/package.json
  packages/yoshi-common/src/templates/serverless/serverless.js
  packages/yoshi-common/src/webpack-utils.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-config/src/paths.ts
  packages/yoshi-flow-app/src/scripts/build.ts
  packages/yoshi-server-tools/src/utils.ts
  packages/yoshi-serverless/.npmrc
  packages/yoshi-serverless/package.json
  packages/yoshi-serverless/src/external-types.d.ts
  packages/yoshi-serverless/src/index.ts
  packages/yoshi-serverless/src/routes/api.ts
  packages/yoshi-serverless/src/server.ts
  packages/yoshi-serverless/src/types.ts
  packages/yoshi-serverless/src/utils.ts
  packages/yoshi-serverless/src/wrap.ts
  packages/yoshi-serverless/tsconfig.json
  packages/yoshi-serverless/types.d.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2532 yoshi-stylable-dependencies(package.json): add explicit @stylable/core
  packages/yoshi-stylable-dependencies/package.json
Labels: PR: Bug Fix :bug:

#2535 fix serverless route + add a missing dep
  packages/yoshi-common/src/templates/serverless/package.json
  packages/yoshi-serverless/src/routes/api.ts
Labels: PR: New Feature :rocket:

#2512 in case there is an error during prompts it will now throw properly
  packages/create-yoshi-app/src/runPrompt.ts
Labels: PR: Internal :house:, 🛠 Infrastructure

#2528 Remove editor.app.ts and viewer.app.ts from the template. Update docs
  packages/create-yoshi-app/templates/flow-editor/typescript/src/editor.app.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/viewer.app.ts
  website/docs/editor-flow/structure-api/application.md
  website/docs/editor-flow/structure-api/configuration.md
  website/docs/editor-flow/structure-api/overview.md
  website/sidebars.js
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2530 Fix wrong value passed in `moduleConfigurationId` in flow-bm
  packages/yoshi-flow-bm/src/renderModule.ts
Labels: PR: Bug Fix :bug:

#2537 fix create yoshi app library flow creation bug
  __tests__/verifyNvmrc.test.ts
  packages/create-yoshi-app/__tests__/TemplateModel.test.ts
  packages/create-yoshi-app/__tests__/createApp.test.ts
  packages/create-yoshi-app/__tests__/generateProject.test.ts
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/src/TemplateModel.ts
  packages/create-yoshi-app/src/getQuestions.ts
  packages/create-yoshi-app/src/templates.ts
Labels: PR: Bug Fix :bug:

#2543 Copy templates in flow-bm
  packages/yoshi-flow-bm/src/scripts/build.ts
Labels: PR: Bug Fix :bug:

#2531 Write full webpack errors log to file.
  packages/yoshi-common/src/webpack-utils.ts
Labels: PR: New Feature :rocket:

#2536 Document env vars related to debugging
  website/docs/development/debugging.md
Labels: PR: Docs :memo:

#2542 Yoshi Serverless: remove redundant deps and test scope
  packages/yoshi-common/src/copy-serverless.ts
  packages/yoshi-common/src/templates/serverless/package.json
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-app/src/scripts/build.ts
  packages/yoshi-helpers/src/utils.ts
Labels: PR: New Feature :rocket:

#2544 Fix a bug with create yoshi app
  packages/create-yoshi-app/src/getQuestions.ts
Labels: PR: Bug Fix :bug:

#2539 Send telemetry when start building
  packages/yoshi-common/package.json
  packages/yoshi-common/src/telemetry.ts
  packages/yoshi-flow-app/src/scripts/build.ts
  packages/yoshi-flow-bm/src/scripts/build.ts
  packages/yoshi-flow-editor/src/commands/build.ts
  packages/yoshi-flow-legacy/src/commands/build.js
  packages/yoshi-flow-library/src/cli.ts
  packages/yoshi-flow-library/src/commands/build.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  yarn.lock
Labels: PR: Internal :house:

#2546 Minify server worker in monorepo flow
  packages/yoshi-flow-monorepo/src/scripts/build.ts
Labels: PR: Polish :nail_care:

#2545 Fix missing JSON.stringify for sentry and fedops in flow-bm
  packages/yoshi-flow-bm/src/renderPage.ts
Labels: PR: Bug Fix :bug:

#2551 Simplify the way we perform requests to the BI
  packages/yoshi-common/package.json
  packages/yoshi-common/src/telemetry.ts
  packages/yoshi-common/src/utils/helpers.ts
Labels: PR: Bug Fix :bug:

#2553 improve debugging guide and added debug mode - initial version
  packages/yoshi-common/package.json
  packages/yoshi-common/src/telemetry.ts
  packages/yoshi-common/src/webpack.config.ts
  website/docs/development/debugging.md
  website/docs/development/environment-variables.md
  website/sidebars.js
  yarn.lock
Labels: PR: New Feature :rocket:

#2555 Make library flow template deploy a tar.gz file to parastorage
  packages/create-yoshi-app/templates/flow-library/typescript/pom.xml
Labels: PR: Templates :building_construction:

#2559 Add comment about Bundle Stats Board
  website/docs/development/bundle-analyze.md
Labels: PR: Docs :memo:

#2560 Update dependency type-fest to v0.15.1
  packages/yoshi-common/package.json
  packages/yoshi-helpers/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2561 Update stylable to v3.6.3
  packages/yoshi-stylable-dependencies/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2556 Screencast scripts and simple screencast created.
  scripts/screencast/screencast.js
  scripts/screencast/screencast.sh
  scripts/screencast/screencast.svg
Labels: PR: Internal :house:

#2557 New CLI Command for editor flow: add
  packages/create-yoshi-app/src/TemplateModel.ts
  packages/create-yoshi-app/src/auto-release/setupAutoRelease.ts
  packages/create-yoshi-app/src/createApp.ts
  packages/create-yoshi-app/src/dev-center-registration/auth.ts
  packages/create-yoshi-app/src/dev-center-registration/getQuestions.ts
  packages/create-yoshi-app/src/dev-center-registration/runPrompt.ts
  packages/create-yoshi-app/src/extended-prompts.ts
  packages/create-yoshi-app/src/generateProject.ts
  packages/create-yoshi-app/src/index.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/fedops.json
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}.json
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-editor/src/cli.ts
  packages/yoshi-flow-editor/src/commands/add-component/fedops.ts
  packages/yoshi-flow-editor/src/commands/add-component/index.ts
  packages/yoshi-flow-editor/src/commands/add-component/runPrompt.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/utils.ts
  website/docs/editor-flow/cli-API.md
  website/docs/editor-flow/getting-started.md
  website/docs/editor-flow/local-development.md
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2563 Force webworker server to use process.env.browser with false
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#2511 EP-1009|added support for appBuilderUrl
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/commands/start.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/utils.ts
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2568 Remove sourcemaps from site-assets node
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#2569 also minify site-assets node compilation
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:, ⚡️ Thunderbolt

#2566 [Library Flow]: Add target for case of a node library
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/typescript/tsc-process.ts
  packages/yoshi-flow-library/src/commands/build.ts
  packages/yoshi-flow-library/src/commands/start.ts
  packages/yoshi-flow-library/src/config/normalize.ts
  packages/yoshi-flow-library/src/config/types.ts
  packages/yoshi-flow-library/src/config/validConfig.ts
Labels: PR: New Feature :rocket:

#2565 Migration guide for Library flow from the Legacy flow
  website/docs/library-flow/configuration.md
  website/docs/library-flow/migration-guide.md
  website/docs/library-flow/overview.md
  website/flows.json
  website/sidebars.js
Labels: PR: Docs :memo:

#2572 Do not minify site-assets node during start
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:, ⚡️ Thunderbolt

#2570 using custom certificate when provided in legacy cdn
  packages/yoshi-flow-legacy/src/tasks/cdn/index.js
Labels: PR: New Feature :rocket:

#2549 Yoshi Serverless: add a publish serverless step
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-app/src/scripts/build.ts
  packages/yoshi-flow-app/tsconfig.json
  packages/yoshi-server-client/src/index.ts
  packages/yoshi-server-tools/package.json
  packages/yoshi-server-tools/src/serverless-publish.ts
  packages/yoshi-server-tools/tsconfig.json
  yarn.lock
Labels: PR: New Feature :rocket:

#2573 Fix a bug where #2563 didn't work as intended
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#2574 be able to run PROFILE=true on yoshi start and document it
  packages/yoshi-common/src/dev-environment-logger.ts
  packages/yoshi-common/src/webpack.config.ts
  website/docs/development/environment-variables.md
Labels: PR: New Feature :rocket:

#2580 Yoshi Serverless: add logs to publish step
  packages/yoshi-server-tools/src/serverless-publish.ts
Labels: PR: New Feature :rocket:

#2567 Upload source maps to sentry
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-flow-monorepo/src/webpack.config.ts
  packages/yoshi-helpers/src/queries.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2581 Yoshi serverless: fix publish step
  packages/yoshi-flow-app/src/scripts/build.ts
Labels: PR: Bug Fix :bug:

#2579 Yoshi Serverless: bundle serverless file
  packages/yoshi-common/src/templates/serverless/package.json
  packages/yoshi-common/src/webpack-utils.ts
  packages/yoshi-serverless/src/server.ts
  packages/yoshi-serverless/src/utils.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2571 Add an Editor flow logger
  packages/yoshi-common/src/dev-environment-logger.ts
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/socket-server.ts
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-editor/src/commands/dev-environment-logger.ts
  packages/yoshi-flow-editor/src/commands/start.ts
  packages/yoshi-flow-editor/src/external-types.d.ts
  packages/yoshi-flow-editor/src/server/server.ts
  yarn.lock
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2577 Avoid creating changes that are just a reordering of the references
  packages/yoshi-flow-monorepo/src/verify-typescript-references.ts
Labels: PR: Polish :nail_care:

#2576 Document `moduleConfigurationId` in bm flow
  website/docs/business-manager-flow.md
Labels: PR: Docs :memo:

#2554 Support configuring Webpack's splitChunks for webworkers
  packages/yoshi-config/src/config.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-config/src/validConfig.ts
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
  test/javascript/features/web-worker/web-worker-dynamic-imports/package.json
  test/javascript/features/web-worker/web-worker-dynamic-imports/src/a.js
  test/javascript/features/web-worker/web-worker-dynamic-imports/src/b.js
  test/javascript/features/web-worker/web-worker-dynamic-imports/src/component.js
  test/javascript/features/web-worker/web-worker-dynamic-imports/src/server.js
  test/javascript/features/web-worker/web-worker-dynamic-imports/src/web-worker-wrapper.js
  test/javascript/features/web-worker/web-worker-dynamic-imports/src/worker.js
  test/javascript/features/web-worker/web-worker-dynamic-imports/web-worker.test.ts
  test/javascript/features/web-worker/web-worker-dynamic-imports/yoshi.config.js
  test/javascript/features/web-worker/web-worker-split-chunks/package.json
  test/javascript/features/web-worker/web-worker-split-chunks/src/a.js
  test/javascript/features/web-worker/web-worker-split-chunks/src/b.js
  test/javascript/features/web-worker/web-worker-split-chunks/src/component.js
  test/javascript/features/web-worker/web-worker-split-chunks/src/server.js
  test/javascript/features/web-worker/web-worker-split-chunks/src/web-worker-wrapper.js
  test/javascript/features/web-worker/web-worker-split-chunks/src/worker.js
  test/javascript/features/web-worker/web-worker-split-chunks/web-worker.test.ts
  test/javascript/features/web-worker/web-worker-split-chunks/yoshi.config.js
  test/typescript/features/web-worker/web-worker-dynamic-imports/package.json
  test/typescript/features/web-worker/web-worker-dynamic-imports/src/a.ts
  test/typescript/features/web-worker/web-worker-dynamic-imports/src/b.ts
  test/typescript/features/web-worker/web-worker-dynamic-imports/src/component.tsx
  test/typescript/features/web-worker/web-worker-dynamic-imports/src/server.tsx
  test/typescript/features/web-worker/web-worker-dynamic-imports/src/web-worker-wrapper.js
  test/typescript/features/web-worker/web-worker-dynamic-imports/src/worker.ts
  test/typescript/features/web-worker/web-worker-dynamic-imports/web-worker.test.ts
  test/typescript/features/web-worker/web-worker-dynamic-imports/yoshi.config.js
  test/typescript/features/web-worker/web-worker-split-chunks/package.json
  test/typescript/features/web-worker/web-worker-split-chunks/src/a.ts
  test/typescript/features/web-worker/web-worker-split-chunks/src/b.ts
  test/typescript/features/web-worker/web-worker-split-chunks/src/component.tsx
  test/typescript/features/web-worker/web-worker-split-chunks/src/server.tsx
  test/typescript/features/web-worker/web-worker-split-chunks/src/web-worker-wrapper.js
  test/typescript/features/web-worker/web-worker-split-chunks/src/worker.ts
  test/typescript/features/web-worker/web-worker-split-chunks/web-worker.test.ts
  test/typescript/features/web-worker/web-worker-split-chunks/yoshi.config.js
Labels: PR: New Feature :rocket:

#2583 Yoshi Serverless: no need to copy templates
  packages/yoshi-common/src/copy-serverless.ts
  packages/yoshi-common/src/templates/serverless/package.json
  packages/yoshi-flow-app/src/scripts/build.ts
Labels: PR: Internal :house:

#2584 Yoshi Serverless: fix version to work with PR CI
  packages/yoshi-helpers/src/utils.ts
Labels: PR: New Feature :rocket:

#2575 Simplify experiments using `scope` prop in flow-bm
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm-runtime/src/experiments.tsx
  yarn.lock
Labels: PR: Internal :house:

#2582 Support optional chaining and nullish coalescing in development
  packages/babel-preset-yoshi/index.js
Labels: PR: Bug Fix :bug:

#2538 Fix extra renders caused by wrapComponent
  packages/yoshi-flow-bm-runtime/src/wrapComponent.tsx
Labels: PR: Bug Fix :bug:

#2586 Upgrade link to polyfill v3
  packages/babel-preset-yoshi/index.js
  packages/create-yoshi-app/templates/client/javascript/src/index.vm
  packages/create-yoshi-app/templates/client/typescript/src/index.vm
  packages/create-yoshi-app/templates/fullstack/javascript/src/index.ejs
  packages/create-yoshi-app/templates/fullstack/typescript/src/index.ejs
  packages/yoshi-flow-editor/src/server/templates/editorApp.vm
  packages/yoshi-flow-editor/src/server/templates/settingsApp.vm
Labels: PR: Templates :building_construction:

#2588 Yoshi Server - fix hard coded version
  packages/yoshi-server-tools/package.json
  yarn.lock
Labels: PR: Bug Fix :bug:

#2587 Allow pass Wix instance for Wix provider to prevent loading original one
  packages/yoshi-flow-editor-runtime/src/react/SDK/WixSDKProvider.tsx
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2585 Add `appDefId` config option
  packages/yoshi-flow-bm/src/config/types.ts
  packages/yoshi-flow-bm/src/config/validConfig.ts
  packages/yoshi-flow-bm/src/renderModuleConfig.ts
  website/docs/business-manager-flow.md
Labels: PR: New Feature :rocket:, 💼 Flow BM

#2589 Yoshi Serverless - fix a bug with serverless scope
  packages/yoshi-helpers/src/utils.ts
Labels: PR: Bug Fix :bug:

#2590 Only minify server worker for Thunderbolt App
  packages/yoshi-flow-monorepo/src/scripts/build.ts
Labels: PR: Polish :nail_care:

#2591 Yoshi Serverless - use `serverlessscope` only when needed
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Internal :house:

#2593 Remove resolveAlias warnings from jest-validate
  packages/yoshi-config/src/validConfig.ts
Labels: PR: Polish :nail_care:

#2600 Fix a bug with `moduleConfigurationId` (missing coma) in flow-bm
  packages/yoshi-flow-bm/src/renderModule.ts
Labels: PR: Bug Fix :bug:

#2599 Improve env-vars guide in the docs
  website/versioned_docs/version-4.x/development/environment-variables.md
Labels: PR: Docs :memo:

#2595 Re-export everything from `@wix/wix-experiments-react`
  packages/create-yoshi-app/templates/flow-bm/typescript/src/pages/index.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}.json
  packages/yoshi-flow-bm-runtime/src/experiments.tsx
  website/docs/business-manager-flow.md
Labels: PR: Polish :nail_care:

#2491 Lock file maintenance
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-library/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server-react/package.json
  packages/yoshi-server-tools/package.json
  test/yoshi-publish/package.json
  website/yarn.lock
  yarn.lock
Labels: PR: Chore :construction_worker:

#2601 Update dependency eslint-plugin-jsx-a11y to v6.3.1
  packages/eslint-config-yoshi/package.json
Labels: PR: Chore :construction_worker:

#2603 Unpin typescript in templates
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}.json
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}.json
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}.json
  packages/create-yoshi-app/templates/flow-editor-platform/typescript/{%packagejson%}.json
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}.json
  packages/create-yoshi-app/templates/flow-library/typescript/{%packagejson%}.json
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}.json
  packages/create-yoshi-app/templates/library/typescript/{%packagejson%}.json
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}.json
Labels: PR: Templates :building_construction:

#2460 Update dependencies (weekly)
  packages/create-yoshi-app/package.json
  packages/yoshi-angular-dependencies/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-library/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-server-client/package.json
  packages/yoshi-server-testing/package.json
  packages/yoshi-server/package.json
  packages/yoshi-serverless/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2605 Yoshi serverless: ambassador externals
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-server-tools/src/serverless-publish.ts
Labels: PR: New Feature :rocket:

#2492 Update babel
  packages/babel-plugin-transform-hmr-runtime/package.json
  packages/babel-preset-yoshi/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-server-tools/package.json
  packages/yoshi/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2609 Emit sourcemaps for site-assets node compilation
  packages/yoshi-flow-monorepo/src/scripts/build.ts
Labels: PR: Bug Fix :bug:, ⚡️ Thunderbolt

#2607 Lock file maintenance
  website/yarn.lock
  yarn.lock
Labels: PR: Chore :construction_worker:

#2611 Build typescript with --force flag (no cache)
  package.json
Labels: PR: Internal :house:

#2548 Add Storybook integration in flow-library
  packages/yoshi-flow-library/src/commands/start.ts
  test/fixtures/flow-library/base-template/package.json
  test/fixtures/flow-library/base-template/src/component.spec.tsx
  test/fixtures/flow-library/base-template/src/component.tsx
  test/fixtures/flow-library/base-template/src/index.ts
  test/fixtures/flow-library/base-template/tsconfig.json
  test/scripts.ts
  test/typescript/features/storybook/flow-library-happy-flow/package.json
  test/typescript/features/storybook/flow-library-happy-flow/src/component.stories.tsx
  test/typescript/features/storybook/flow-library-happy-flow/src/component.tsx
  test/typescript/features/storybook/flow-library-happy-flow/src/index.ts
  test/typescript/features/storybook/flow-library-happy-flow/storybook-library-happyflow.test.ts
  test/typescript/features/storybook/flow-library-happy-flow/tsconfig.json
  website/docs/development/bundle-analyze.md
  website/docs/editor-flow/cli-API.md
  website/docs/editor-flow/getting-started.md
  website/docs/editor-flow/local-development.md
  website/docs/editor-flow/runtime-API.md
  website/docs/library-flow/overview.md
  website/docs/yoshi-config.md
Labels: PR: New Feature :rocket:

#2592 Internal: fix typing problem
  packages/yoshi-helpers/src/utils.ts
Labels: PR: Internal :house:

#2598 Implement automatic translations solution for Editor flow
  package.json
  packages/create-yoshi-app/templates/flow-editor/typescript/.application.json
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/helpers/flowAPI.mock.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.spec.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.spec.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.spec.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-editor-runtime/src/EditorAppWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/FlowAPI.ts
  packages/yoshi-flow-editor-runtime/src/SettingsWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/WidgetWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/constants.ts
  packages/yoshi-flow-editor-runtime/src/i18next/I18nextProvider.tsx
  packages/yoshi-flow-editor-runtime/src/i18next/index.ts
  packages/yoshi-flow-editor-runtime/src/index.ts
  packages/yoshi-flow-editor-runtime/src/test.ts
  packages/yoshi-flow-editor-runtime/src/test/i18next/I18nextProvider.tsx
  packages/yoshi-flow-editor-runtime/src/test/i18next/i18n.mock.ts
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor-runtime/test.d.ts
  packages/yoshi-flow-editor-runtime/test.js
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/editorAppWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/settingsWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/EditorAppEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/SettingsAppEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/EditorAppEntryContent.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/EditorAppEntryContent.test.ts.snap
  website/docs/editor-flow/runtime-api/flow-api.md
  website/docs/editor-flow/runtime-api/yoshi-flow-editor-runtime.md
  website/docs/editor-flow/structure-api/application.md
  website/docs/editor-flow/structure-api/overview.md
  website/sidebars.js
  yarn.lock
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2608 Yoshi Serverless: fix local work
  .eslintignore
  .eslintrc
  packages/yoshi-common/src/server-process.ts
  packages/yoshi-common/src/templates/serverless/serverless.js
  packages/yoshi-common/src/webpack-utils.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-helpers/src/utils.ts
  packages/yoshi-server-client/src/index.ts
  packages/yoshi-serverless/src/routes/launchEditor.ts
  packages/yoshi-serverless/src/server.ts
Labels: PR: New Feature :rocket:

#2614 Yoshi serverless types
  packages/yoshi-serverless/src/server.ts
  packages/yoshi-serverless/src/types.ts
Labels: PR: New Feature :rocket:

#2615 Lock file maintenance
  yarn.lock
Labels: PR: Chore :construction_worker:

#2616 Yoshi Serverless Client
  packages/yoshi-serverless-client/package.json
  packages/yoshi-serverless-client/src/external-types.d.ts
  packages/yoshi-serverless-client/src/index.ts
  packages/yoshi-serverless-client/src/utils.ts
  packages/yoshi-serverless-client/tsconfig.json
Labels: PR: New Feature :rocket:

#2619 Fix --debug option not being passed over to dev-environment in monorepo flow
  packages/yoshi-flow-monorepo/src/scripts/start.ts
Labels: PR: Bug Fix :bug:

#2602 Clean BM Flow template
  packages/create-yoshi-app/templates/flow-bm/typescript/app-config-templates/module_{%PROJECT_NAME%}.json
  packages/create-yoshi-app/templates/flow-bm/typescript/dev/environment.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/dev/server.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/components/LegacyTodoList.tsx
  packages/create-yoshi-app/templates/flow-bm/typescript/src/hooks/useTodos.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/methods/getTodo.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/methods/getTodos.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/src/moduleInit.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}.json
  packages/yoshi-flow-bm/package.json
Labels: PR: Templates :building_construction:

#2617 [Experimental] Use `babel-loader` with cache enabled to transpile TypeScript files
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#2618 monorepoflow – remove stripOrganization from the error logs
  packages/yoshi-flow-monorepo/src/scripts/start.ts
Labels: PR: Polish :nail_care:, ⚡️ Thunderbolt

#2613 Move TpaComponentsProvider and ExperimentsProvider from user's side
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.spec.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.spec.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/types/external-modules.d.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-editor-runtime/src/EditorAppWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/WidgetWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/experiments/ExperimentsProvider.tsx
  packages/yoshi-flow-editor-runtime/src/index.ts
  packages/yoshi-flow-editor-runtime/src/react/utils.tsx
  packages/yoshi-flow-editor-runtime/src/test.ts
  packages/yoshi-flow-editor-runtime/src/test/experiments/ExperimentsProvider.tsx
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/src/external-types.d.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
  website/docs/editor-flow/runtime-api/yoshi-flow-editor-runtime.md
  yarn.lock
Labels: PR: New Feature :rocket:, PR: Templates :building_construction:, 🖼 Flow Editor

#2622 Don't create `serverless.js` for projects that didn't opt-into yoshi-serverless
  packages/yoshi-common/src/webpack-utils.ts
Labels: PR: Bug Fix :bug:

#2604 Refactor `yoshi/types.d.ts` to be shared across the different flows
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/tsconfig.json
  packages/create-yoshi-app/templates/client/typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/client/typescript/tsconfig.json
  packages/create-yoshi-app/templates/flow-bm/typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/flow-bm/typescript/tsconfig.json
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}.json
  packages/create-yoshi-app/templates/fullstack/typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/fullstack/typescript/tsconfig.json
  packages/yoshi-common/types.d.ts
  packages/yoshi-flow-bm/types.d.ts
  packages/yoshi-flow-editor/types.d.ts
  packages/yoshi/types.d.ts
Labels: PR: Internal :house:

#2625 Mock auto-release module
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/src/createApp.ts
Labels: PR: Bug Fix :bug:, 🐛 Bug

#2621 Intagrate tpa-settings v0
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/helpers/i18n.mock.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.e2e.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.global.scss
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.spec.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Tabs/DesignTab.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Tabs/MainTab.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.spec.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.st.css
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/componentSettings.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/componentStyles.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.spec.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}.json
  packages/yoshi-flow-editor-runtime/src/styles/wix-base-ui.global.scss
Labels: PR: Templates :building_construction:, 🖼 Flow Editor

#2626 Fix for translations to include default values during build time
  packages/yoshi-flow-editor-runtime/src/EditorAppWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/FlowAPI.ts
  packages/yoshi-flow-editor-runtime/src/constants.ts
  packages/yoshi-flow-editor-runtime/src/i18next/index.ts
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/utils.ts
  packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/editorAppWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/settingsWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/EditorAppEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/SettingsAppEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/EditorAppEntryContent.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/EditorAppEntryContent.test.ts.snap
  website/docs/editor-flow/structure-api/application.md
Labels: PR: Bug Fix :bug:

#2627 add .dockerignore to BM template
  packages/create-yoshi-app/templates/business-manager-module/javascript/.dockerignore
  packages/create-yoshi-app/templates/business-manager-module/typescript/.dockerignore
Labels: PR: Bug Fix :bug:

#2628 Add dockerignore and templates
  packages/create-yoshi-app/templates/business-manager-module/javascript/.dockerignore
  packages/create-yoshi-app/templates/business-manager-module/javascript/Dockerfile
  packages/create-yoshi-app/templates/business-manager-module/typescript/.dockerignore
  packages/create-yoshi-app/templates/business-manager-module/typescript/Dockerfile
  packages/yoshi-common/src/copy-docker.ts
  packages/yoshi-config/src/paths.ts
  test/javascript/features/yoshi-server/create-docker/__snapshots__/create-docker.test.ts.snap
  test/javascript/features/yoshi-server/create-docker/create-docker.test.ts
  test/typescript/features/yoshi-server/create-docker/__snapshots__/create-docker.test.ts.snap
  test/typescript/features/yoshi-server/create-docker/create-docker.test.ts
Labels: PR: New Feature :rocket:

#2631 Fix testEnvBuilder naming lint error in server template
  packages/create-yoshi-app/templates/server/typescript/test/environment.ts
Labels: PR: Templates :building_construction:

#2630 Remove appName usage from the editor flow template
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.spec.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/componentSettings.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.spec.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/controller.ts
Labels: PR: Templates :building_construction:, 🖼 Flow Editor

#2633 Remove babel-preset-yoshi from docs
  website/versioned_docs/version-4.x/babel-preset-yoshi.md
Labels: PR: Docs :memo:

#2638 Update stylable to v3.7.0
  packages/yoshi-stylable-dependencies/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2637 Update devDependencies (weekly)
  package.json
  packages/create-yoshi-app/package.json
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-helpers/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2620 Yoshi Serverless: remove redundant code
  packages/yoshi-serverless/src/routes/api.ts
  packages/yoshi-serverless/src/server.ts
  packages/yoshi-serverless/src/types.ts
Labels: PR: Internal :house:

#2639 fix(CONTRIBUTING.md): test section typo
  CONTRIBUTING.md
Labels: PR: Docs :memo:

#2640 Upgrade petri-specs
  packages/yoshi-common/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2641 Upgrade petri spec version to 1.3.285
  packages/yoshi-common/package.json
  yarn.lock
Labels: PR: Bug Fix :bug:

#2632 Remove sourcemaps from site-assets node
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:, ⚡️ Thunderbolt

#2643 Create site-assets web compilation under a flag in start script
  packages/yoshi-flow-monorepo/src/scripts/start.ts
Labels: PR: Polish :nail_care:

#2635 Provide translations, experiments automatically.
  packages/create-yoshi-app/templates/flow-editor/typescript/src/assets/locales/messages_en.json
  packages/create-yoshi-app/templates/flow-editor/typescript/src/assets/locales/messages_uk.json
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.spec.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Settings/Settings.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/{each%flowData.components:name%each}/Widget/Widget.tsx
  packages/yoshi-flow-editor-runtime/src/FlowAPI.ts
  packages/yoshi-flow-editor-runtime/src/SettingsWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/i18next/index.ts
  packages/yoshi-flow-editor-runtime/src/react/utils.tsx
  packages/yoshi-flow-editor-runtime/src/test.ts
  packages/yoshi-flow-editor-runtime/src/test/SDK/WixSDKProvider.tsx
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/src/wrappers/settingsWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/SettingsAppEntryContent.ts
  website/docs/editor-flow/runtime-api/flow-api.md
  website/versioned_docs/version-4.x/editor-flow/runtime-API.md
  website/versioned_docs/version-4.x/editor-flow/runtime-api/flow-api.md
Labels: PR: New Feature :rocket:, PR: Templates :building_construction:, 🖼 Flow Editor

#2645 Yoshi serverless - import fresh with _non_webpack_require
  packages/yoshi-serverless/package.json
  packages/yoshi-serverless/src/external-types.d.ts
  packages/yoshi-serverless/src/non-webpack-require-fresh.ts
  packages/yoshi-serverless/src/routes/api.ts
  packages/yoshi-serverless/src/server.ts
  yarn.lock
Labels: PR: Bug Fix :bug:
