Repository wix/yoshi, pull requests merged in 2020-02, with the labels that each got.

#1912 Upgrade `lint-staged` to new major v`10.0.7`
  package.json
  packages/create-yoshi-app/templates/business-manager-module/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-editor/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/library/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/library/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/server/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
  packages/yoshi-template-intro/package.json
  yarn.lock
Labels: PR: New Feature :rocket:

#1911 Simplify moment exclusion test (Stabler CI)
  test/javascript/features/moment/moment.test.js
  test/typescript/features/moment/moment.test.js
  test/utils.js
Labels: PR: Internal :house:

#1907 add description to `shouldTranspileFile` function
  packages/yoshi-common/src/utils/should-transpile-file.ts
Labels: PR: Chore :construction_worker:, 📜 Documentation

#1915 Refactor test utils, remove code duplication
  test/utils.js
Labels: PR: Internal :house:

#1856 fix ts caching issues on build command
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-config/src/paths.ts
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-bm/src/webpack.config.ts
  packages/yoshi-flow-legacy/config/webpack.config.js
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:, 🏘️ Monorepo

#1917 `yoshi-server` handle default route
  packages/yoshi-server/src/server.ts
  test/javascript/features/yoshi-server/route-default/route-default.test.js
  test/javascript/features/yoshi-server/route-default/src/component.js
  test/javascript/features/yoshi-server/route-default/src/routes/index.js
  test/typescript/features/yoshi-server/route-default/route-default.test.js
  test/typescript/features/yoshi-server/route-default/src/component.tsx
  test/typescript/features/yoshi-server/route-default/src/routes/index.ts
Labels: PR: Yoshi Server

#1919 upgrade `husky` to new major v`4.2.1`
  package.json
  packages/create-yoshi-app/templates/business-manager-module/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-editor/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/library/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/library/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/server/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
  packages/yoshi-template-intro/package.json
  yarn.lock
Labels: PR: New Feature :rocket:

#1921 Yoshi Server: add a test for route with params
  packages/yoshi-server/src/server.ts
  test/javascript/features/yoshi-server/route-with-params/route-with-params.test.js
  test/javascript/features/yoshi-server/route-with-params/src/component.js
  test/javascript/features/yoshi-server/route-with-params/src/routes/users/[userid].js
  test/typescript/features/yoshi-server/route-with-params/route-with-params.test.js
  test/typescript/features/yoshi-server/route-with-params/src/component.tsx
  test/typescript/features/yoshi-server/route-with-params/src/routes/users/[userid].ts
Labels: PR: Yoshi Server

#1922 Remove content hash from webworker output for experimentalBuildHtml
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1913 Telemetry support with wix-bi-logger
  packages/yoshi-common/package.json
  packages/yoshi-common/src/telemetry.ts
  packages/yoshi-common/src/utils/helpers.ts
  packages/yoshi-flow-app/src/scripts/build.ts
  packages/yoshi-flow-legacy/src/commands/build.js
  packages/yoshi/bin/yoshi-cli.js
  yarn.lock
Labels: PR: New Feature :rocket:

#1918 eslint-tslint-config-yoshi - remove no-full-wsr-lib
  packages/eslint-config-yoshi/index.js
  packages/eslint-config-yoshi/package.json
  packages/tslint-config-yoshi/index.js
  packages/tslint-config-yoshi/package.json
Labels: PR: New Feature :rocket:

#1934 Removed remaining references to projects
  .eslintignore
  .eslintrc
  jest.config.js
Labels: PR: Bug Fix :bug:

#1930 prevent error when project is opened at the first time
  packages/create-yoshi-app/templates/business-manager-module/javascript/.editorconfig
  packages/create-yoshi-app/templates/business-manager-module/typescript/.editorconfig
  packages/create-yoshi-app/templates/client/javascript/.editorconfig
  packages/create-yoshi-app/templates/client/typescript/.editorconfig
  packages/create-yoshi-app/templates/flow-bm/typescript/.editorconfig
  packages/create-yoshi-app/templates/flow-editor/javascript/.editorconfig
  packages/create-yoshi-app/templates/flow-editor/typescript/.editorconfig
  packages/create-yoshi-app/templates/fullstack/javascript/.editorconfig
  packages/create-yoshi-app/templates/fullstack/typescript/.editorconfig
  packages/create-yoshi-app/templates/library/javascript/.editorconfig
  packages/create-yoshi-app/templates/library/typescript/.editorconfig
  packages/create-yoshi-app/templates/out-of-iframe/javascript/.editorconfig
  packages/create-yoshi-app/templates/out-of-iframe/typescript/.editorconfig
  packages/create-yoshi-app/templates/server/javascript/.editorconfig
  packages/create-yoshi-app/templates/server/typescript/.editorconfig
Labels: PR: Bug Fix :bug:

#1861 Storybook managed under experimental flag
  .eslintignore
  packages/yoshi-common/.storybook/config.js
  packages/yoshi-common/package.json
  packages/yoshi-common/src/dev-environment-logger.ts
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/storybook/storybook-process.ts
  packages/yoshi-common/src/storybook/storybook-worker.ts
  packages/yoshi-common/src/storybook/storybook.webpack.config.ts
  packages/yoshi-config/src/config.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-config/src/validConfig.ts
  packages/yoshi-flow-app/src/scripts/start.ts
  packages/yoshi-storybook-dependencies/package.json
  packages/yoshi-storybook-dependencies/src/index.ts
  packages/yoshi-storybook-dependencies/tsconfig.json
  test/javascript/features/storybook/error-in-story-and-app/package.json
  test/javascript/features/storybook/error-in-story-and-app/src/component.js
  test/javascript/features/storybook/error-in-story-and-app/src/component.stories.js
  test/javascript/features/storybook/error-in-story-and-app/storybook-error-in-story-and-app.test.ts
  test/javascript/features/storybook/error-in-story/package.json
  test/javascript/features/storybook/error-in-story/src/component.js
  test/javascript/features/storybook/error-in-story/src/component.stories.js
  test/javascript/features/storybook/error-in-story/storybook-error-in-story.test.ts
  test/javascript/features/storybook/happy-flow/package.json
  test/javascript/features/storybook/happy-flow/src/component.js
  test/javascript/features/storybook/happy-flow/src/component.stories.js
  test/javascript/features/storybook/happy-flow/storybook-happyflow.test.ts
  test/scripts.ts
  test/typescript/features/storybook/error-in-story-and-app/package.json
  test/typescript/features/storybook/error-in-story-and-app/src/component.stories.tsx
  test/typescript/features/storybook/error-in-story-and-app/src/component.tsx
  test/typescript/features/storybook/error-in-story-and-app/storybook-error-in-story-and-app.test.ts
  test/typescript/features/storybook/error-in-story/package.json
  test/typescript/features/storybook/error-in-story/src/component.stories.tsx
  test/typescript/features/storybook/error-in-story/src/component.tsx
  test/typescript/features/storybook/error-in-story/storybook-error-in-story.test.ts
  test/typescript/features/storybook/happy-flow/package.json
  test/typescript/features/storybook/happy-flow/src/component.stories.tsx
  test/typescript/features/storybook/happy-flow/src/component.tsx
  test/typescript/features/storybook/happy-flow/storybook-happyflow.test.ts
  test/utils.ts
  test/yoshi-publish/package.json
  yarn.lock
Labels: PR: New Feature :rocket:

#1931 create a webworker bundle that runs on server side
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-config/src/config.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-config/src/validConfig.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: New Feature :rocket:, 🏘️ Monorepo

#1943 Yoshi server: add `bo-auth` middleware
  packages/yoshi-server/package.json
  packages/yoshi-server/src/bo-auth.ts
  packages/yoshi-server/src/bootstrap.ts
  packages/yoshi-server/src/index.ts
  packages/yoshi-server/src/types.ts
  yarn.lock
Labels: PR: New Feature :rocket:, 💁‍♂️ Yoshi Server

#1949 do not generate manifest for server webworker bundle
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#1879 [Editor-flow] Update templates to be typed and have highlight
  .eslintignore
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}
  packages/yoshi-flow-editor/.vscode/extensions.json
  packages/yoshi-flow-editor/src/wrappers/componentWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/editorAppWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/settingsWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/ComponentWidgetEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/ControllerEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/EditorAppEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/SettingsAppEntryContent.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/template.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/template.ts
  packages/yoshi-flow-editor/src/wrappers/viewerScriptWrapping.ts
  packages/yoshi-flow-editor/tsconfig.json
Labels: PR: Flow Editor 🖼

#1951 Added documentation about BROWSER=false
  docs/api/cli.md
Labels: :wave: Help wanted, PR: Docs :memo:, 👶 Good first issue, 📜 Documentation

#1947 add an ability to modify the public path
  .eslintrc
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/viewerApp.e2e.js
  packages/yoshi-common/src/webpack-utils.ts
  test/javascript/features/public-path/public-path.test.ts
  test/javascript/features/public-path/src/component.js
  test/javascript/features/stats/stats.test.ts
  test/scripts.ts
  test/typescript/features/public-path/public-path.test.ts
  test/typescript/features/public-path/src/component.tsx
  test/typescript/features/stats/stats.test.ts
Labels: PR: New Feature :rocket:

#1952 jest-preset-override - allow resetMocks config override
  .gitignore
  docs/guides/jest-setup.md
  packages/jest-yoshi-preset/jest-preset.js
  packages/yoshi-config/src/jest/config.ts
  packages/yoshi-config/src/jest/validConfig.ts
  test/javascript/features/jest-preset-overrides/jest-yoshi.config.js
  test/javascript/features/jest-preset-overrides/src/component.js
  test/javascript/features/jest-preset-overrides/src/component.spec.js
  test/javascript/features/jest-preset-overrides/src/moduleToMock.js
  test/typescript/features/jest-preset-overrides/jest-yoshi.config.js
  website/versioned_docs/version-4.x/guides/jest-setup.md
Labels: PR: New Feature :rocket:

#1954 Yoshi Server: a temp fix for body parsing
  packages/yoshi-server/src/routes/api.ts
Labels: PR: Yoshi Server

#1956 add the spaced-comment lint rule for the monorepo
  .eslintrc
  packages/create-yoshi-app/templates/business-manager-module/typescript/src/config.ts
  packages/create-yoshi-app/templates/flow-editor/javascript/src/config/constants.js
  packages/create-yoshi-app/templates/flow-editor/typescript/src/config/constants.ts
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/config/constants.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/config/constants.ts
  packages/create-yoshi-app/templates/server/javascript/index-dev.js
  packages/create-yoshi-app/templates/server/typescript/index-dev.js
  packages/yoshi-common/src/webpack-utils.ts
  packages/yoshi-flow-legacy/test/test.spec.js
  test/scripts.ts
Labels: PR: Internal :house:

#1929 upgrade 18next and change fullstack templates
  packages/create-yoshi-app/templates/fullstack/javascript/__tests__/browser.e2e.js
  packages/create-yoshi-app/templates/fullstack/javascript/src/client.js
  packages/create-yoshi-app/templates/fullstack/javascript/src/components/App/App.js
  packages/create-yoshi-app/templates/fullstack/javascript/src/components/App/App.scss
  packages/create-yoshi-app/templates/fullstack/javascript/src/components/App/App.spec.js
  packages/create-yoshi-app/templates/fullstack/javascript/src/components/__mocks__/i18n.js
  packages/create-yoshi-app/templates/fullstack/javascript/src/i18n.js
  packages/create-yoshi-app/templates/fullstack/javascript/src/index.ejs
  packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/typescript/__tests__/browser.e2e.ts
  packages/create-yoshi-app/templates/fullstack/typescript/src/client.tsx
  packages/create-yoshi-app/templates/fullstack/typescript/src/components/App/App.scss
  packages/create-yoshi-app/templates/fullstack/typescript/src/components/App/App.spec.tsx
  packages/create-yoshi-app/templates/fullstack/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/fullstack/typescript/src/components/__mocks__/i18n.ts
  packages/create-yoshi-app/templates/fullstack/typescript/src/i18n.ts
  packages/create-yoshi-app/templates/fullstack/typescript/src/index.ejs
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
Labels: PR: New Feature :rocket:

#1958 Patch Yoshi@3 jest-preset config resolution.
  packages/jest-yoshi-preset/jest-preset.js
  packages/jest-yoshi-preset/package.json
Labels: PR: Bug Fix :bug:, PR: Internal :house:

#1965 create-yoshi-app: drop type declarations for wnp modules with types
  packages/create-yoshi-app/templates/fullstack/typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/server/typescript/src/external-types.d.ts
Labels: PR: Bug Fix :bug:

#1959 build all pkgs on monorepo flow
  packages/yoshi-flow-monorepo/src/build.ts
  packages/yoshi-flow-monorepo/src/scripts/build.ts
Labels: PR: Polish :nail_care:

#1961 [create-yoshi-app] [client] upgrade 18next and change client templates
  packages/create-yoshi-app/templates/client/javascript/__tests__/simple.e2e.js
  packages/create-yoshi-app/templates/client/javascript/src/client.js
  packages/create-yoshi-app/templates/client/javascript/src/components/App/App.js
  packages/create-yoshi-app/templates/client/javascript/src/components/App/App.scss
  packages/create-yoshi-app/templates/client/javascript/src/components/App/App.spec.js
  packages/create-yoshi-app/templates/client/javascript/src/components/__mocks__/i18n.js
  packages/create-yoshi-app/templates/client/javascript/src/i18n.js
  packages/create-yoshi-app/templates/client/javascript/src/index.vm
  packages/create-yoshi-app/templates/client/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/__tests__/simple.e2e.ts
  packages/create-yoshi-app/templates/client/typescript/src/client.tsx
  packages/create-yoshi-app/templates/client/typescript/src/components/App/App.scss
  packages/create-yoshi-app/templates/client/typescript/src/components/App/App.spec.tsx
  packages/create-yoshi-app/templates/client/typescript/src/components/App/App.tsx
  packages/create-yoshi-app/templates/client/typescript/src/components/__mocks__/i18n.ts
  packages/create-yoshi-app/templates/client/typescript/src/i18n.ts
  packages/create-yoshi-app/templates/client/typescript/src/index.vm
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
Labels: PR: New Feature :rocket:

#1966 Fix website publishing: enforce registry to be the public registry for the website
  website/.yarnrc
  website/yarn.lock
Labels: PR: Internal :house:

#1967 [create-yoshi-app][out-of-iframe] - remove wix-ui-core dependency
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
Labels: PR: New Feature :rocket:

#1972 FEDINF-488 - moved the validation of node version to the start of the…
  packages/create-yoshi-app/src/bin/create-yoshi-app.ts
Labels: PR: Bug Fix :bug:

#1971 Yoshi Server:don't apply Yoshi Server Jest Transform in e2e tests
  packages/jest-yoshi-preset/jest-preset.js
  packages/jest-yoshi-preset/transforms/babel-yoshi-server.js
  packages/jest-yoshi-preset/transforms/babel.js
  packages/jest-yoshi-preset/transforms/typescript-yoshi-server.js
  packages/jest-yoshi-preset/transforms/typescript.js
Labels: PR: Bug Fix :bug:

#1969 Update dependencies (weekly)
  package.json
  packages/babel-plugin-transform-hmr-runtime/package.json
  packages/babel-preset-yoshi/package.json
  packages/bootstrap-hot-loader/package.json
  packages/create-yoshi-app/package.json
  packages/jest-yoshi-preset/package.json
  packages/yoshi-angular-dependencies/package.json
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-legacy/test/build.spec.js
  packages/yoshi-flow-legacy/test/loaders.spec.js
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server-tools/package.json
  packages/yoshi-server/package.json
  packages/yoshi-style-dependencies/package.json
  packages/yoshi/package.json
  renovate.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#1973 fixed bug where empty dependencies won't update
  packages/yoshi-flow-legacy/src/commands/utils/index.js
  packages/yoshi-flow-monorepo/src/verify-typescript-references.ts
Labels: PR: Polish :nail_care:

#1976 fix(create-yoshi-app): Increase timeout time for h2 selector for viewer.
  packages/create-yoshi-app/templates/out-of-iframe/javascript/__tests__/e2e-setup.js
  packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerApp/viewerApp.e2e.js
  packages/create-yoshi-app/templates/out-of-iframe/typescript/__tests__/e2e-setup.ts
  packages/create-yoshi-app/templates/out-of-iframe/typescript/src/viewerApp/viewerApp.e2e.ts
Labels: PR: Internal :house:

#1975 Lock file maintenance
  packages/yoshi-flow-bm-runtime/package.json
  website/yarn.lock
  yarn.lock
Labels: PR: Chore :construction_worker:

#1982 add content hash to webworker bundle
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1981 Yoshi Server: add support for mocha
  packages/yoshi-flow-legacy/config/test-setup.js
  packages/yoshi-flow-legacy/package.json
Labels: PR: Polish :nail_care:, 💁‍♂️ Yoshi Server

#1984 use a separate runtime chunk only for target web
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#1985 Tests: increase timeout for flaky TS test
  test/typescript/features/request-errors/request-errors.test.ts
Labels: PR: Internal :house:

#1978 Removing --ssl --https options
  docs/api/cli.md
  docs/api/configuration.md
  docs/guides/app-flow.md
  packages/yoshi-flow-app/src/scripts/start.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  packages/yoshi-flow-editor/src/commands/start.ts
  packages/yoshi-flow-legacy/bin/yoshi-cli.js
  packages/yoshi-flow-legacy/src/commands/start.js
  packages/yoshi-flow-legacy/test/start.spec.js
  packages/yoshi-flow-monorepo/src/scripts/start.ts
Labels: PR: Breaking Change :boom:

#1988 Yoshi Server Testing: better error messages
  packages/yoshi-server-testing/src/index.ts
Labels: PR: New Feature :rocket:, 💁‍♂️ Yoshi Server

#1992 Yoshi Server: add a `requireHttps` middleware
  packages/yoshi-server/package.json
  packages/yoshi-server/src/server.ts
  yarn.lock
Labels: PR: New Feature :rocket:, 💁‍♂️ Yoshi Server

#1993 Update dependencies (weekly)
  package.json
  packages/create-yoshi-app/package.json
  packages/yoshi-angular-dependencies/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-server-tools/package.json
  packages/yoshi-server/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#1960 Deprecating --entry-point and --server flags
  CONTRIBUTING.md
  docs/api/cli.md
  docs/guides/app-flow.md
  packages/create-yoshi-app/templates/business-manager-module/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/server/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
  packages/yoshi-common/src/webpack-utils.ts
  packages/yoshi-flow-app/src/scripts/start.ts
  packages/yoshi-flow-bm/src/scripts/start.ts
  packages/yoshi-flow-legacy/src/commands/start.js
  packages/yoshi-flow-legacy/src/tasks/app-server/index.js
  packages/yoshi-flow-monorepo/src/scripts/start.ts
  packages/yoshi-helpers/__tests__/server-start-file.test.ts
  packages/yoshi-helpers/src/queries.ts
  packages/yoshi-helpers/src/server-start-file.ts
  test/fixtures/javascript/base-template/index-dev.js
  test/fixtures/typescript/base-template/index-dev.js
  test/fixtures/yoshi-server-javascript/base-template/index-dev.js
  test/fixtures/yoshi-server-typescript/base-template/index-dev.js
  test/scripts.ts
  website/versioned_docs/version-4.x/api/cli.md
Labels: PR: Polish :nail_care:

#1997 Update configuration.md
  docs/api/configuration.md
Labels: PR: Docs :memo:

#1996 Yoshi Server - change the api
  packages/yoshi-server-client/src/index.ts
  packages/yoshi-server-react/src/hooks.ts
  packages/yoshi-server-testing/src/index.ts
  packages/yoshi-server/src/wrap.ts
  test/javascript/features/yoshi-server/api-client-server-react/src/api/greeting.api.js
  test/javascript/features/yoshi-server/api-client-server/src/api/greeting.api.js
  test/javascript/features/yoshi-server/api-client-server/src/component.js
  test/javascript/features/yoshi-server/api-server-server/src/api/greeting.api.js
  test/javascript/features/yoshi-server/api-server-server/src/routes/app.js
  test/javascript/features/yoshi-server/return-values/return-a-string/src/api/greeting.api.js
  test/javascript/features/yoshi-server/return-values/return-a-string/src/routes/app.js
  test/typescript/features/yoshi-server/api-client-server-react/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/api-client-server/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/api-client-server/src/component.tsx
  test/typescript/features/yoshi-server/api-server-server/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/api-server-server/src/routes/app.ts
  test/typescript/features/yoshi-server/return-values/return-a-string/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/return-values/return-a-string/src/routes/app.ts
Labels: PR: New Feature :rocket:, 💁‍♂️ Yoshi Server

#1927 Emit Webpack stats file for worker compilation
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:, 🏘️ Monorepo

#1991 Support single viewerScript + few fixes and enhancements.
  jest.unit.config.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/editorApp.e2e.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/viewerApp.e2e.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/viewerScript.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/dev/sites.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Settings.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Settings/Settings.global.scss
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Settings/Settings.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Settings/Settings.scss
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Settings/Settings.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Widget.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Widget.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Widget.st.css
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/controller.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/controller.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/templates/editorApp.vm
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/editorApp.e2e.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/viewerApp.e2e.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/viewerScript.spec.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/dev/sites.js
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/Settings.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/Settings/Settings.global.scss
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/Settings/Settings.scss
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/Settings/Settings.spec.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/Settings/Settings.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/Widget.spec.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/Widget.st.css
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/Widget.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/controller.spec.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/controller.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/templates/settingsPanel.vm
  packages/yoshi-flow-editor-runtime/src/WidgetWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/viewerScript.ts
  packages/yoshi-flow-editor/src/buildEditorEntires.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/server/server.ts
  packages/yoshi-flow-editor/src/server/templates/editorApp.vm
  packages/yoshi-flow-editor/src/server/templates/settingsApp.vm
  packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/WidgetViewerScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/template.test.ts
  packages/yoshi-flow-editor/src/wrappers/widgetViewerScriptWrapping.ts
Labels: PR: Flow Editor 🖼

#2005 Eslint typescript
  .eslintrc
  packages/eslint-config-yoshi-base/index.js
  packages/eslint-config-yoshi-base/package.json
  packages/eslint-config-yoshi-base/test.js
  packages/eslint-config-yoshi/__tests__/eslint-config-yoshi.test.js
  packages/eslint-config-yoshi/__tests__/rules/adjacent-overload-signatures/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/adjacent-overload-signatures/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/constructor-super/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/constructor-super/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/curly/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/curly/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/default-case/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/default-case/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/dot-notation/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/dot-notation/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/eqeqeq/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/eqeqeq/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-caller/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-cond-assign/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-duplicate-case/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-duplicate-case/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-duplicates/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-duplicates/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-dynamic-delete/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-eval/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-fallthrough/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-fallthrough/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-misused-new/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-new-wrappers/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-new-wrappers/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-non-null-assertion/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-non-null-assertion/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-restricted-syntax/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-return-await/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-shadow/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-template-curly-in-string/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-template-curly-in-string/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-throw-literal/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-throw-literal/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-unsafe-finally/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/no-var/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/prefer-const/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/prefer-const/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/prefer-for-of/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/prefer-for-of/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/prefer-function-type/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/prefer-function-type/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/prefer-object-spread/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/prefer-object-spread/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/radix/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/radix/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/rules-of-hooks/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/rules-of-hooks/valid.ts
  packages/eslint-config-yoshi/__tests__/rules/triple-slash-reference/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/use-isnan/invalid.ts
  packages/eslint-config-yoshi/__tests__/rules/use-isnan/valid.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2008 Lock file maintenance
  website/yarn.lock
  yarn.lock
Labels: PR: Chore :construction_worker:

#1980 Yoshi serve command
  packages/yoshi-common/package.json
  packages/yoshi-common/src/cdn.ts
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/server-process.ts
  packages/yoshi-flow-app/src/bin/yoshi-app.ts
  packages/yoshi-flow-app/src/scripts/serve.ts
  packages/yoshi-helpers/__tests__/server-start-file-parser.test.ts
  packages/yoshi-helpers/package.json
  packages/yoshi-helpers/src/server-start-file-parser.ts
  test/javascript/features/serve/http/serve.test.ts
  test/javascript/features/serve/http/src/component.js
  test/javascript/features/serve/https/package.json
  test/javascript/features/serve/https/serve.test.ts
  test/javascript/features/serve/https/src/component.js
  test/javascript/features/serve/https/src/index.ejs
  test/scripts.ts
  test/typescript/features/serve/http/serve.test.ts
  test/typescript/features/serve/http/src/component.tsx
  test/typescript/features/serve/https/package.json
  test/typescript/features/serve/https/serve.test.ts
  test/typescript/features/serve/https/src/component.tsx
  test/typescript/features/serve/https/src/index.ejs
  yarn.lock
Labels: PR: New Feature :rocket:

#2011 add templates label to changelog
  lerna.json
Labels: PR: Internal :house:

#2014 fix website publishing
  renovate.json
  scripts/createVersion.js
  website/yarn.lock
Labels: PR: Internal :house:

#2012 Eslint: Remove @typescript-eslint/consistent-type-definitions rule
  packages/eslint-config-yoshi-base/index.js
Labels: PR: New Feature :rocket:

#2009 enabled eslint rules
  .eslintrc
  packages/bootstrap-hot-loader/src/types.ts
  packages/create-yoshi-app/__tests__/verifyNodeVersion.test.ts
  packages/create-yoshi-app/src/installExternalDependnecies.ts
  packages/create-yoshi-app/src/utils.ts
  packages/yoshi-common/src/AsyncWebWorkerTarget/WebWorkerMainTemplatePlugin.ts
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/print-build-results.ts
  packages/yoshi-common/src/server-process.ts
  packages/yoshi-common/src/webpack-manager.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-config/src/loadConfig.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-bm/src/createFlowBMModel.ts
  packages/yoshi-flow-bm/src/webpack.config.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/webpack.config.ts
  packages/yoshi-flow-editor/types.d.ts
  packages/yoshi-flow-monorepo/src/verify-typescript-references.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
  packages/yoshi-helpers/src/rewrite-forward-proxy.ts
  packages/yoshi-server-react/src/hooks.ts
  packages/yoshi-server/src/server.ts
  packages/yoshi/types.d.ts
  scripts/build.ts
  scripts/customPublish.ts
  test/javascript/features/hmr/web-worker/web-worker.test.ts
  test/typescript/features/hmr/hmr-web-worker/hmr-web-worker.test.ts
  test/typescript/features/hmr/hmr/hmr.test.ts
Labels: PR: Chore :construction_worker:

#2004 yoshi-create-app: server templates cleanups
  packages/create-yoshi-app/templates/server/javascript/templates/{%projectName%}.json.erb
  packages/create-yoshi-app/templates/server/javascript/test/environment.js
  packages/create-yoshi-app/templates/server/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/server/typescript/src/config.ts
  packages/create-yoshi-app/templates/server/typescript/src/external-types.d.ts
  packages/create-yoshi-app/templates/server/typescript/src/server.ts
  packages/create-yoshi-app/templates/server/typescript/src/types.ts
  packages/create-yoshi-app/templates/server/typescript/templates/{%projectName%}.json.erb
  packages/create-yoshi-app/templates/server/typescript/test/environment.ts
  packages/create-yoshi-app/templates/server/typescript/test/it/server.it.ts
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
Labels: PR: Templates :building_construction:

#2015 Scoping thunderbolt modules under @/wix
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#2020 Remove ts in index-dev
  docs/guides/app-flow.md
Labels: PR: Docs :memo:, 📜 Documentation

#2018 Yoshi Serve in yoshi-common
  packages/yoshi-common/serve.d.ts
  packages/yoshi-common/serve.js
  packages/yoshi-common/src/commands/serve.ts
  test/javascript/features/serve/http/serve.test.ts
  test/javascript/features/serve/monorepo/monorepo.test.ts
  test/javascript/features/serve/monorepo/package.json
  test/scripts.ts
  test/typescript/features/serve/http/serve.test.ts
  test/typescript/features/serve/monorepo/monorepo.test.ts
  test/typescript/features/serve/monorepo/package.json
Labels: PR: New Feature :rocket:

#2016 Yoshi serve documentation
  docs/api/node.md
Labels: PR: Docs :memo:, 📜 Documentation

#2019 Yoshi Server HMR
  packages/yoshi-server/src/routes/api.ts
  packages/yoshi-server/src/server.ts
  packages/yoshi-server/src/utils.ts
  test/fixtures/yoshi-server-javascript/base-template/src/templates/app.ejs
  test/fixtures/yoshi-server-typescript/base-template/src/templates/app.ejs
  test/javascript/features/yoshi-server/hmr/hmr.test.ts
  test/javascript/features/yoshi-server/hmr/src/api/greeting.api.js
  test/javascript/features/yoshi-server/hmr/src/component.js
  test/javascript/features/yoshi-server/hmr/src/routes/app.js
  yarn.lock
Labels: PR: New Feature :rocket:

#2010 Expose `stylableSeparateCss` configuration
  docs/api/configuration.md
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-config/src/config.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-config/src/validConfig.ts
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-legacy/config/webpack.config.js
  packages/yoshi-flow-monorepo/src/webpack.config.ts
  packages/yoshi/types.d.ts
  test/javascript/features/stylable/separate-css/package.json
  test/javascript/features/stylable/separate-css/separate-css.test.ts
  test/javascript/features/stylable/separate-css/src/component.js
  test/javascript/features/stylable/separate-css/src/style.st.css
  test/typescript/features/stylable/separate-css/package.json
  test/typescript/features/stylable/separate-css/separate-css.test.ts
  test/typescript/features/stylable/separate-css/src/component.tsx
  test/typescript/features/stylable/separate-css/src/style.st.css
Labels: PR: New Feature :rocket:

#2024 Remove stylable runtime from types.d.ts
  packages/yoshi/types.d.ts
Labels: PR: Bug Fix :bug:

#2017 Output html files for editor apps (widget wrapper + settings)
  packages/yoshi-flow-editor-runtime/src/EditorAppWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/WidgetWrapper.tsx
  packages/yoshi-flow-editor/docs/editor-and-settings.md
  packages/yoshi-flow-editor/src/commands/build.ts
  packages/yoshi-flow-editor/src/commands/htmlGenerator.ts
  packages/yoshi-flow-editor/src/server/vm.ts
  packages/yoshi-flow-editor/src/wrappers/editorAppWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/EditorAppEntryContent.ts
Labels: PR: Flow Editor 🖼, 🖼 Flow Editor, 🗣 Discussion
