Repository wix/yoshi, pull requests merged in 2020-03, with the labels that each got.

#2025 fix stylable type mismatches
  test/typescript/features/stylable/separate-css/src/test-types.d.ts
  test/typescript/features/stylable/separate-css/tsconfig.json
Labels: PR: Internal :house:

#2027 Update dependencies (weekly)
  packages/eslint-config-yoshi-base/package.json
  packages/yoshi-angular-dependencies/package.json
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server-tools/package.json
  packages/yoshi-server/package.json
  packages/yoshi/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2028 start `server=dist/server` on TypeScript templates
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
Labels: PR: Templates :building_construction:

#2032 Try to tell renovate to ignore website/yarn.lock
  renovate.json
Labels: PR: Chore :construction_worker:

#2035 Remove website lockfile
  renovate.json
  scripts/createVersion.js
  website/.yarnrc
  website/yarn.lock
Labels: PR: Internal :house:

#2036 Change integration package name to avoid haste map warning
  test/typescript/features/serve/monorepo/package.json
Labels: PR: Internal :house:

#2034 Update dependencies (weekly)
  packages/bootstrap-hot-loader/package.json
  packages/eslint-config-yoshi-base/package.json
  packages/yoshi-angular-dependencies/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-server/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2031 Lock file maintenance
  yarn.lock
Labels: PR: Chore :construction_worker:

#2023 add stylable dependencies (Support for stylable 3)
  package.json
  packages/jest-yoshi-preset/jest-preset.js
  packages/yoshi-common/package.json
  packages/yoshi-common/src/@stylable/jest.ts
  packages/yoshi-common/src/@stylable/node.ts
  packages/yoshi-common/src/@stylable/utils.ts
  packages/yoshi-common/src/@stylable/webpack-plugin.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-legacy/config/jest.config.js
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-legacy/src/ignore-extensions.js
  packages/yoshi-flow-legacy/test/test.spec.js
  packages/yoshi-stylable-dependencies/.npmrc
  packages/yoshi-stylable-dependencies/package.json
  packages/yoshi/config/webpack.config.storybook.js
  packages/yoshi/package.json
  yarn.lock
Labels: PR: New Feature :rocket:

#2040 Add scripts to Yoshi tests fixtures
  CONTRIBUTING.md
  test/scripts.ts
Labels: PR: Internal :house:

#2046 fix webpack.config.storybook.js webpack plugin import
  packages/yoshi/config/webpack.config.storybook.js
Labels: PR: Bug Fix :bug:

#2044 Yoshi tests: handle errors in tests + better logs
  package.json
  test/scripts.ts
  test/utils.ts
  yarn.lock
Labels: PR: Internal :house:

#2037 make `yoshi test --help` show how to run specific test files
  packages/yoshi-flow-legacy/bin/yoshi-cli.js
Labels: PR: New Feature :rocket:

#2048 Yoshi tests: remove duplications
  test/fixtures/javascript/base-template/src/component.js
  test/fixtures/typescript/base-template/src/component.tsx
  test/fixtures/yoshi-server-javascript/base-template/src/component.js
  test/fixtures/yoshi-server-typescript/base-template/src/component.tsx
  test/javascript/features/statics/src/component.js
  test/javascript/features/stats/src/component.js
  test/javascript/features/verify-dependencies/src/component.js
  test/javascript/features/yoshi-server/api-server-server/src/component.js
  test/javascript/features/yoshi-server/hmr/src/component.js
  test/javascript/features/yoshi-server/return-values/return-a-string/src/component.js
  test/javascript/features/yoshi-server/return-values/send-a-response-directly/src/component.js
  test/javascript/features/yoshi-server/route-default/src/component.js
  test/javascript/features/yoshi-server/route-with-params/src/component.js
  test/javascript/features/yoshi-server/route/src/component.js
  test/typescript/features/analyze/src/component.tsx
  test/typescript/features/dev-server/src/component.tsx
  test/typescript/features/entries/src/component.tsx
  test/typescript/features/request-errors/src/component.tsx
  test/typescript/features/statics/src/component.tsx
  test/typescript/features/stats/src/component.tsx
  test/typescript/features/verify-dependencies/src/component.tsx
  test/typescript/features/yoshi-server/api-server-server/src/component.tsx
  test/typescript/features/yoshi-server/return-values/return-a-string/src/component.tsx
  test/typescript/features/yoshi-server/return-values/send-a-response-directly/src/component.tsx
  test/typescript/features/yoshi-server/route-default/src/component.tsx
  test/typescript/features/yoshi-server/route-with-params/src/component.tsx
  test/typescript/features/yoshi-server/route/src/component.tsx
Labels: PR: Internal :house:

#2052 Run integration tests serially by default
  CONTRIBUTING.md
  jest.config.js
  package.json
  test/config/serial-runner.js
  test/globalSetup.ts
  yarn.lock
Labels: PR: Internal :house:

#2045 Run webworker server compiler in start command
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-flow-monorepo/src/scripts/start.ts
Labels: PR: Bug Fix :bug:, 🏘️ Monorepo

#2057 Fix yoshi serve: app-server use `NODE_ENV="development"`
  packages/yoshi-common/src/server-process.ts
Labels: PR: Bug Fix :bug:

#2055 Update dependencies (weekly)
  packages/babel-preset-yoshi/package.json
  packages/yoshi-angular-dependencies/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-server-tools/package.json
  packages/yoshi/package.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2061 Refactor server process class usage (default `env`)
  packages/yoshi-common/src/commands/serve.ts
  packages/yoshi-common/src/server-process.ts
Labels: PR: Internal :house:

#2059 Use SRC_MD5 to consturct public patch
  packages/yoshi-flow-legacy/test/webpack-config.spec.js
  packages/yoshi-helpers/src/queries.ts
  packages/yoshi-helpers/src/utils.ts
Labels: PR: Bug Fix :bug:

#2063 update vscode intregration
  packages/create-yoshi-app/templates/client/javascript/.vscode/extensions.json
  packages/create-yoshi-app/templates/client/javascript/.vscode/settings.json
  packages/create-yoshi-app/templates/client/typescript/.vscode/extensions.json
  packages/create-yoshi-app/templates/client/typescript/.vscode/settings.json
  packages/create-yoshi-app/templates/fullstack/javascript/.vscode/extensions.json
  packages/create-yoshi-app/templates/fullstack/javascript/.vscode/settings.json
  packages/create-yoshi-app/templates/fullstack/typescript/.vscode/extensions.json
  packages/create-yoshi-app/templates/fullstack/typescript/.vscode/settings.json
  packages/create-yoshi-app/templates/library/javascript/.vscode/extensions.json
  packages/create-yoshi-app/templates/library/javascript/.vscode/settings.json
  packages/create-yoshi-app/templates/library/typescript/.vscode/extensions.json
  packages/create-yoshi-app/templates/library/typescript/.vscode/settings.json
  packages/create-yoshi-app/templates/server/javascript/.vscode/extensions.json
  packages/create-yoshi-app/templates/server/javascript/.vscode/settings.json
  packages/create-yoshi-app/templates/server/typescript/.vscode/extensions.json
  packages/create-yoshi-app/templates/server/typescript/.vscode/settings.json
Labels: PR: Templates :building_construction:

#2062 remove stylelint dependency
  docs/api/cli.md
  packages/stylelint-config-yoshi/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-legacy/src/tasks/stylelint.js
  packages/yoshi-flow-legacy/test/lint.spec.js
  website/versioned_docs/version-4.x/api/cli.md
Labels: PR: Breaking Change :boom:

#2067 tsconfig skip lib check for templates
  packages/create-yoshi-app/templates/business-manager-module/typescript/tsconfig.json
  packages/create-yoshi-app/templates/client/typescript/tsconfig.json
  packages/create-yoshi-app/templates/flow-bm/typescript/tsconfig.json
  packages/create-yoshi-app/templates/flow-editor/typescript/tsconfig.json
  packages/create-yoshi-app/templates/fullstack/typescript/tsconfig.json
  packages/create-yoshi-app/templates/library/typescript/tsconfig.json
  packages/create-yoshi-app/templates/out-of-iframe/typescript/tsconfig.json
  packages/create-yoshi-app/templates/server/typescript/tsconfig.json
Labels: PR: Templates :building_construction:

#2065 use eslint for TypeScript templates
  packages/create-yoshi-app/templates/business-manager-module/typescript/tslint.json
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/tslint.json
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-bm/typescript/tslint.json
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-editor/typescript/tslint.json
  packages/create-yoshi-app/templates/fullstack/typescript/tslint.json
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/library/typescript/tslint.json
  packages/create-yoshi-app/templates/library/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/tslint.json
  packages/create-yoshi-app/templates/server/typescript/tslint.json
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
Labels: PR: Templates :building_construction:

#2066 Add the spaced comment eslint rule
  packages/eslint-config-yoshi-base/index.js
Labels: PR: New Feature :rocket:

#2070 add deprecation PR label
  lerna.json
Labels: PR: Internal :house:

#2069 Deprecate `yoshi release` command
  packages/create-yoshi-app/templates/business-manager-module/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-editor/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/library/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/library/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/server/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
  packages/yoshi-flow-legacy/src/commands/release.js
Labels: PR: Deprecation :warning:, PR: Templates :building_construction:

#2058 Provide 404 and 500 errors on Yoshi Server Routes
  packages/yoshi-server/package.json
  packages/yoshi-server/src/httpErrors.ts
  packages/yoshi-server/src/server.ts
  test/javascript/features/yoshi-server/server-error/server-error.test.ts
  test/javascript/features/yoshi-server/server-error/src/routes/app.js
  test/scripts.ts
  test/typescript/features/yoshi-server/server-error/server-error.test.ts
  test/typescript/features/yoshi-server/server-error/src/routes/app.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2072 Remove the `yoshi release` command of the monorepo flow
  packages/yoshi-flow-monorepo/src/bin/yoshi-monorepo.ts
  packages/yoshi-flow-monorepo/src/scripts/release.ts
Labels: PR: Breaking Change :boom:, 🏘️ Monorepo

#2077 Wait for release command - urgent fix
  packages/yoshi-flow-legacy/src/commands/release.js
Labels: PR: Bug Fix :bug:

#2076 duplicated module field in library template
  packages/create-yoshi-app/templates/library/javascript/{%packagejson%}
Labels: PR: Templates :building_construction:

#2079 Lock file maintenance
  yarn.lock
Labels: PR: Chore :construction_worker:

#2083 Revert telemetry and bi-logger private dependency
  packages/yoshi-common/package.json
  packages/yoshi-common/src/telemetry.ts
  packages/yoshi-flow-app/src/scripts/build.ts
  packages/yoshi-flow-legacy/src/commands/build.js
  yarn.lock
Labels: PR: Bug Fix :bug:

#2081 Add migration script link to release deprecation
  packages/yoshi-flow-legacy/src/commands/release.js
Labels: PR: Polish :nail_care:

#2074 Remove not needed type resolutions
  package.json
  packages/yoshi-common/package.json
  packages/yoshi-config/package.json
  packages/yoshi-flow-app/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-bm/package.json
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-monorepo/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server-react/package.json
  packages/yoshi-server-tools/package.json
  test/yoshi-publish/package.json
  yarn.lock
Labels: PR: Internal :house:

#2085 Integration tests: fix flaky storybook test
  test/javascript/features/storybook/happy-flow/storybook-happyflow.test.ts
  test/scripts.ts
  test/typescript/features/storybook/happy-flow/storybook-happyflow.test.ts
Labels: PR: Bug Fix :bug:, PR: Internal :house:

#2089 Remove dep check
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-flow-legacy/src/commands/build.js
  packages/yoshi-flow-legacy/src/tasks/dep-check/index.js
  yarn.lock
Labels: PR: Bug Fix :bug:

#2078 Yoshi Server: Support nested default routes
  packages/yoshi-server/src/server.ts
  packages/yoshi-server/src/utils.ts
  test/javascript/features/yoshi-server/route-default/route-default.test.ts
  test/javascript/features/yoshi-server/route-default/src/routes/app/index.js
  test/typescript/features/yoshi-server/route-default/route-default.test.ts
  test/typescript/features/yoshi-server/route-default/src/routes/app/index.ts
Labels: PR: Bug Fix :bug:

#2075 Align npm scripts in templates
  packages/create-yoshi-app/scripts/e2e.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/client/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-editor/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/library/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/library/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
  packages/create-yoshi-app/templates/server/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/server/typescript/{%packagejson%}
Labels: PR: Templates :building_construction:

#2091 [yoshi template "library"]: use `maven-v4.0.0.xsd` in pom.xml
  packages/create-yoshi-app/templates/library/javascript/pom.xml
  packages/create-yoshi-app/templates/library/typescript/pom.xml
Labels: PR: Polish :nail_care:

#1970 Basic setup for testing monorepo flow use cases
  test/fixtures/monorepo-typescript/base-template/index.js
  test/fixtures/monorepo-typescript/base-template/lerna.json
  test/fixtures/monorepo-typescript/base-template/package.json
  test/fixtures/monorepo-typescript/base-template/packages/app/package.json
  test/fixtures/monorepo-typescript/base-template/packages/app/src/client.tsx
  test/fixtures/monorepo-typescript/base-template/packages/app/src/component.tsx
  test/fixtures/monorepo-typescript/base-template/packages/app/src/index.ejs
  test/fixtures/monorepo-typescript/base-template/packages/app/src/server.tsx
  test/fixtures/monorepo-typescript/base-template/packages/app/tsconfig.json
  test/fixtures/monorepo-typescript/base-template/packages/lib/package.json
  test/fixtures/monorepo-typescript/base-template/packages/lib/src/index.tsx
  test/fixtures/monorepo-typescript/base-template/packages/lib/tsconfig.json
  test/fixtures/monorepo-typescript/base-template/tsconfig.json
  test/scripts.ts
  test/typescript/features/monorepo/basic/basic.test.ts
Labels: PR: Internal :house:

#2030 Add docs for overview and dev center registration + troubleshooting.
  packages/yoshi-flow-editor/docs/DEV_CENTER_REGISTRATION.md
  packages/yoshi-flow-editor/docs/EDITOR-AND-SETTINGS-APPS.md
  packages/yoshi-flow-editor/docs/OVERVIEW.md
Labels: PR: Docs :memo:, PR: Flow Editor 🖼

#2093 Add `.editor-flow-dev.com` to allowedHosts.
  packages/yoshi-common/src/webpack-dev-server.ts
Labels: PR: New Feature :rocket:

#2090 Remove erb from BM templates
  packages/create-yoshi-app/templates/business-manager-module/javascript/app-config-templates/module_{%PROJECT_NAME%}.json
  packages/create-yoshi-app/templates/business-manager-module/javascript/dev/environment.js
  packages/create-yoshi-app/templates/business-manager-module/javascript/templates/module_{%PROJECT_NAME%}.json.erb
  packages/create-yoshi-app/templates/business-manager-module/typescript/app-config-templates/module_{%PROJECT_NAME%}.json
  packages/create-yoshi-app/templates/business-manager-module/typescript/dev/environment.ts
  packages/create-yoshi-app/templates/business-manager-module/typescript/templates/module_{%PROJECT_NAME%}.json.erb
Labels: PR: New Feature :rocket:

#2092 [yoshi-flow-editor] Update templates and css paths
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/settingsPanel.e2e.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/viewerApp.e2e.js
  packages/create-yoshi-app/templates/flow-editor/javascript/__tests__/viewerScript.spec.js
  packages/create-yoshi-app/templates/flow-editor/javascript/dev/certificates/cert.pem
  packages/create-yoshi-app/templates/flow-editor/javascript/dev/certificates/key.pem
  packages/create-yoshi-app/templates/flow-editor/javascript/dev/fake-tpa-response.json
  packages/create-yoshi-app/templates/flow-editor/javascript/dev/server.js
  packages/create-yoshi-app/templates/flow-editor/javascript/dev/vm.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/.component.json
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/button/Widget.st.css
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/todo/Settings.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/todo/Widget.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/todo/controller.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/todo/service.js
  packages/create-yoshi-app/templates/flow-editor/javascript/src/components/todo/styles.scss
  packages/create-yoshi-app/templates/flow-editor/javascript/{%packagejson%}
  packages/create-yoshi-app/templates/flow-editor/typescript/.nvmrc
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/settingsPanel.e2e.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/__tests__/viewerScript.spec.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/.component.json
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/Widget.st.css
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/button/controller.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/todo/Settings.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/todo/Widget.tsx
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/todo/controller.ts
  packages/create-yoshi-app/templates/flow-editor/typescript/src/components/todo/styles.scss
  packages/yoshi-flow-editor-runtime/src/WidgetWrapper.tsx
  packages/yoshi-flow-editor/src/server/templates/settingsApp.vm
  packages/yoshi-flow-editor/src/wrappers/componentWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/ComponentWidgetEntry.ts
Labels: PR: Flow Editor 🖼

#2087 Integration tests: try to fix stylable flaky test
  test/javascript/features/stylable/separate-css/separate-css.test.ts
  test/typescript/features/stylable/separate-css/separate-css.test.ts
Labels: PR: Internal :house:

#2096 Revert "Remove ts in index-dev"
  docs/guides/app-flow.md
Labels: PR: New Feature :rocket:

#2097 fix(yoshi-commin): Don’t add cwd to absolute file paths.
  packages/yoshi-common/src/server-process.ts
Labels: PR: Bug Fix :bug:

#2100 Remove tslint rule from settings.json
  packages/create-yoshi-app/templates/client/javascript/.vscode/settings.json
  packages/create-yoshi-app/templates/client/typescript/.vscode/settings.json
  packages/create-yoshi-app/templates/fullstack/javascript/.vscode/settings.json
  packages/create-yoshi-app/templates/fullstack/typescript/.vscode/settings.json
  packages/create-yoshi-app/templates/library/javascript/.vscode/settings.json
  packages/create-yoshi-app/templates/library/typescript/.vscode/settings.json
  packages/create-yoshi-app/templates/server/javascript/.vscode/settings.json
  packages/create-yoshi-app/templates/server/typescript/.vscode/settings.json
Labels: PR: Polish :nail_care:

#2098 chore(deps): update dependencies (weekly)
  package.json
  packages/create-yoshi-app/package.json
  packages/eslint-config-yoshi-base/package.json
  packages/yoshi-angular-dependencies/package.json
  packages/yoshi-common/package.json
  packages/yoshi-flow-bm-runtime/package.json
  packages/yoshi-flow-legacy/package.json
  packages/yoshi-helpers/package.json
  packages/yoshi-server-tools/package.json
  packages/yoshi-server/package.json
  packages/yoshi-stylable-dependencies/package.json
  renovate.json
  yarn.lock
Labels: PR: Chore :construction_worker:

#2101 Yoshi Server: less strict return type restrictions
  packages/yoshi-server/src/types.ts
Labels: PR: New Feature :rocket:

#2099 add a message to the readme that only wix employees can contribute
  README.md
Labels: PR: Docs :memo:, 📜 Documentation

#2103 Fix `devtools` option in `jest-yoshi.config.js` not working bug
  packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/globalSetup.js
Labels: PR: Bug Fix :bug:

#2104 Don't make full page reload if client HMR is defined
  packages/yoshi-common/src/webpack-dev-server.ts
Labels: PR: Bug Fix :bug:

#2056 thunderbolt - Add `editor-elements-registry` to bundling check
  .gitignore
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Internal :house:

#2111 Yoshi Server: Support ambassador
  packages/yoshi-server/package.json
  packages/yoshi-server/src/bootstrap.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#2106 Yoshi server: init server
  packages/yoshi-common/src/webpack-utils.ts
  packages/yoshi-server/package.json
  packages/yoshi-server/src/bootstrap.ts
  packages/yoshi-server/src/routes/api.ts
  packages/yoshi-server/src/server.ts
  packages/yoshi-server/src/types.ts
  test/javascript/features/yoshi-server/init-server/init-server.test.ts
  test/javascript/features/yoshi-server/init-server/src/api/greeting.api.js
  test/javascript/features/yoshi-server/init-server/src/component.js
  test/javascript/features/yoshi-server/init-server/src/init-server.js
  test/javascript/features/yoshi-server/init-server/src/routes/app.js
  test/javascript/features/yoshi-server/init-server/src/templates/app.ejs
  test/scripts.ts
  test/typescript/features/yoshi-server/init-server/init-server.test.ts
  test/typescript/features/yoshi-server/init-server/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/init-server/src/component.tsx
  test/typescript/features/yoshi-server/init-server/src/init-server.ts
  test/typescript/features/yoshi-server/init-server/src/routes/app.ts
  test/typescript/features/yoshi-server/init-server/src/templates/app.ejs
Labels: PR: New Feature :rocket:

#2112 [create-yoshi-app:dev]: Improve symlink strategy to ignore development types
  scripts/utils/symlinkModules.js
  scripts/utils/symlinkModules.ts
Labels: PR: Internal :house:

#2114 Use inline source maps for worker locally to support loading worker as a blob
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#2110 Override viewerScript, viewerWidget, editor and settings urls for local mode.
  packages/create-yoshi-app/templates/flow-editor/javascript/.application.json
  packages/create-yoshi-app/templates/flow-editor/typescript/.application.json
  packages/yoshi-config/src/config.ts
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/commands/start.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/utils.ts
Labels: PR: Flow Editor 🖼, 🖼 Flow Editor

#2116 bootstrap-hot-loader: change `BootstrapContext` to be `any`
  packages/bootstrap-hot-loader/src/types.ts
Labels: PR: Bug Fix :bug:

#2118 [flow-library]: Fix example's package.json
  packages/create-yoshi-app/templates/flow-library/typescript/example/{%packagejson%}.json
Labels: PR: Flow Library 📚

#2117 [flow-library]: Bundle name will be [name].umd.js
  packages/create-yoshi-app/templates/flow-library/typescript/dev/index.html
  packages/yoshi-flow-library/src/webpack.config.ts
Labels: PR: Flow Library 📚

#2122 Resolve tsc bin only when tsc-process is used
  packages/yoshi-common/src/tsc/tsc-process.ts
Labels: PR: Bug Fix :bug:

#2121 Always separate css and always use css modules
  packages/yoshi-flow-library/src/config/normalize.ts
  packages/yoshi-flow-library/src/config/types.ts
  packages/yoshi-flow-library/src/config/validConfig.ts
  packages/yoshi-flow-library/src/webpack.config.ts
Labels: PR: Flow Library 📚

#2120 Do not run bundle if the user didn't specify it
  packages/yoshi-flow-library/src/commands/build.ts
Labels: PR: Flow Library 📚

#2080 add public path to prod source maps; use plugin directly
  packages/yoshi-common/src/source-map-plugin.ts
  packages/yoshi-common/src/webpack.config.ts
  packages/yoshi-flow-legacy/config/webpack.config.js
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Bug Fix :bug:

#2123 Consider overridePlatformBaseUrls when building a query + build it with join-url.
  packages/yoshi-flow-editor/package.json
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/utils.ts
  yarn.lock
Labels: PR: Flow Editor 🖼, 🖼 Flow Editor

#2124 [yoshi-editor-flow]: Use withStyles wrapper and always separate css
  packages/yoshi-flow-editor-runtime/src/EditorAppWrapper.tsx
  packages/yoshi-flow-editor-runtime/src/WidgetWrapper.tsx
  packages/yoshi-flow-editor/src/webpack.config.ts
  packages/yoshi-flow-editor/src/wrappers/templates/ComponentWidgetEntry.ts
Labels: PR: Flow Editor 🖼, 🖼 Flow Editor

#2126 Use React as an external module for thunderbolt-elements
  packages/yoshi-common/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#2127 Resolve stylable dependencies from cwd.
  packages/yoshi-common/src/@stylable/utils.ts
Labels: PR: Bug Fix :bug:

#2128 update contributing with an up to date 'release-a-new-version' guide
  CONTRIBUTING.md
Labels: PR: Docs :memo:

#2125 Yoshi Server: support csrf
  packages/yoshi-server-client/src/index.ts
  packages/yoshi-server/package.json
  packages/yoshi-server/src/server.ts
  test/javascript/features/yoshi-server/csrf/csrf.test.ts
  test/javascript/features/yoshi-server/csrf/src/api/greeting.api.js
  test/javascript/features/yoshi-server/csrf/src/component.js
  test/javascript/features/yoshi-server/csrf/src/routes/app.js
  test/javascript/features/yoshi-server/csrf/src/templates/app.ejs
  test/typescript/features/yoshi-server/csrf/csrf.test.ts
  test/typescript/features/yoshi-server/csrf/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/csrf/src/component.tsx
  test/typescript/features/yoshi-server/csrf/src/routes/app.ts
  test/typescript/features/yoshi-server/csrf/src/templates/app.ejs
  yarn.lock
Labels: PR: New Feature :rocket:

#2115 Yoshi Server: add a test for initData on routes
  test/javascript/features/yoshi-server/init-server/init-server.test.ts
  test/javascript/features/yoshi-server/init-server/src/routes/app.js
  test/javascript/features/yoshi-server/init-server/src/templates/app.ejs
  test/typescript/features/yoshi-server/init-server/init-server.test.ts
  test/typescript/features/yoshi-server/init-server/src/routes/app.ts
  test/typescript/features/yoshi-server/init-server/src/templates/app.ejs
Labels: PR: Internal :house:

#2130 create-yoshi-app:dev should include the experimental flows
  packages/create-yoshi-app/scripts/dev.js
Labels: PR: Internal :house:

#2133 Don't transpile with ts-node/register files ignored by git
  packages/yoshi-common/src/require-hooks/ts-node-register.ts
Labels: PR: Bug Fix :bug:

#2135 [editor-flow] Settings panel fixes.
  packages/yoshi-flow-editor-runtime/package.json
  packages/yoshi-flow-editor-runtime/src/styles/wix-base-ui.global.scss
  packages/yoshi-flow-editor/src/server/templates/editorApp.vm
  packages/yoshi-flow-editor/src/server/templates/settingsApp.vm
  packages/yoshi-flow-editor/src/wrappers/settingsWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/SettingsAppEntryContent.ts
  yarn.lock
Labels: PR: Polish :nail_care:, 🖼 Flow Editor

#2134 [flow-editor] Dont generate viewerScript for each widget.
  packages/yoshi-flow-editor/src/wrappers/widgetViewerScriptWrapping.ts
Labels: PR: Polish :nail_care:, 🖼 Flow Editor

#2136 Yoshi Server Tests: a tiny type fix
  test/typescript/features/yoshi-server/api-client-server-react/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/api-client-server/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/api-server-server/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/csrf/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/init-server/src/api/greeting.api.ts
  test/typescript/features/yoshi-server/return-values/return-a-string/src/api/greeting.api.ts
Labels: PR: Internal :house:

#2137 Always transpile with ts-node ts/tsx files even if they're ignored by git
  packages/yoshi-common/src/require-hooks/ts-node-register.ts
Labels: PR: Bug Fix :bug:

#2131 Finalize files transpilations (tsc, babel, copy-file)
  packages/yoshi-common/package.json
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/tsc/tsc-worker.ts
  packages/yoshi-common/src/typescript/copy-files.ts
  packages/yoshi-common/src/typescript/formatter.ts
  packages/yoshi-common/src/typescript/run-babel.ts
  packages/yoshi-common/src/typescript/tsc-process.ts
  packages/yoshi-common/src/typescript/tsconfig-enforcer.ts
  packages/yoshi-config/src/paths.ts
  packages/yoshi-flow-library/package.json
  packages/yoshi-flow-library/src/commands/build.ts
Labels: PR: Flow Library 📚

#2141 Arrange the script in flow library template
  packages/create-yoshi-app/templates/flow-library/typescript/{%packagejson%}.json
Labels: PR: Flow Library 📚

#2142 add a DEBUG environment parameter that when used, the terminal is not…
  packages/yoshi-common/src/dev-environment-logger.ts
Labels: PR: Internal :house:

#2147 disable no null assertion rule in yoshi's codebase
  .eslintrc
  packages/create-yoshi-app/__tests__/verifyNodeVersion.test.ts
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/print-build-results.ts
  packages/yoshi-common/src/server-process.ts
  packages/yoshi-common/src/storybook/storybook-worker.ts
  packages/yoshi-config/src/normalize.ts
  packages/yoshi-flow-app/src/webpack.config.ts
  packages/yoshi-flow-bm/src/createFlowBMModel.ts
  packages/yoshi-flow-bm/src/webpack.config.ts
  packages/yoshi-flow-editor/src/webpack.config.ts
  packages/yoshi-flow-library/src/commands/start.ts
  packages/yoshi-flow-library/src/webpack.config.ts
  packages/yoshi-flow-monorepo/src/verify-typescript-references.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
  packages/yoshi-server-react/src/hooks.ts
  scripts/build.ts
  scripts/customPublish.ts
Labels: PR: Internal :house:

#2152 Do not bring webpack as a dependnecy for yoshi config
  packages/yoshi-config/package.json
  packages/yoshi-config/schema/WebpackOptions.json
  packages/yoshi-config/schema/yoshi-config-schema.js
Labels: 🐛 Bug

#2145 Update eslint-config-yoshi-base for TS
  packages/eslint-config-yoshi-base/index.js
  packages/yoshi-server/src/httpErrors.ts
Labels: PR: Bug Fix :bug:

#2151 Add editor script support for yoshi-flow-editor
  packages/create-yoshi-app/templates/flow-editor/javascript/src/init.app.js
  packages/create-yoshi-app/templates/flow-editor/typescript/src/init.app.ts
  packages/yoshi-flow-editor/src/__tests__/utils.test.ts
  packages/yoshi-flow-editor/src/buildEditorEntires.ts
  packages/yoshi-flow-editor/src/model.ts
  packages/yoshi-flow-editor/src/utils.ts
  packages/yoshi-flow-editor/src/wrappers/commonEditorScriptWrapping.ts
  packages/yoshi-flow-editor/src/wrappers/templates/CommonEditorScriptEntry.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonEditorScriptEntry.test.ts
  packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonEditorScriptEntry.test.ts.snap
Labels: PR: New Feature :rocket:, 🖼 Flow Editor

#2150 change es directory name into esm
  packages/create-yoshi-app/templates/flow-library/typescript/tsconfig.json
  packages/create-yoshi-app/templates/flow-library/typescript/{%packagejson%}.json
  packages/yoshi-config/src/paths.ts
Labels: PR: Flow Library 📚

#2149 Enforce ts config improvements
  packages/create-yoshi-app/templates/flow-library/typescript/tsconfig.json
  packages/yoshi-common/package.json
  packages/yoshi-common/src/typescript/ensure-typescript-installed.ts
  packages/yoshi-common/src/typescript/tsconfig-enforcer.ts
  packages/yoshi-common/src/write-json.ts
  packages/yoshi-flow-monorepo/src/verify-typescript-references.ts
  test/scripts.ts
Labels: PR: Flow Library 📚

#2153 remove yoshi egg splash screen
  packages/yoshi-flow-library/src/cli.ts
  packages/yoshi-flow-library/src/yoshi-egg.ts
Labels: PR: Flow Library 📚

#2140 Library flow readme
  packages/yoshi-flow-library/README.md
  packages/yoshi-flow-library/src/commands/start.ts
  packages/yoshi-flow-library/src/commands/test.ts
Labels: PR: Flow Library 📚, 📜 Documentation

#2156 Fixing the test watch command
  docs/getting-started/usage.md
Labels: PR: Docs :memo:

#2148 added support for custom cdn certificate
  packages/yoshi-common/src/cdn.ts
  packages/yoshi-common/src/dev-environment.ts
  packages/yoshi-common/src/webpack-dev-server.ts
  packages/yoshi-helpers/src/rewrite-forward-proxy.ts
Labels: PR: Internal :house:

#2154 re-structure the config for library flow
  packages/create-yoshi-app/templates/flow-library/typescript/{%packagejson%}.json
  packages/yoshi-flow-library/src/commands/build.ts
  packages/yoshi-flow-library/src/commands/start.ts
  packages/yoshi-flow-library/src/commands/test.ts
  packages/yoshi-flow-library/src/config/normalize.ts
  packages/yoshi-flow-library/src/config/types.ts
  packages/yoshi-flow-library/src/config/validConfig.ts
  packages/yoshi-flow-library/src/webpack.config.ts
Labels: PR: Flow Library 📚

#2158 fix(yoshi-flow-editor-runtime): Fix ssr by checking `window` presence.
  packages/yoshi-flow-editor-runtime/src/WidgetWrapper.tsx
Labels: PR: Bug Fix :bug:, 🖼 Flow Editor

#1974 Yoshi server testing
  test/javascript/features/yoshi-server/api-client-server-react/src/components/App/App.spec.js
  test/javascript/features/yoshi-server/api-client-server-react/yoshi-server.test.ts
  test/javascript/features/yoshi-server/api-client-server/api-client-server.test.ts
  test/javascript/features/yoshi-server/api-client-server/src/client.js
  test/javascript/features/yoshi-server/api-client-server/src/component.js
  test/javascript/features/yoshi-server/api-client-server/src/component.spec.js
  test/typescript/features/yoshi-server/api-client-server-react/src/components/App/App.spec.tsx
  test/typescript/features/yoshi-server/api-client-server-react/yoshi-server.test.ts
  test/typescript/features/yoshi-server/api-client-server/api-client-server.test.ts
  test/typescript/features/yoshi-server/api-client-server/src/client.tsx
  test/typescript/features/yoshi-server/api-client-server/src/component.spec.tsx
  test/typescript/features/yoshi-server/api-client-server/src/component.tsx
  test/yoshi-publish/package.json
Labels: PR: New Feature :rocket:

#2143 [Flow library]: Do not exit when there is a babel parsing error during start
  packages/yoshi-common/src/typescript/run-babel.ts
Labels: PR: Flow Library 📚

#2157 add umd named define option
  packages/yoshi-flow-library/src/webpack.config.ts
Labels: PR: Flow Library 📚

#2165 Fix suricate configuration for monorepo flow
  packages/yoshi-flow-monorepo/src/scripts/start.ts
  packages/yoshi-flow-monorepo/src/webpack.config.ts
Labels: PR: Polish :nail_care:

#2163 [library-flow]: Fix line and column order for link to issue feature
  packages/yoshi-common/src/typescript/formatter.ts
Labels: PR: Flow Library 📚, 🐛 Bug

#2166 Yoshi Server: use jest transform on e2e tests
  packages/jest-yoshi-preset/jest-preset.js
Labels: PR: Bug Fix :bug:

#2168 Strip the organization name from the default library option
  packages/yoshi-flow-library/src/commands/start.ts
  packages/yoshi-flow-library/src/config/normalize.ts
  packages/yoshi-flow-library/src/utils.ts
  packages/yoshi-flow-library/src/webpack.config.ts
Labels: PR: Flow Library 📚

#2167 feat(yoshi-flow-editor): Add migraiton guide
  packages/yoshi-flow-editor/docs/OOI_TO_EDITOR_FLOW_MIGRATION_GUIDE.md
Labels: PR: Docs :memo:, 📜 Documentation

#2172 add yoshi-flow-library's bin to the package.json's files array
  packages/yoshi-flow-library/package.json
Labels: PR: Flow Library 📚
